### ISSUE TITLE
Survival Instinct does not allow movement to a connecting location

### ISSUE THREAD

**Issue by Malacante** [halogenandtoast/ArkhamHorror#100]
As seen here: https://i.imgur.com/WRbSI07.jpeg
A successful test with Survival Instinct allows me to disengage with each other enemy, but presents no option to move to a connecting location. This may be a problem with "The House Always Wins" as I also had a similar issue with Elusive in this scenario

**Comment by Malacante** [comment]
Upon selecting "do not move to a connecting location", the game softlocked

**Comment by halogenandtoast** [comment]
Should be fixed now.
