### ISSUE TITLE
Hawk-Eye Folding Camera Willpower boost turns off during treacheries

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#1000]
As described, I should have 5 willpower during the test but the stat goes down to 4 when the test starts.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/60739c82b5cfb0b70ef9bf395ce855a2412763093b87c01d4b06efc460640805.json

**Comment by halogenandtoast** [comment]
It looks like this is a result of wracked

 ![Image](https://github.com/user-attachments/assets/d170f897-887c-4e42-8ebe-f781819167c6)

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/efb69b7b-2702-40f8-b0b4-daa558dfd49b)
