### ISSUE TITLE
Peaks of Thock does not flip with resolving of its text after passing the test on the location

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#1001]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 378 for game 37d82a13-bc9c-4cc2-aa60-344803d6d165 without step 377", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/13f3f0542abf2c8e98e6769b5defb2dbace2a085130555383fce35f3c419dbb7.json

**Comment by halogenandtoast** [comment]
Once this fix is out, you'll need to undo your test, turn on debug mode, hit debug on the location and "Reset" it, then you can do the test again and it should flip correctly.
