### ISSUE TITLE
Offerings on Masks

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#1006]
Offerings on masks can be replenished over 2

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1d52d58b087ec5b1de12b594816d21a89229f4b2d3804accdead8aa27b967cc6.json

**Comment by halogenandtoast** [comment]
Are you saying

1) The app is incorrectly replenishing over 2 

or

2) The app is not and should be replenishing over 2

The file you sent me I think only has Sparrow's Mask and I don't see it going over 2, which is correct. When it is replenishing it can only replenish up to it's printed uses.
