### ISSUE TITLE
Undo to reset starting investigator

### ISSUE THREAD

**Issue by Ralphus1701** [halogenandtoast/ArkhamHorror#1019]
Safe.fromJustNote Nothing, Invalid question type
CallStack (from HasCallStack):
  fromJustNote, called at library/Entity/Answer.hs:281:13 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Entity.Answer

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c29e590e5200ad42343b99a74cda193da77ce7305f19f6dcda10f8216a63ea13.json

**Comment by halogenandtoast** [comment]
This error usually means you just undid too fast and/or need to refresh. There are reasons the app can get out of sync and I plan to try and fix them at some point, but for now you should be able to do this with a refresh.
