### ISSUE TITLE
Investigate option cannot be selected in this location

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#1024]
When I click the location I just see a black circle. I don't see the option to Investigate. Now that I mention it, I for example also don't see any options anymore when clicking the Ornate Bow. In fact, all cards that used to show options for what to do with them when you clicked them don't work anymore and just show a circle instead now.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d9f6fa00d8a7323fdb687cc23d5492b1f2878157f08b3a8984dc130dfd3648e0.json

**Comment by bobdole12** [comment]
Noted this too!
