### ISSUE TITLE
Dr. Milan doesn't exhaust when using latest taboo

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#1026]
I noticed that after updating my deck to the latest taboo, Milan no longer exhausts after succesfully investigating.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/0d2090b873feb7840fbfd96ffdc96bb59331ad8ebe66e1c0de53871f1e698363.json

**Comment by halogenandtoast** [comment]
@ChrisIsMyMiddleName when did you upgrade your deck? The taboo list is showing as empty for this deck which makes me think it might have been upgraded before I added support for the list. I added it yesterday and I just tried loading the deck you are using and it picked it up correctly so maybe it was a timing thing?

**Comment by ChrisIsMyMiddleName** [comment]
@halogenandtoast Yeah I suspected that might be it, this game started basically very soon after the list was on ArkhamDB, so before it was implemented here. Reloading the decks that use the new list should work then, I'll try that.
