### ISSUE TITLE
Hunting Shadow - Unable to spend clue

### ISSUE THREAD

**Issue by ghdevo** [halogenandtoast/ArkhamHorror#1027]
**Provide a Game ID**
Playing on local copy

**Describe the bug**
Hunting Shadow does not give me the option to spend clues, just assign damage (Roland).
[arkham-debug (13).json](https://github.com/user-attachments/files/17613913/arkham-debug.13.json)

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/19e31538-c16a-40df-ab28-132c3a541900)

**Comment by ghdevo** [comment]
Duh.  Well, at least that was an easy one.  Thanks!

**Comment by halogenandtoast** [comment]
No worries, this one comes up occasionally. I'll eventually add some sort of UI indication to help make it easily discernible as to why.
