### ISSUE TITLE
Azathoth attacking on failing test (tablet token effect) causes bug

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#1031]
Safe.fromJustNote Nothing, trying to convert source ChaosTokenEffectSource Tablet but can't
CallStack (from HasCallStack):
  fromJustNote, called at library/Arkham/Helpers/Ref.hs:50:3 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Helpers.Ref
  sourceToTarget, called at library/Arkham/Enemy/Runner.hs:890:40 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Enemy.Runner
  runMessage, called at library/Arkham/Enemy/Cards/Azathoth.hs:41:23 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Enemy.Cards.Azathoth
  runMessage, called at library/Arkham/Enemy.hs:32:15 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Enemy
  runMessage, called at library/Arkham/Entities.hs:195:45 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2852:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4624:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/df4efea97210181d97d820d8afa77e3e928f03cde6bedf9d6057790f9cccbcbc.json

**Comment by halogenandtoast** [comment]
Couple of odd things here. First... Skids should be dead. But because of how I queue up the Mythos Card draw he still ends up drawing, so I have a fix for that and for this token issue.
