### ISSUE TITLE
I cant do anything

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#1035]
I cant do anything. Its blocked. I can go backwards with undo, but i can play next action.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/dbf18998f939649d2af851433ce5369b0d06ee989032b58cb87155babbd92f8e.json

**Comment by halogenandtoast** [comment]
The issue was the skill test ending prematurely due to Delilah's ability. I have a fix incoming, but you'll need to step back to before triggering Delilah and then you should be set.
