### ISSUE TITLE
No idea what happened

### ISSUE THREAD

**Issue by adran06** [halogenandtoast/ArkhamHorror#1036]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 264 for game 3a503391-a159-431e-9d72-c0f240323893 without step 263", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f8ecf64a3576bb459e8285d7e5ba3486f73e8dbb65b6aba5fc2aefaa5c24714b.json

**Comment by halogenandtoast** [comment]
Sometimes there is a timing conflict between responses, as long as you can continue you can ignore this issue for now, I'll eventually figure out how to prevent this...
