### ISSUE TITLE
Don't know what happened but it says to report.

### ISSUE THREAD

**Issue by adran06** [halogenandtoast/ArkhamHorror#1038]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 345 for game 3a503391-a159-431e-9d72-c0f240323893 without step 344", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4c95f47fa0d4a8ce6fd853a4eca83052d50b2ba3e4849e27a40fbd7fa1c35cb5.json

**Comment by halogenandtoast** [comment]
I think this is a timing issue, I will figure out how to fix this eventually, but for now you can ignore this.
