### ISSUE TITLE
Can't advance act (The unspeakable oath)

### ISSUE THREAD

**Issue by Kwaice** [halogenandtoast/ArkhamHorror#1040]
Got 6 clues and can't advance act in 2 investigators game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1cb39f173a71c0074fb15c3e71309714109aeab8068d500c962766b361ea5d16.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/028af50c-1e63-424b-9f8b-1401540647d6)

Calvin can't advance because he has this in hand, but you can switch to Kōhaku (by clicking on the eye in the tab) to advance.
