### ISSUE TITLE
Multiple masks

### ISSUE THREAD

**Issue by SteffenAP** [halogenandtoast/ArkhamHorror#1049]
You cannot play a new mask if another one is in play, you should be able to replace it

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/7b5d72c478d06b4eeef6891d29c6a5a5e84fda7036f3a07635a2215ddd546e9d.json

**Comment by halogenandtoast** [comment]
Masks cannot be replaced right, if you have one mask in play you are stuck until something forces it to be discarded

> Limit 1 Mask per investigator.

> Some limits may pertain to a particular play area, such as "Limit 1 per deck," "Limit 1 in the victory display," or "Limit 1 in play." This limit restricts the number of copies of that card (by title) that can exist in the specified play area. Another copy of that card cannot enter the specified play area if this limit has already been reached. Remember that limits are player specific unless otherwise noted. For example, a card with "Limit 1 per deck" can exist in two different investigator decks.
