### ISSUE TITLE
Cannot create a new game

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#105]
Just pulled the latest update (23 BST), rebuilt the images and reloaded the page (after clearing the cache) and when I try to create a new game, the "CREATE" button gets enabled once all the required details are specified. However nothing happens if I press the button...

**Comment by halogenandtoast** [comment]
Can you look at the network tab in your browser and see if there is any response. This usually happens when the frontend can't read the backend data structure. I'd highly recommend shift-refreshing or clearing your cache to avoid any artifacts from an old build.

**Comment by halogenandtoast** [comment]
I should mention I just did a huge overhaul and a lot may be broken. I will be verifying every currently implemented card so things might be majorly broken right now.

**Comment by stefano-bragaglia** [comment]
I’ve tried it on the latest Safari, in a Private Tab after a Force clearing cache in the Developers menu, and on Chromium. On Chromium it was the first time I ever tested the app, so there weren’t any scripts cached there.

I’ll check the messages in the console after work. Thanks for now!

**Comment by stefano-bragaglia** [comment]
I hope this is what you were asking me to check... let me know if I have to check something more specific.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/4399978/178560020-9159e8bd-dc14-48fc-9600-b7e10f1768fc.png">

Of course, I updated to the latest commit, cleared the cache and hard reloaded before taking this screenshot.

**Comment by halogenandtoast** [comment]
Yeah that's close it would be helpful to use the network tab and actually see the error response. That error does at least confirm the issue is not the frontend, so the net best guess is the database being invalid somehow.

**Comment by stefano-bragaglia** [comment]
I see, please see below the network tab.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/4399978/178699714-73c3982e-fd35-4f89-a53a-5fb84985376e.png">

I usually update with:

    docker-compose down
    git pull
    docker-compose up --build --force-recreate

I'm trying with `docker-compose down -rmi all` to recreate the Postgres image from scratch.

**Comment by halogenandtoast** [comment]
Also @stefano-bragaglia just want to express my gratitude that you have been helpful when the app isn't working for you. I know it could be annoying to have something broken on arrival, but the feedback will help me improve the overall interaction in the future. Part of the issue is, and may continue to be for a bit, that the data model keeps changing as I try to simplify the code or need new features to handle cases. Once I get through covering and testing all the cards from Carcosa, I will likely try to make the code more resilient to the data model changing, but that's a bit of work in itself so I have been putting it off.

**Comment by stefano-bragaglia** [comment]
No worries @halogenandtoast, 
I'm kinda familiar with the procedure, and I'm happy to help.
If I had actually more time to spare, I'd be happy to learn some Haskell to help more...

Anyway, I updated everything and it started to work again!
The aesthetic touch-ups are actually nice!

I should probably open another ticket, but I played a game to test everything was fine and I realised I cannot commit Vicious Blow to a Fight started on a Machete. Please find the game state below.

[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/9103639/arkham-debug.json.gz)

**Comment by halogenandtoast** [comment]
I just checked this, I was able to commit it right after skipping the fast actions window

**Comment by stefano-bragaglia** [comment]
Oh duck! 
After sometime I play, I forget that I have to get past the fast action window. Sorry!
