### ISSUE TITLE
A wild debug pop-up appeared

### ISSUE THREAD

**Issue by Evelf** [halogenandtoast/ArkhamHorror#1061]
I was trying to investigate with Augur, nothing seems wrong. After I accepted to file a bug the game went back to the previous step.

There's also an issue just after that, but maybe it's unrelated and more about the rules implementation: even though I didn't choose to discard Augur previously, the game asked me which other cat I want from the discard pile.

> SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 103 for game 3ffb91fe-b6f1-4bfb-a198-fbaac5c3f5b3 without step 102", sqlErrorDetail = "", sqlErrorHint = ""}
>
> file: https://arkham-horror-bugs.s3.amazonaws.com/exports/cb2eda491cc75da776ab7a24b04a7a53511fd6f04dde55981b0702c10f26942b.json

**Comment by halogenandtoast** [comment]
Probably means you clicked through too fast and it decided you meant to trigger augur. I'm not sure there is anything I can do about this, but I will hopefully have a solution that gets rid of the initial error message. I keep trying new things to no avail.
