### ISSUE TITLE
Streetwise trigger is not available

### ISSUE THREAD

**Issue by seenev** [halogenandtoast/ArkhamHorror#1073]
When I have Dig Deep and Streetwise level 3, it only gives me the option to spend resources for Dig Deep and not Streetwise.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3f3d37f79d46c6c57b36fb4215c8d31e7b645e9f467e9b38afa5b5f1fc7f468b.json

**Comment by halogenandtoast** [comment]
Streetwise costs 2 resources, you only have 1

**Comment by seenev** [comment]
Maybe you're right. I don't recall. I thought I had the resources between family inheritance and my resource pool. Is there a way to see if family inheritance had resources on it? Sorry if false alarm.
