### ISSUE TITLE
Undo to play a card I meant to play.

### ISSUE THREAD

**Issue by faris-cloud** [halogenandtoast/ArkhamHorror#1081]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 1428 for game 24b0f172-32c3-47a4-ae3b-ddfe24511eac without step 1427", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/36b3741dbed02cb59908453601dfdf6990c1a28a66ac9cfdd0bced7fa3dc683e.json

**Comment by halogenandtoast** [comment]
Whenever you see the "Cannot insert step" feel free to ignore it and try again, it should work.
