### ISSUE TITLE
Scenario 1 Binoculars effect reversed

### ISSUE THREAD

**Issue by reamonntiu** [halogenandtoast/ArkhamHorror#1082]
The one with binoculars get Eyes in the Dark, while everyone else gets Shape in Trees when selected.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/93e228be6aaaff8f2843f4734be880fa95133ffa89f311a279e6208b92359eb4.json

**Comment by halogenandtoast** [comment]
Turns out it wasn't backwards, but it was checking Provisions instead of Binoculars...
