### ISSUE TITLE
Eldritch Tongue not working with "Beguile"

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1086]
Unable to play "Beguile" from the discard pile with Eldritch Tongue

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/554ffbbf63dfbcfbf63e1191ce95c1746f5c74e7b92b67b0e8f67081d5654d3e.json

**Comment by halogenandtoast** [comment]
I have a fix for this soon, but keep in mind beguile will get removed from the game after attaching so it's sort of useless I think:

> FAQ 2.3: Q: If I use Eldritch Tongue to play an event that attaches to another card, such as Beguile, when does that event get removed from the game? A: An event that attaches to another card is considered “resolved” when all abilities and effects triggered by it entering play resolve, including its attachment effect. If you play Beguile using Eldritch Tongue, Beguile will attach to the enemy, then immediately get removed from the game

**Comment by grabben2** [comment]
And congrats on 1000 issues closed! 🥳 

I really love what you've done and are doing. 
I hope you don't get discouraged by the number of issues we raise, you're doing amazing work on this.
