### ISSUE TITLE
"Get over here" cannot be used

### ISSUE THREAD

**Issue by AUscarface79** [halogenandtoast/ArkhamHorror#1093]
It seems that I am unable to play "Get over here" even though I have both the resources to play it and there is an enemy 2 locations away.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3f54d117909484ae397ca76b2778d975d33fd399fb4d59b2d725f9df228cac52.json

**Comment by grabben2** [comment]
I'm not the dev, but just read your bug report. 
You say the enemy is 2 locations away, but I think "Get over here" only works on an enemy in a connecting location (= 1 location away).

**Comment by AUscarface79** [comment]
True. I should have specified that the issue is with "Get over here (2)", which extends the range to 2 locations. I just checked and the card can be played if the enemy is one location away, so it seems that the range upgrade is not working.

**Comment by grabben2** [comment]
Ah, didn't know about the upgraded version, sorry about that!
