### ISSUE TITLE
Tablet option to remove clues from Brood does not work

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1094]
When drawing the tablet, the option to remove clues from a brood to avoid "-4" is not possible.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4139c512cc5799955ef137af329838b5ed10ddad4048425034bae48e1b262e5f.json

**Comment by halogenandtoast** [comment]
Good call, I'll have a fix for this shortly.

However, your situation is doomed as removing the two clues from the Brood will drop the +4 bonus you are getting from Esoteric Formula.
