### ISSUE TITLE
Zamacona spawn instructions not followed

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1118]
Zamacona spawns engaged with Alessandra instead of nearest empty location

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c3bec2515d3b764845988ff3b514af900bf5cb4d61b87c454174f6074162143e.json

**Comment by halogenandtoast** [comment]
@grabben2 so actually the spawn is working as expected here. You have an additional cost to move from Arcane Barrier, and as part of that skill test you committed guts which draws Zamacona. During that part you are still at the Entrance and Museum Halls is empty -which is where Zamacona spawns. After that you then complete the move, and then become engaged.
