### ISSUE TITLE
Money talks card commits

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#1121]
I should not be able to commit cards in the test that I played Money Talks. (Except for few skill cards)

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/fc3c39bbf00040066493ac9b8aa8f14b0dee3391f10c2de09eac257e5cc01f70.json

**Comment by zzdldl31** [comment]
Also, I was not given a timing window to trigger free trigger abilities before card commit (between ST1 and ST2) when have Money Talks in my hand (both when I use it or not? not tested though)

**Comment by halogenandtoast** [comment]
@zzdldl31 what are you trying to trigger during your skill test? ![Image](https://github.com/user-attachments/assets/18777a0b-cbef-4754-97dc-606034150933)
This setting is going to probably disable some stuff

**Comment by halogenandtoast** [comment]
If it's Stealth (3) I'm going to add that to "affect the outcome"

**Comment by zzdldl31** [comment]
I believe it was 'well connected'
