### ISSUE TITLE
(TCU)Watcher's Grasp and Prey-

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#1122]
Prey- keyword is not properly applied with Watcher's Grasp.
The spectral watcher was engaged with Mandy, Agnes drew watcher's grasp, the watcher does not move, yes, but since two investigators are in the same location, the watcher should change its engagement to Agnes. Therefore hitting Agnes.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e638ae120430574c68dc95713475271adac0642b0c8b8e55e4b0514c46aadac8.json

**Comment by halogenandtoast** [comment]
The spectral watcher is not going to disengage though. So it's not going to change here.
