### ISSUE TITLE
Hovering over bottom half of "Next" button in replays doesn't highlight the button

### ISSUE THREAD

**Issue by max-torch** [halogenandtoast/ArkhamHorror#1126]
**Provide a Game ID**
Load any game replay

**Describe the bug**
Observed on Microsoft Edge.
When mouse cursor is hovered over the bottom half of the "Start" and "Previous" buttons, the buttons highlight; but, when the mouse is hovered over the bottom half of the "Next" button, the button is not highlighted. See video snip:

https://github.com/user-attachments/assets/e9c6281e-de0f-4298-b573-c66ad41ba1e9

**Comment by halogenandtoast** [comment]
The issue is that the footer overlaps this (the ffg copyright one). I'm updating the buttons and adding some text below so it won't overlap anymore (and look a bit nicer).

![Image](https://github.com/user-attachments/assets/0606fe25-47da-44c5-b924-a1c4218eb06c)
