### ISSUE TITLE
More True Magick headaches

### ISSUE THREAD

**Issue by Kwaice** [halogenandtoast/ArkhamHorror#1131]
I think i should be allowed to use True Magick to trigger Blood Pact ability from my hand during this test

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/cc70b726b513d2d0cf26794889b62b5431328459839fb42bedbaee7218d96c76.json

**Comment by halogenandtoast** [comment]
True Magick is treated as a copy of the card it is mimicking for the duration of that ability. Therefor, in this case it cannot be used on Blood Pact because it is currently Wither.
