### ISSUE TITLE
Emerging Deep Ones do not spawn exhausted

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1132]
They should spawn exhausted and unengaged unless they are at a fully flooded location

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e16ec8040c5d8743de5608bb56626106643807c1efa5d16c2a7f5db9cff64340.json

**Comment by halogenandtoast** [comment]
@grabben2 youy only trigger the revelation when the card is drawn. The last Emerging Deep One here was spawned via Deep One Invasion so you would not get the revelation effect.
