### ISSUE TITLE
Opportunist not discarded after failed test

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1134]
Used Jacqueline's ability to draw 3 tokens, cancelled the autofail. Two "Opportunist" were committed to the test and both should be discarded because the test failed, but they are both returned to hand.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c0d5465cfceca70e694916e51bfc5728087a5e996e1677d8f2e2b3ea1e9350f8.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/4f917fde-23f1-42cd-8dfb-b273f1a384e8)

I think you accidentally uncommitted them...

You can see here before you cancelled the autofail they are back in your hand already, when I step back through the log it looks like 1 was committed, and then uncomitted.
