### ISSUE TITLE
Plan of Action does not draw a card when committed during the second action of the turn

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#1139]
Game ID: c90c1960-b19f-4a90-818f-89d80e0cd38d

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e4e0c7c18759dca9c45e45ac1b2b0f2245cc9c1d6766daf8645248cb40b80d7d.json

**Comment by halogenandtoast** [comment]
@kyle-tieng it did draw a card, it drew Day of Reckoning which attached to the current agenda.
