### ISSUE TITLE
Active Games not showing up in Active Games list

### ISSUE THREAD

**Issue by mtwebb** [halogenandtoast/ArkhamHorror#114]
ran truncate arkham_games cascade to start clean database
started a new game 
clicked home and no games are listed. 

tested using: https://github.com/halogenandtoast/ArkhamHorror/commit/75892a07fe7d094a06a02c46b04018a3a247ff4e

**Comment by halogenandtoast** [comment]
This generally means there was a parsing error, can you check:

* The javascript console and/or network request, the response of the network request will sometimes include the sql error, but my guess here is that something is amiss regarding the database
* If you are running the server manually there should be some error logs, if you are using docker than you likely won't have easy access to those.

**Comment by mtwebb** [comment]
I'll see if I can repro again.  Tailing the log I see: 

2023-03-14 19:44:17.198 PDT [4930] ERROR:  duplicate key value violates unique constraint "steps_game_step_idx"
2023-03-14 19:44:17.198 PDT [4930] DETAIL:  Key (arkham_game_id, step)=(393ad598-54cc-4af2-9198-d0e8b65db727, 133) already exists.

**Comment by halogenandtoast** [comment]
That tailed output usually has to do with pressing undo or other game elements too fast

**Comment by halogenandtoast** [comment]
Going to close as not reproducible for now, if you run into the issue again, just let me know, but generally speaking the main reason this happens is I change the structure of something and the frontend can't parse the old format anymore. It's quite a bit of work to support old and new formats so I need to add some way for it to automatically delete these invalid games and let you know.
