### ISSUE TITLE
Lots of locations in play, not sure what went wrong for this one.

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#1142]
could not find label
CallStack (from HasCallStack):
  error, called at library/Arkham/Location/Cards/PrismaticCascade.hs:35:20 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Location.Cards.PrismaticCascade
  runMessage, called at library/Arkham/Location.hs:33:18 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Location
  runMessage, called at library/Arkham/Entities.hs:210:47 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2875:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4677:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/527c971686b6fd112aa7e63d02ca1bfea09ea30d31464ebed55bdf85618a62cb.json

**Comment by halogenandtoast** [comment]
So there was an issue where a prismatic cascade got duplicated. Once I deploy a fix you can fix your game by hitting undo twice, right clicking, hitting inspect, going to the console, and entering;

```
sendDebug({"tag": "ObtainCard", "contents": "6dd91202-5774-4317-9dd8-e3b3d53bb55e"})
```
