### ISSUE TITLE
Error after track shoes test

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1144]
No messages for chooseOne
CallStack (from HasCallStack):
  error, called at library/Arkham/Message.hs:1214:18 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Message
  chooseOne, called at library/Arkham/Asset/Assets/TrackShoes.hs:38:14 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Asset.Assets.TrackShoes
  runMessage, called at library/Arkham/Asset/Runner.hs:70:15 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Asset.Runner
  runMessage, called at library/Arkham/Entities.hs:213:44 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2876:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4679:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b4556f22fcf45d7060711f40eb0ebc0004d9fb9116a96ffded40f33e084b34a8.json

**Comment by grabben2** [comment]
Sorry, didn't really look at your comment until now. There must be some rule I'm totally missing. 
What is it in the agenda that is stopping me from moving?

**Comment by halogenandtoast** [comment]
Actually I was wrong here. I thought it was the Ocean movement causing +2 actions BUT I misread the traits. Turns out both Bootlegger's did not have the correct location connections listed.

**Comment by grabben2** [comment]
I still can't move in my game even though I undid the whole move action and retried.

**Comment by halogenandtoast** [comment]
Fixing the connections is hard, you'd need to reset the location, but it messes up it's position in the grid in this game. I can't fix this game exactly, so if you need to move into that location I suggest using debug mode and dragging your investigator onto it. Sorry for the trouble here.

**Comment by grabben2** [comment]
No worries, I did not realize I could do that, good to know! :-)
