### ISSUE TITLE
Success instead of failure of a skill test

### ISSUE THREAD

**Issue by Kwaice** [halogenandtoast/ArkhamHorror#1147]
Test 5 against 3, draw -3, somehow succeeded by 2.
Pretty sure another test in this scenario that should have failed succeeded instead.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c935d46ac0f9502475bd67fa047e4bf0f1dd257299fc55a19a52a9714267ffb4.json

**Comment by Kwaice** [comment]
Seems that the tablet token is just treated as a "0"

**Comment by halogenandtoast** [comment]
Turns out none of the tokens were actually implemented in this scenario.
