### ISSUE TITLE
Unable to advance agenda

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1149]
Have more than the right number of clues but can't advance

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/76593c1bf81051a900aac3d2bc35ce571d1db4e6a9331660b3ef6dc4e6deb91c.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/419370d6-27a0-4782-8b3a-f23875caa9ff)

This prevents it.

**Comment by grabben2** [comment]
Oh, shoot! This app is a learning experience.. I've missed a lot of rules when playing with physical cards over the years. Invalidating probably all my previously successful campaigns..
