### ISSUE TITLE
Storm of Spirits - Inconspicous Zoog, odd behaviour

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1153]
This is maybe a rules question, but I think in the end it works as intended, however with some erratic behaviour.
Using Storm of spirits to defeat a swarm of Inconspicous Zoog. This should (imo)  defeat the whole swarm at once.
But each defeated zoog triggers the reaction to move to a new location exhausted. Then the next zoog gets defeated which triggers another move to a connecting (where options include a location only connected to the original location).
Debug state is after the "incident", so you would need to rewind to see it in action.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/095b2b5df8ca1f1de948eb6dcc0a5dff59a91ba7a10e151729ba300575bdb0a3.json

**Comment by halogenandtoast** [comment]
I think because it's a when window it's working within the rules. The forced ability is a "When" so it happens before the effects of defeat (which would discard the swarm card) so the ability has to trigger because the host cannot be defeated yet.

**Comment by grabben2** [comment]
Yes I agree, probably correct overall. 
But the final "move" feels weird, that you are able to select a location connected to the original location but not connected to the current location of the enemy group. It does not matter for the end result since they are all defeated, but if the host somehow would survive it would matter..

**Comment by halogenandtoast** [comment]
Ah this case is Enchanted Woods The Moon Tree IS connected to Enchanted
Woods Mystical Forest
[image: Screenshot 2024-11-29 at 18.59.43.png]

**Comment by grabben2** [comment]
Ah that's right, I didn't realize cause the connections overlay each other.. Thanks for the explanation.

**Comment by halogenandtoast** [comment]
No problem! I was confused by it at first too!
