### ISSUE TITLE
Chaos token chaos with Jacqueline and Olive

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1154]
Skill test 2 on 3. Use Jacqueline's ability to draw 3 tokens. First token: Use Olve's ability to draw 3 more.
Olive draw: 0, -1 and Elder sign. Choose to resolve ES and 0.
Jacqueline draw: 0, -3 (and 0, ES from Olive). Choose to cancel -3 and one 0. 
Results in the 0 getting selected as a token and a card draw as if the Elder Sign was cancelled.
If I "Undo" and select to cancel the other 0 token it works as it should.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b1c5e629ec51eb8fce46a4a56c2fd8d42c5c19472324169cb609017eae6d5520.json

**Comment by halogenandtoast** [comment]
So this one is sort of working as intended, but I think the UI might be slightly confusing here is what happens:

step1) drawing one token
step2) Use Jaqueling: drawing 3 tokens, lets call them: x, y z, you will cancel 2 of these, so at the end only x,y, or z will be valid
step3) Use Olive on x, so now x = [a, b, c] and you will choose to keep 2
step4) Resolve the draw x = [ElderSign, Zero, -1]
step5) Cancel the -1, so now x = [ElderSign, Zero]
step6) Resolve the other tokens so we have:
* x = [ElderSign, Zero]
* y = Zero
* z = -3

step7) So now you cancel 2, the -3 is obvious so you are left with:
* x = [ElderSign, Zero]
* y = Zero

If you cancel either token in x, the entirety of x is cancelled

![Image](https://github.com/user-attachments/assets/a6d877ef-aec0-471e-a5a4-0143c5c96a80)

The tokens get slightly shifted when cancelling so x is the "stack" of the zero and the eldersign, so cancelling the single zero leaves you with the group of ElderSign, Zero whereas cancelling either of the other tokens will result in just the singular Zero. I'll update the UI soon on this.
