### ISSUE TITLE
Evading exhausted enemy

### ISSUE THREAD

**Issue by morvael** [halogenandtoast/ArkhamHorror#1176]
I was able to evade Harbinger of Valusia for a second time, despite it was being exhausted and not engaged with me. "Unlike the fight and engage action, an investigator can only perform an evade action against an enemy engaged with him or her."

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c6702c3e235b28ab93444b61de91a9eed306227e5252be418e949680a1d12b3e.json

**Comment by morvael** [comment]
I guess it's because it stayed "engaged" with me for his special retaliate rule to work?

**Comment by halogenandtoast** [comment]
For some reason this game ended up being exported pretty far after this happened? Do you know how far back I need to go?

**Comment by halogenandtoast** [comment]
This was due to entombed
