### ISSUE TITLE
Honed Instinct

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#1180]
After playing honed instinct, playing Blur did not consume any action nor resources; maybe a bug regarding Quick Thinking? idk

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/07a4fd364e89872eba1ba14a6bef579d54af7dd86d39cd5a18ec1bcd54b00052.json

**Comment by halogenandtoast** [comment]
I think I fixed this recently, when I undo back I can no longer play Blur (likely due to the resources).
