### ISSUE TITLE
Winifred free trigger ability not available (or not obvious)

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#1186]
When committing two different cards to a skill test by Winifred, I can't use her ability to draw a card.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e0b77c9c941c978f38dc8dcd57485bf8c8ea9fc7f84ba30cbdeef41295947ea6.json

**Comment by Kwaice** [comment]
You probably need to untick the "skip triggers" in View > View Settings

**Comment by halogenandtoast** [comment]
I'm goign to fix her ability to not require you to untick that.
