### ISSUE TITLE
Kate Withdrop

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#1191]
Cannot trigger Kate's ability while testing at a flash window

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ed45f99fc491e333a30f8a66dbfa01ca49cfd6cc750b9f38dadb78c99ea90d88.json

**Comment by halogenandtoast** [comment]
@ZhouHao268 The issue is as @Kwaice posted, by default we skip fast abilities to prevent the game from slowing down, but you can disable it if you need to by

> You probably need to untick the "skip triggers" in View > View Settings

Or you can hit Shift + S to pull up the settings
