### ISSUE TITLE
Drew Mob Enforcer again, should have been removed from play

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1192]
First time I drew the weakness I paid him off to put him on the discard. Later, drew "Abandoned and alone" to remove the discard pile from the game. Now he shows up again on a card draw (I have since cycled through the deck). Are weaknesses not removed from the game by "Abandoned and alone"?
I do not have the advanced version of "A&A".

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/053d8a16af32fd368e1f3750df215b7ca8b8a6bb04ee23543573fd82573185c5.json

**Comment by halogenandtoast** [comment]
You're drawing Abandoned and Alone after you shuffle your discard back into your deck so the Mob Goons is already back into your deck at this point.

**Comment by grabben2** [comment]
Really sorry about that, must have misremembered the sequence.
Feature request: More detailed action log to quickly look back instead of having to "Undo" (takes a lot of time).
