### ISSUE TITLE
Bugs Everywhere! (e.g. Dragon Pole Doesn't Modify Attack)

### ISSUE THREAD

**Issue by Ener-G-Productions** [halogenandtoast/ArkhamHorror#1200]
As of today, a wide array of bugs have shown up out of nowhere for both me and my friend playing both single player and co-op campaigns with different investigators. In this particular example, the Dragon Pole _sometimes_ doesn't increase strength or damage when arcane slots are filled.

### Dragon Pole Example
file: https://arkham-horror-bugs.s3.amazonaws.com/exports/7e0591d50cbeb392458c0f6fdeae8433e5062593f5b389e738f4c2031ca5e0a4.json

<img width="585" alt="Screen Shot 2024-12-07" src="https://github.com/user-attachments/assets/0dbdcbca-7fd4-4243-bc53-35150188ca7b">

### Other Examples
Examples of other bugs we found that sometimes do and sometimes don't trigger:
[arkham-debug.json](https://github.com/user-attachments/files/18049269/arkham-debug.json)
- Track Shoes don't provide passive Agility increase and trigger at inappropriate times.
- Cat Mask fails to add increases to skill checks
- Lily Chen's willpower Discipline, when Broken, fails to notice damage dealt by itself in its Unbroken state earlier in the round.
- Lola Hayes can commit cards outside her role.
- "The King's Edict" encounter card triggers both its effects after the targeted player chooses one.

**Comment by halogenandtoast** [comment]
There was an issue I missed whilst trying to improve performance, I believe this should be resolved now.
