### ISSUE TITLE
spectral razor

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#1201]
Using the Spectral Blade with a deep gank does not add the fist value to the head value. Just use the fist value.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f249751a79bbe9f08bc9b3e018d15d1f38bed0ff412ecd1f6405f30641ee95ed.json

**Comment by halogenandtoast** [comment]
This was a bug that I fixed in the past day, should be good now.
