### ISSUE TITLE
Error when defeated

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1204]
Defeated by both damage and horror

no investigators
CallStack (from HasCallStack):
  error, called at library/Arkham/Game/Runner.hs:1748:13 in arkham-api-0.0.0-J2rBCSLY8ZaIBqcTg9CTr2:Arkham.Game.Runner
  runGameMessage, called at library/Arkham/Game/Runner.hs:2912:13 in arkham-api-0.0.0-J2rBCSLY8ZaIBqcTg9CTr2:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4743:19 in arkham-api-0.0.0-J2rBCSLY8ZaIBqcTg9CTr2:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/0b9bb0615c136dded1e309cdb776fd8f39b69ad4c04783c09069a89fc0dbcb0a.json

**Comment by halogenandtoast** [comment]
Once I mark this as completed, you can run this in the console to get past this issue:

```
sendDebug({ "tag": "ForTarget", "contents": [{"tag": "ScenarioTarget"}, {"tag": "RestartScenario"}]})
```

**Comment by grabben2** [comment]
Thanks, but how do i access the console?

**Comment by halogenandtoast** [comment]
In your browser you right click, hit something like "Inspect" in the drop down menu, find the tab that says console and paste that in.
