### ISSUE TITLE
Yorick elder sign bug

### ISSUE THREAD

**Issue by Kwaice** [halogenandtoast/ArkhamHorror#1206]
Couldn't return a card to hand after a successful test

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8f47dff9d5ca4090b62aba795c4eef7ac16e62ca3d7db69145c087223b6f0e1a.json

**Comment by halogenandtoast** [comment]
Your discard is empty? Skill cards don't get discarded until Step 8, which is before the elder sign effect would resolve.
