### ISSUE TITLE
No Visual Cue When Treachery is Drawn

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#121]
First of all I want to say that I'm impressed by the progress you've made since I last played: so much cards implemented and the UI is much better now!

I've managed to tweak Docker's settings, and for now I can compile the project. I'm afraid I've reached the limit of my machine so I won't be able to test it anymore of newer releases will require more memory.

But let's go back to the issue: I'm playing Wendy in Return to the Night of the Zealot. I'm in the 2nd turn in, I press "End Turn".
I automatically draw a card which is, I suppose, my treachery Abandoned and Alone (2 direct horror and remove the discard pile from the game).
I suppose it is my treachery because the only control I can interact with is my horror token pile.
after taking the horror, Abandoned and Alone actually appear in my discard pile.

Everything works fine, I think it would be better to show the treachery if not in the hand (it technically never reach my hand) in a popup (such as the one to bypass the window to play fast cards after a test is performed).

Arigatou gosaimas and keep up the awesome job!

**Comment by halogenandtoast** [comment]
Thanks for creating this issue. I agree on the interaction, I need to make all treacheries move obvious and there are some tools in the app to let me do that. I'm doing some big refactorings at the moment (changing how I handle zones like pursuit and the void in preparation for changing how I handle enemies spawning), but afterwards I'll focus a bit more on some UI tweaks.

**Comment by halogenandtoast** [comment]
> I've managed to tweak Docker's settings, and for now I can compile the project. I'm afraid I've reached the limit of my machine so I won't be able to test it anymore of newer releases will require more memory.

I recently made a change that should cause it to use up less memory, let me know if you see any improvement.

**Comment by stefano-bragaglia** [comment]
Thank you! Will do!

**Comment by halogenandtoast** [comment]
Added a visual cue.
