### ISSUE TITLE
Winnifred Habbamock uses Crystallizer of Dreams

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#1210]
Winnifred Habbamock cannot draw a card when she commits cards attached to Crystallizer of Dreams

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/666d18ce6a5b0d2ddf978ce70b84eec0f4d68912d8953669fbec2d92a7982719.json

**Comment by Kwaice** [comment]
Did you untick the Skip Trigger in the View settings ?

**Comment by ZhouHao268** [comment]
I didn't. But I unticked the Skip Trigger in the View settings and tried some times later, and it did not work.
In this file:https://arkham-horror-bugs.s3.amazonaws.com/exports/9d204ef68fc8a9bd7614192674b83001f483a1320bdfab78f37663f64324dbe4.json
I commit "You Handle This One" attached to Crystallizer of Dreams and Quick Thinking in my hand, but I did not draw a card.

**Comment by halogenandtoast** [comment]
So I think you just need to step forward after picking the cards, when you commit cards in this app there are a couple of steps, selecting the card is not "committing" it. Once you click on the token to draw one, it actually commits the cards and I see Winnifred being accessible then

![Image](https://github.com/user-attachments/assets/e2475fb6-c133-4d9a-9bc5-1f04ca99a988)

**Comment by halogenandtoast** [comment]
I'm also going to fix her ability to not need to uncheck the skill test settings.
