### ISSUE TITLE
Using contraband from stick to the plan having 8 resources (Enough) after play shotgun

### ISSUE THREAD

**Issue by AdrianMeizoso** [halogenandtoast/ArkhamHorror#1218]
InvalidState "Can't afford cost: Costs [ActionCost 1,ExhaustCost (AssetTarget bab863f2-6f2e-41e7-b394-1f3fa3a22fce),ResourceCost 4]"

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1af926a6f3a996d7a63e21b5e3efdeef7de428011eb1d64334b9b129f8169cea.json

**Comment by halogenandtoast** [comment]
Yeah it's actually the exhaust cost here that is the issue. Fix incoming so that the card isn't clickable when stick to the plan is exhausted.
