### ISSUE TITLE
Randolph Carter put out of play after mulligan

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1227]
Randolph was captured so should be put out of play, but he is still in the deck during Mulligan. My understanding is the initial card draw is done after setup so Randolph should already be out of play?

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/14a9624fe8310a70b71e0b8c8875e9547791ff9ada4838f80ff119d16bd8a033.json

**Comment by halogenandtoast** [comment]
Technically according to Appendix III: Setting Up The Game

Step 8. Is to draw your opening hand
Step 10. Is to perform scenario setup

**Comment by grabben2** [comment]
More evidence I’ve been playing the game wrong for years…

**Comment by halogenandtoast** [comment]
I think it's intended that he gets removed earlier though, it's just poorly handled in the framework

**Comment by halogenandtoast** [comment]
I'm going to remove him earlier.
