### ISSUE TITLE
Possession (Traitorous) kills me when it shouldn't

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1240]
Have 12 horror on me and sanity 7. Possession should only kill me if I have 14 or more horror.
I do have 2 horror on Peter Sylvestre, but those shouldn't count imo.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/fdfc0e1e93b9f21c5eff4faf51d0479b39115824c0cff3766842639df6861a80.json

**Comment by halogenandtoast** [comment]
The Pallid Mask is giving you -2 sanity
