### ISSUE TITLE
Frozen in fear

### ISSUE THREAD

**Issue by gustavoberman** [halogenandtoast/ArkhamHorror#125]
Frozen in fear appears in Mythos phase,
I move 2 times (2 actions) and still have 1 action to spend
I think the first move should have taken 2 actions
Does the debug log helps?
[arkham-debug.json.txt](https://github.com/halogenandtoast/ArkhamHorror/files/12739252/arkham-debug.json.txt)

**Comment by gustavoberman** [comment]
The same happens if I Evade, it takes just 1 action.

**Comment by halogenandtoast** [comment]
Should be fixed, it was related to a change I made on "perform" vs "taken" and the "peformed" actions weren't cleared out each round so it basically was never the "first"
