### ISSUE TITLE
Voice of Ra and Jacqueline Fine

### ISSUE THREAD

**Issue by wappowers** [halogenandtoast/ArkhamHorror#127]
I played Voice of Ra with Jackie, and used here ability and it only drew three tokens total, rather than the 5 I would expect.

**Comment by halogenandtoast** [comment]
https://github.com/halogenandtoast/ArkhamHorror/assets/201288/641c328f-93f8-4b80-bb87-f8d5557cc9af

Discussed and this is likely not an issue, but a misunderstanding of the UI which likely needs to do a better job of communicating what is going on here.
