### ISSUE TITLE
Crystallizer of Dreams cannot commit cards to other investigators' tests

### ISSUE THREAD

**Issue by corwinburdick** [halogenandtoast/ArkhamHorror#128]
The events underneath Crystallizer of Dreams are highlighted and can be committed to your own tests, but do not highlight when another investigator at your location is performing the test. Clicking on the non-highlighted cards also does nothing.

I experienced this in 2-handed solo, on the version that is being hosted.

**Comment by halogenandtoast** [comment]
Should be resolved in the latest deploy.
