### ISSUE TITLE
Game stuck after advancing Act 2a of Curtain Call

### ISSUE THREAD

**Issue by corwinburdick** [halogenandtoast/ArkhamHorror#129]
![image](https://github.com/halogenandtoast/ArkhamHorror/assets/9068244/e394a8f4-c8c5-452f-95d1-b8fadd14cc7f)

Clicking the highlighted act only shows the "Your game is out of sync, trying to reconnect..." message. It doesn't seem like there's any way to progress.

The act was advanced by investigating The Man in the Pallid Mask. The -1 chaos token, committed Glory, and test results are all from that test. Luke was the one to investigate, but the act is only highlighted when Tony is the active investigator since he's the lead.

[arkham-debug-2024-01-21-crystallizer and carcosa bugs.json](https://github.com/halogenandtoast/ArkhamHorror/files/14000350/arkham-debug-2024-01-21-crystallizer.and.carcosa.bugs.json)

**Comment by halogenandtoast** [comment]
So this issue has to do with the odd numbering for these cards (compared to others, on ArkhamDB). I've added a fix, but it's a bit weird and it won't immediately fix your issue. If you want to keep your game going you can use this file (I've manually fixed it):

[arkham-debug-2024-01-21-crystallizer.and.carcosa.bugs.json](https://github.com/halogenandtoast/ArkhamHorror/files/14006561/arkham-debug-2024-01-21-crystallizer.and.carcosa.bugs.json)
