### ISSUE TITLE
stack: not found using docker compose build.

### ISSUE THREAD

**Issue by klingeling** [halogenandtoast/ArkhamHorror#130]
I tried to use the command "docker compose build" and got the following error.
```
 => ERROR [web dependencies 8/8] RUN --mount=type=cache,id=stack,target=/root/.stack stack build --system-ghc --dependencies-only --no-termina  0.2s
------                                                                                                                                               
 > [web dependencies 8/8] RUN --mount=type=cache,id=stack,target=/root/.stack stack build --system-ghc --dependencies-only --no-terminal --ghc-options '-j4 +RTS -A128m -n2m -RTS':
0.199 /bin/sh: 1: stack: not found
------
failed to solve: process "/bin/sh -c stack build --system-ghc --dependencies-only --no-terminal --ghc-options '-j4 +RTS -A128m -n2m -RTS'" did not complete successfully: exit code: 127
```

**Comment by klingeling** [comment]
Maybe there's something wrong with my network, anyway, thanks!

**Comment by halogenandtoast** [comment]
I do think it was a network issue of some sort, I just did a clean build and did not run into this issue. Maybe there was some earlier issue? You might be able to use the images on dockerhub instead. Can you try docker compose up instead of build?

**Comment by klingeling** [comment]
I tried docker compose up, it works well. I use Github Action to build and push the images to docker hub instead of build on my computer.This worked, so I think there may be a problem with my network.
