### ISSUE TITLE
Flipping Sophie causes infinite copies

### ISSUE THREAD

**Issue by avgalapon** [halogenandtoast/ArkhamHorror#137]
Hi, I'm playing with Mark on a 3-handed solo and I encountered in what seems to be an issue.
When I flip Sophie, it causes multiple (maybe infinite) copies of the flipped version and the forced button does not disappear.

<img width="421" alt="image" src="https://github.com/halogenandtoast/ArkhamHorror/assets/25943519/1e824062-506c-44fd-b40d-9301b751e1b5">

**Comment by halogenandtoast** [comment]
Oh wow, this seems to be a pretty old bug because it relies on when asset ids were the same as their card ids to effectively replace it. Even after I fixed it though there was another fun issue, but this should work correctly now.
