### ISSUE TITLE
Multi-handed Solo doesn't work for 3+ Players

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#140]
Whenever I try to start a game with 3 players I get the "Game is out of sync" error during the select lead investigator step. When creating a 4p Multi-handed deck I get the exact same error whenever I try to add a 4th deck. 1-2 Players works as intended.

**Comment by halogenandtoast** [comment]
This should be fixed now. Thanks for the filing the bug!
