### ISSUE TITLE
Dunwich Museum Horror doesn't spawn correctly

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#142]
First spawn works as intended. 2nd spawn from Encounter cards doesn't (just causes Connection error). First Agenda advance spawn works. Encounter cards are still bugged. Also doesn't spawn after Act 2 advances, making the scenario impossible to continue. 

Also, I think the "Breaking In" option doesn't work correctly? I still got Adam Lynch as a story ally instead of Harold Walsted. Same for the act. It's still Night at the Museum instead of Breaking and Entering.

**Comment by halogenandtoast** [comment]
These should be fixed in the next deploy, thanks for filing the bug!
