### ISSUE TITLE
Bug: The Gold Pocket Watch

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#143]
Tried using it during the mythos phase. Clicked on the trigger and the card got moved out of play but it didn't seem to do anything? Still added doom and made me draw encounter cards.
Same for the phase repeat, doesn't seem to do anything.

**Comment by halogenandtoast** [comment]
Yeah there was some changes to how phases worked that broke this. it should be resolved in the next deploy.
