### ISSUE TITLE
Dunwich Lost in Time and Space error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#147]
Another Dimensions forced effect doesn't cause the Horror damage from the agenda.

You can't move to Tear through Time. Clicking it, even when unrevealed, just shows the Resign button. Clicking the button resigns the character, even from another location (doesn't even cost the 2 clues). 

Also Arcane Barrier doesn't work correctly. Doesn't trigger when moving into the area.

Game ends before Epilogue.

**Comment by halogenandtoast** [comment]
Should be all set. Also I didn't even program the epilogue, so needed that added.
