### ISSUE TITLE
The Last King error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#151]
The effect to transform the Bystanders appears bugged. Nothing happened with Ashleigh. Jordan, Haruko and Sebastien got flipped and added the interview log before the transformation. Constance worked as intended.

Resigning on the Foyer places the clues on the location instead of the act. Only the last investigator's clues get added to the act.

[arkham-debug.json](https://github.com/halogenandtoast/ArkhamHorror/files/15070568/arkham-debug.json)

**Comment by halogenandtoast** [comment]
Should be fixed.
