### ISSUE TITLE
Echoes of the Past error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#152]
- The setup is missing one Ground Floor location. Also looks really odd with the one that's there.

![image](https://github.com/halogenandtoast/ArkhamHorror/assets/9109870/c9e98cc9-a52b-4a2c-9d1f-450abed6023a)

- The agenda doesn't skip the Mythos phase doom placement.

**Comment by halogenandtoast** [comment]
Technically both locations where there, but there was a css issue causing them to overlap. I've fixed the agenda issue as well.
