### ISSUE TITLE
The Unspeakable Oath error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#154]
- Gift of Madness (Misery) makes it so you can't move between locations.
- Gift of Madness (Pity) still allows attacks against Lunatic enemies (at least Daniel).
- Mad Patient forced effect doesn't trigger.
- Dance of the Yellow King deals horror for some reason.
- Asylum Gorger ignores Spawn condition.
- Resign doesn't work. I press the button and it consumes the action but nothing happens.

**Comment by halogenandtoast** [comment]
Okay I was able to fix all of these (and some other issues with this scenario) EXCEPT:

> Dance of the Yellow King deals horror for some reason.

I don't see any way in which this could have happened. The card implementation doesn't have anything related to horror. It must have been something else, but without the debug file at that point in time, I have no way to figure it out.

Thanks again for filing all these bugs, it's been great to get these reports!

**Comment by Eleros** [comment]
> I don't see any way in which this could have happened. The card implementation doesn't have anything related to horror. It must have been something else, but without the debug file at that point in time, I have no way to figure it out.

It definitely happened multiple times when drawing the card. I've added the debug file, it should be about 4 rounds after the last draw.

Another weird issue I had this scenario was that Yorrick's trigger wasn't properly triggering when defeating enemies with his Knife or Beat Cop. But it did trigger when using Debug mode to defeat them. The ability has worked fine in every game before this scenario so I'm not sure what the cause is. I'll keep an eye out in future scenarios to see if it persists and what the cause could be.

[https://www.mediafire.com/file/6161p86dls2uv5v/arkham-debug_%25281%2529.json/file](https://www.mediafire.com/file/6161p86dls2uv5v/arkham-debug_%25281%2529.json/file)

**Comment by halogenandtoast** [comment]
Thanks, I will definitely take a look at this tomorrow to see what is going
on. I am real curious to see what is happening, my guess is that it will be
some card "overlapping" somehow. I'll also take a look at Yorrick!

**Comment by halogenandtoast** [comment]
So the answer was that something had overlapped, specifically the elderthing (and tablet) tokens were always dealing horror independent of it being on easy/standard vs hard/expert so adding those guards fixed it. Also yeah Yorrick had some oddness around if a card was playable due to it thinking you needed an action, I reworked it a bit and it should be set now.
