### ISSUE TITLE
Bug: Archaic Glyphs (Guiding Stones) + Deduction

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#159]
These two don't seem to work together? Succeeded a test by 4 but only got 3 clues total instead of 4.

[https://www.mediafire.com/file/fypze5oftkaw9pc/arkham-debug_%2528glyphs%2529.json/file](https://www.mediafire.com/file/fypze5oftkaw9pc/arkham-debug_%2528glyphs%2529.json/file)
(Also damn, these files are getting huge the longer a campaign goes on. )

**Comment by halogenandtoast** [comment]
And yes the files get big because the debug file dumps the entire undo history into the file.
