### ISSUE TITLE
A Phantom of Truth error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#160]
- Missing the 3 bonus resources from Jordan's information.
- Opéra Garnier location effect doesn't do anything (the one that doubles base skill).
- Picked the option to get attacked on Deadly Fate but didn't take any damage/horror.
- Marked by the Sign also didn't do any horror on fail.
- Stalked by Shadows fast ability only requires 1 clue instead of 1 per investigator. It can also be used more than 1/round.
- Conviction route of the Agenda doesn't subtract doom in play (for example from Spires of Carcosa).
- Agenda flip forces the move. Should be optional.
- Agenda flip moves The Organist to the farthest space away. Should be only 1 space farther.
- Auto-Fail but not really??: 
![image](https://github.com/halogenandtoast/ArkhamHorror/assets/9109870/11b479bf-e15b-4144-b05f-b4f4055caf60)
[https://www.mediafire.com/file/4apfxz6h0oopo5d/arkham-debug_%2528autofail%2529.json/file](https://www.mediafire.com/file/4apfxz6h0oopo5d/arkham-debug_%2528autofail%2529.json/file)

**Comment by Eleros** [comment]
Update to the autofail thing: It happened again in the next scenario. Again on Yorick, this time during an investigation. It's not all auto-fails, the rest so far worked as normal.

**Comment by halogenandtoast** [comment]
Re autofail, fix for that soon, I had an issue in 3 scenarios where autofail would not trigger, but it's fixed now

<img width="241" alt="Screenshot 2024-04-25 at 16 59 58" src="https://github.com/halogenandtoast/ArkhamHorror/assets/201288/22665f49-8392-48aa-8b9e-9d367d8ed496">

**Comment by halogenandtoast** [comment]
All of these issues should be resolved.
