### ISSUE TITLE
The Pallid Mask error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#162]
Okay, so some weird stuff right off the bat.

- I start out in The Gate to Hell, putting two Catacombs into play with the forced effect. But for some reason the game forces me to click on one of them afterward, revealing it in the process and triggering its forced effect. This is what it looks like right after setup:
![image](https://github.com/halogenandtoast/ArkhamHorror/assets/9109870/534fcd10-f06f-4078-82e8-0f406dd31fa4)
- The Narrow Shaft in the previous case did not offer the option to put a location "above" it.
- Well of Souls doesn't offer the "below" option. It did offer the option to put one "above" even though that spot was already taken.
- Labyrinth of Bones is missing the location to the "right".
- Stone Archways doesn't put anything into play (or puts it into an inaccessible area). It's static effect also doesn't work (should make movement to Catacombs free).
- Candlelit Tunnels also missing "right" option. Also puts one on the left even if occupied, replacing it in the process.
- Bone-Filled Cavern misses "below". 
- Shivering Pools doesn't offer the "right" option.
- Didn't get to see the remaining locations (Crypt of the Sepulchral Lamp, copies of others mentioned) but would recommend looking them over as well. 

- The Pit Below doesn't attach, it just discards itself.
- Catacombs Docent can be parleyed from any location.

Aaaand I'm stuck. Revealed every location and so can't put any more Catacombs into play. Could you fix the Debug mode Act advance button? Pressing it currently does nothing. Gonna have to take the loss otherwise to continue.

**Comment by jeyaprasath1** [comment]
https://www.tublian.com/project/86350964/7386

**Comment by halogenandtoast** [comment]
Can you send me the game id, I can download the debug for it so you don't have to upload it.

**Comment by Eleros** [comment]
> Can you send me the game id, I can download the debug for it so you don't have to upload it.

This?

eab159cd-953f-4a28-92cb-6b2d59da2878

**Comment by halogenandtoast** [comment]
Yup that helped. So all the placements in this were wrong. I had at some point changed how this was handled to read more naturally and I missed one aspect that needed to be reversed. So it would be hard for me to review the rest of the directionality based bugs here. I'm going to assume the direction ones are fixed and try to look at the others.

I might be able to fix the act advance button. One issue is that some acts depend on a specific game state so they can't all universally be advanced, but I might be able to make those specific ones error out.

**Comment by halogenandtoast** [comment]
> I start out in The Gate to Hell, putting two Catacombs into play with the forced effect. But for some reason the game forces me to click on one of them afterward, revealing it in the process and triggering its forced effect. This is what it looks like right after setup:

The forcing you to choose one is because of

> Remember "you opened a secret passageway"

**Comment by halogenandtoast** [comment]
@Eleros sorry your game was so messed up, the best I could do to "fix" it since the act needs to the tome of shadows to be in play was to add it to the right of the stone archways. This should let you proceed, but you may run into more issues due to how the connection issues really messed things up. If you get stuck again let me know. The other issues should be resolved now.
