### ISSUE TITLE
Rex elder sign token hang

### ISSUE THREAD

**Issue by Jaykee011** [halogenandtoast/ArkhamHorror#164]
When playing as Rex, whenever I draw the elder sign token, there is no choice to be made and I am therefore stuck.

![Screenshot_20240501_135354](https://github.com/halogenandtoast/ArkhamHorror/assets/7535219/48f1ded5-b783-4843-b9dc-8d9932f16689)

**Comment by halogenandtoast** [comment]
Should be fixed in the next release. It was a UI issue where you wouldn't see the options. I've fixed it and also made the final results of the skill test more accurately show the result.
