### ISSUE TITLE
Unsure what to click after choosing to add Dr. Francis Morgan to a deck

### ISSUE THREAD

**Issue by mmartinsky** [halogenandtoast/ArkhamHorror#166]
I completed House Always Wins as the first scenario, and had the option to add Morgan to a deck. However, when I click the button, nothing appears to happen. Am I missing something highlighted here?

https://github.com/halogenandtoast/ArkhamHorror/assets/9168958/987faf4a-34c1-4f0d-a634-8799284b9302

**Comment by halogenandtoast** [comment]
Ah yeah this is a bug, will fix.

**Comment by halogenandtoast** [comment]
This should have been fixed with a release a few days ago.
