### ISSUE TITLE
Conflict between [Working a Hunch] and [Cover Up]

### ISSUE THREAD

**Issue by frankzgq** [halogenandtoast/ArkhamHorror#167]
New player here.

When I use [Working a Hunch], I gain a clue normally instead of discarding that many clues from Cover Up. This shouldn't be the case, right?

By the way, fantastic project!

**Comment by eike** [comment]
This is not a technical answer, just a game-rules answer: The reaction trigger ability on Cover Up is not mandatory. (Reaction triggered abilities never are; **Forced** abilities are used for that.) So you can just get a clue using Working a Hunch even with Cover Up in your threat area. (And the same applies to normal investigations.)

So maybe you just missed the opportunity to use the ability in the interface, instead? (I have not checked if the implementation does in fact give you that option. If it does not, that would indeed be a bug.)

**Comment by halogenandtoast** [comment]
There is an issue here. It seems like I've inadvertently created two branching paths for discovering clues and one includes the proper windows and one doesn't. I need to figure out how to consolidate them.

**Comment by halogenandtoast** [comment]
Should be resolved
