### ISSUE TITLE
Diana Stanley's willpower isn't taken into account correctly 

### ISSUE THREAD

**Issue by norse-dog** [halogenandtoast/ArkhamHorror#169]
In a game with Diana Stanley, only her base willpower attribute is taken into account at least when playing the Read the Signs Event. In the case I ran into, she had 3 cards tucked, which should have resulted in a willpower of 7 for the investigation, but the test value was 4 instead.

**Comment by halogenandtoast** [comment]
This should be resolved vie 2297617d6b74799291cc3cc819caff1cf7d973eb and bd9743b4468f7c1273af17aeb24df90933ee49f3

**Comment by norse-dog** [comment]
Oh wow, absolutely amazing turn around time :)
Thank you for this wonderful project, it's my favorite discovery of the year.

**Comment by halogenandtoast** [comment]
> Thank you for this wonderful project, it's my favorite discovery of the year.

Thanks! Happy to hear it, I'll continue to try and make the project better and better and every bug filed helps immensely since it's hard to track everything.
