### ISSUE TITLE
Skill test popup not draggable on safari due to unconstrained height

### ISSUE THREAD

**Issue by norse-dog** [halogenandtoast/ArkhamHorror#170]
On OSX/Safari, the skill test dialog is taller than the surface, which hides the drag bar at the top.
Cause is unclear (it appears some content elements like the investigator and chaos token images are too tall)
The inability to drag the popup means that actions on cards are not available.
![image](https://github.com/halogenandtoast/ArkhamHorror/assets/1811613/5a26a53a-cd88-47e3-b18b-60524f6b4a3a)

**Comment by halogenandtoast** [comment]
I think this should be resolved a few deploys ago.
