### ISSUE TITLE
miskatonik museum can't advance to act 3a

### ISSUE THREAD

**Issue by randomcrit2020** [halogenandtoast/ArkhamHorror#171]
![image](https://github.com/user-attachments/assets/af4a4c62-0d5e-4824-b50c-371c22eb8334)

After trying to enter the location Exhibit Hall (Restricted Hall), the game doesn't advance to act 3a.

[arkham-debug.json](https://github.com/user-attachments/files/16261018/arkham-debug.json)

**Comment by randomcrit2020** [comment]
In this playthrough: 
[arkham-debug.json](https://github.com/user-attachments/files/16277345/arkham-debug.json)


The [Hunting Horror](https://arkhamdb.com/card/02141) was already in play and the Act advanced, in the previous example I couldn't press the choose bottom.
![image](https://github.com/user-attachments/assets/8bb3a874-c6a0-43d1-b275-157c82f11752)

**Comment by halogenandtoast** [comment]
Glad it's working now, thanks for filing a bug! I did make some fixes around this, but was going to do some more testing, but I think it is good.
