### ISSUE TITLE
Unhallowed Country doesn't activate Forced skill test at the end of turn

### ISSUE THREAD

**Issue by randomcrit2020** [halogenandtoast/ArkhamHorror#173]
[Unhallowed Country](https://arkhamdb.com/card/02088) has a forced skill test at the end of turn but the game skip it after pressing the force button.

![image](https://github.com/user-attachments/assets/9bf7f814-35c6-4ed2-a823-f544d076744b)
[arkham-debug.json](https://github.com/user-attachments/files/16302588/arkham-debug.json)

**Comment by halogenandtoast** [comment]
Thanks, this should be fixed in 900c6954ad0c57cbe9a4f8abff6daa771d3f93bc
