### ISSUE TITLE
Mr. Rook can't get card with weakness

### ISSUE THREAD

**Issue by Shamangaka** [halogenandtoast/ArkhamHorror#175]
![image](https://github.com/user-attachments/assets/dfd6c080-8d78-49c3-bf83-86c4925e2bfc)

**Comment by Shamangaka** [comment]
![image](https://github.com/user-attachments/assets/c3696ba3-449c-4957-a8ba-2af93821cc26)

**Comment by Shamangaka** [comment]
![image](https://github.com/user-attachments/assets/ec9f02ae-581b-45a5-8f90-3a0344e3840a)

**Comment by halogenandtoast** [comment]
Should be fixed in a previous deploy.
