### ISSUE TITLE
3 player game can't start

### ISSUE THREAD

**Issue by Shamangaka** [halogenandtoast/ArkhamHorror#176]
I tried to start game with my 2 friends and we chose our investigators game didn't start. We tried to play in duo with each and it was okay, so I tried to host game for 3 where I logged in of their acc in incognito mode and game started but once third player connected as usual and not by my incognito mode browser game rewinds to investigator picking screen and doesn't start. Game worked okay with 4 player game where I played with second hand in incognito mode browser.

What causes this issue?

**Comment by Shamangaka** [comment]
> @Shamangaka I am not seeing this issue, maybe there was an issue with one of the decks or something. Do you still have that game up on the site?

It can't be issue with decks becuse we tried playong solo duo and 4p, it occurs when we play 3 player game. I deleted all bugged games, but I think we can recreate the bug.

**Comment by halogenandtoast** [comment]
Okay if it happens again, please let me know the game id and then just leave the game be and I'll look into it.
