### ISSUE TITLE
Baseball Bat discarded by a skull token that's cancelled by Heavy Furs

### ISSUE THREAD

**Issue by rayduck** [halogenandtoast/ArkhamHorror#178]
Cancelled token by [Heavy Furs](https://arkhamdb.com/card/08126) still discards [Baseball Bat](https://arkhamdb.com/card/01074).

As referenced in the FAQ for Baseball bat, tokens that are cancelled entirely should not cause Baseball Bat to be discarded. However, it did while I was playing Yorick. 

[arkham-debug.json](https://github.com/user-attachments/files/16534397/arkham-debug.json)

On a side note, I tried to use the debug tool to bring it back, but couldn't find a convenient way to do so.

**Comment by halogenandtoast** [comment]
This should be fixed by f323bf0002407e90ba488bc06421204d9db1e971 and improved on in 18233f1cfc0fcc93487b751cd0dde79c497ea2ae

With regards to the debug menu it's constantly being extended so I might add something like that in the future
