### ISSUE TITLE
Some problems and suggestion after trying the website

### ISSUE THREAD

**Issue by kaixinqi** [halogenandtoast/ArkhamHorror#179]
It's a fantastic project that I love and would love to keep using.
But in the process of using, I encountered some problems:
- [Calling in Favor](https://arkhamdb.com/card/03158), the card can't correct selection of Allies, even search 9 CARDS contain the costs of a enough Allies.
- [Deciphered Reality(5)](https://arkhamdb.com/card/02303), the card after successful survey, will cause game crash, characterized by "the Apply Results" no response after click on the button.
- When using mobile devices, after clicking the Act card, the enlarged card will cover the push button in the default position, and when clicking outside the card, the push button will be withdrawn, making it difficult to press the push button
- Occasionally the home page does not load any adventure, refresh is the same. (Do not rule out my own Internet connection problems, I will try again)

And some suggestions:
- It is recommended to highlight the stage of the current step on the right timeline
- When the tarot card is drawn to the reverse position, the enlarged card is still in the forward position. It is recommended that the enlarged card of the reverse Tarot card be displayed in the reverse position
- It is recommended to provide a rollback function to reduce the negative experience caused by misoperation; However, it is not possible to roll back random actions (such as drawing chaos bags, drawing player/encounter cards, etc.) or unknown actions (such as advancing Act, filp location card).
- I hope Chinese translation can be supported, I will be glad to provide the translated text of the website first, and look for supplementary card pictures (the translated card text can be found at [arkhamdb](https://zh.arkhamdb.com))

**Comment by halogenandtoast** [comment]
> [Calling in Favor](https://arkhamdb.com/card/03158), the card can't correct selection of Allies, even search 9 CARDS contain the costs of a enough Allies.

I just tried this card myself and didn't run into any issue, can you send me the game id (from the url) of the game this happened to you.

> [Deciphered Reality(5)](https://arkhamdb.com/card/02303), the card after successful survey, will cause game crash, characterized by "the Apply Results" no response after click on the button.

This should be fixed now in c331372089dc105e4e8a37ef7755ee7126dd3e2b

> When using mobile devices, after clicking the Act card, the enlarged card will cover the push button in the default position, and when clicking outside the card, the push button will be withdrawn, making it difficult to press the push button

I'll try to figure out a solution for this on mobile, I think I need to do some sort of long tap to show the large image on mobile but I don't have experience with setting that up yet. I'll break that into a separate issue from this one.

> Occasionally the home page does not load any adventure, refresh is the same. (Do not rule out my own Internet connection problems, I will try again)

Sometimes after I make updates games are broken and I need to fix them. At the moment all games should be fixed so if you are still running into the issue now, let me know.

> The current stage should be darker, were you suggesting something else 
<img width="196" alt="Screenshot 2024-08-11 at 11 13 43" src="https://github.com/user-attachments/assets/1626c554-19f2-48ed-958b-9237733bc245">

What would make this better.

> When the tarot card is drawn to the reverse position, the enlarged card is still in the forward position. It is recommended that the enlarged card of the reverse Tarot card be displayed in the reverse position

That is weird, I know it works correctly when I do a reading, which browser are you using?

<img width="719" alt="Screenshot 2024-08-11 at 11 16 09" src="https://github.com/user-attachments/assets/173fde76-8c5c-4864-9dd0-c535b44477ff">

> It is recommended to provide a rollback function to reduce the negative experience caused by misoperation; However, it is not possible to roll back random actions (such as drawing chaos bags, drawing player/encounter cards, etc.) or unknown actions (such as advancing Act, filp location card).

At the moment the undo button is mainly meant for me to debug, in the future I will definitely extend it's functionality

> I hope Chinese translation can be supported, I will be glad to provide the translated text of the website first, and look for supplementary card pictures

Upgrading the text would be easy as I have i18n built in currently (it will be harder to update a lot of the button text but it is doable). If you want to provide Chinese for the website text (non-card text) I can update that now and start working on gettings the cards into i18n. The hardest part for me is finding the campaign text, if you have access to the campaign guides in chinese that would be helpful for me.

**Comment by kaixinqi** [comment]
Thanks a lot for your reply.
> [Calling in Favor](https://arkhamdb.com/card/03158), the card can't correct selection of Allies, even search 9 CARDS contain the costs of a enough Allies.

> I just tried this card myself and didn't run into any issue, can you send me the game id (from the url) of the game this happened to you.

I tried once more, and found it would not reduce its cost by X. the game id is 80c45089-2af7-42bb-ae92-2967be67e45b



> When the tarot card is drawn to the reverse position, the enlarged card is still in the forward position. It is recommended that the enlarged card of the reverse Tarot card be displayed in the reverse position

> That is weird, I know it works correctly when I do a reading, which browser are you using?

I found the game id, is 130bc1cd-72b1-4a45-939e-ae16dbbd64d1
![image](https://github.com/user-attachments/assets/a5400ff0-d82d-4e44-bdbf-5c55e67aedaf)
Also, in this game, when I lose the last horror, I will lose connect from server, so this record is still there...

> I hope Chinese translation can be supported, I will be glad to provide the translated text of the website first, and look for supplementary card pictures

> Upgrading the text would be easy as I have i18n built in currently (it will be harder to update a lot of the button text but it is doable). If you want to provide Chinese for the website text (non-card text) I can update that now and start working on gettings the cards into i18n. The hardest part for me is finding the campaign text, if you have access to the campaign guides in chinese that would be helpful for me.

The translated campaign guide text can be found at another project [arkham-cards-data](https://github.com/zzorba/arkham-cards-data). For Chinese, you can found at ```i18n/zh/campaigns/notz/arkham.po```

**Comment by halogenandtoast** [comment]
Regarding the tarot card, I see now! Yes thanks, should be fixed in 8377e68618ceb68f42c62cb0964d88b6914727cf (deploy should be live in about an hour).

I'll look into the remaining issues

**Comment by halogenandtoast** [comment]
> I tried once more, and found it would not reduce its cost by X. the game id is 80c45089-2af7-42bb-ae92-2967be67e45b

Thanks I see the issue here too! Should be fixed in b5c51c7a2c6987bef70b4a5c9a820346f74aaeba (again will take about an hour to deploy).

**Comment by halogenandtoast** [comment]
I think these things were all fixed, if any are still broken can you open a new issue. Thanks!
