### ISSUE TITLE
Issues with attacking using Act of Desperation and while being affected by a Treachery

### ISSUE THREAD

**Issue by paradoxcat** [halogenandtoast/ArkhamHorror#183]
Game ID: `c4c58f18-845d-4332-8801-8c5fdbdd73af`

1. The game will not let me use `Act of Desperation`, even though I can fulfil either requirement (1 hand item asset in hand or in play). (I know I have `Dissonant Voices` but this was still true before that).
2. I cannot use `Roland's .38 Special` on the Ghoul Priest, since when I select it, the fight button is hidden below the Treachery and I cannot select it.
![image](https://github.com/user-attachments/assets/28a4e81a-d5e8-4072-ab90-64ab7d5af923)

**Comment by halogenandtoast** [comment]
This should be resolved now.
