### ISSUE TITLE
Cannot fight enemy with card effects if enemy is next to another enemy or treachery in the threat area

### ISSUE THREAD

**Issue by jakespurgeon1** [halogenandtoast/ArkhamHorror#184]
![Screenshot 2024-08-13 at 12 58 30 PM](https://github.com/user-attachments/assets/e0fc40d6-6354-41c5-9c88-6e4622528f79)

to help recreate issue:
Spirit Athame to attack rats, which is next to striking fear — the fight button appears behind adjacent card after selecting curse tokens.

Chrome 127.0

**Comment by jakespurgeon1** [comment]
https://arkhamhorror.app/#/games/4cd58a0c-26a0-4005-bb94-2ac899fa5c68

**Comment by halogenandtoast** [comment]
This should be resolved now.
