### ISSUE TITLE
Steadfast symbols not committing correctly.

### ISSUE THREAD

**Issue by Sqwirril** [halogenandtoast/ArkhamHorror#188]
Game ID:  https://arkhamhorror.app/#/games/b9b4f502-951c-45c2-a142-497db0c18003

Game state:
committing "STEADFAST" to a "Crypt Chill" unmodified brain test of difficulty of 4 whilst having one card under Diana Stanley. (2 against test:4)

total current sanity damage: 3
total current health damage: 1
total remaining health and sanity combined = 7+7-3-1 = 10.  meaning steadfast should commit for 3x total brain symbols, but is only committing for 1.

**Comment by Sqwirril** [comment]
BTW this project rocks.  I love it!  huge fan - thank you and keep up the AMAZING WORK!

**Comment by halogenandtoast** [comment]
Seems like the game was deleted and I can't recreate this issue, so I'm going to close this and if it happens again you can reopen it

![Image](https://github.com/user-attachments/assets/d01382f7-6999-49ca-9737-642f5b929cbb)

You can see I tried to recreate the same issue (health and damage set).  The result is

Base 1 + 3 from steadfast - 0 from the token = 4. When I also tried with a card underneath her, I got 5.

Maaaaybe something I did between when you opened this ticket and when I got to it changed something?

One thing of note: The icons don't get calculated until after you draw your token for technical reasons (probably will calculate them when you commit in the future).
