### ISSUE TITLE
Popup (forced, etc) occurs behind other engaged items and cannot be resolved.

### ISSUE THREAD

**Issue by wschlundt** [halogenandtoast/ArkhamHorror#189]
Was playing along and sometimes the action for an engaged enemy ends up behind a second card making it impossible to trigger the forced action (or possibly others)

Before I click the forced item:
![image](https://github.com/user-attachments/assets/deaa7700-bb08-4d08-903d-dc17dd283872)

After I click the forced enemy: 
![image](https://github.com/user-attachments/assets/af2684bc-bdcb-47dd-912c-abcd8a7a9f35)

You can see just a little of the dark area Highlighted here:
![image](https://github.com/user-attachments/assets/6b35e439-1607-49ff-945f-61b82dbd327d)

**Comment by wschlundt** [comment]
Game ID: 50e90ad1-4016-45c1-a8e2-ee1306908f0f

**Comment by Sqwirril** [comment]
Was also having this issue in Game ID: https://arkhamhorror.app/#/games/b9b4f502-951c-45c2-a142-497db0c18003

**Comment by edalven** [comment]
Also had this issue occur.
https://arkhamhorror.app/#/games/4a10e284-f1e6-4476-99a1-97112080e3df
Could not use workaround suggested by @Sqwirril 
Microsoft Edge Version 127.0.2651.98

**Comment by halogenandtoast** [comment]
Should be resolved now, those popups should have gone up (not to the right).
