### ISSUE TITLE
Committing Cards from other investigators.

### ISSUE THREAD

**Issue by Sqwirril** [halogenandtoast/ArkhamHorror#192]
Game ID:  https://arkhamhorror.app/#/games/cc70083e-6ba8-46f8-992e-e868cfdd62cd

Cannot commit Darrel's "Resourceful" (1 fight symbol) to Carolyn's Fight test against the rats (they are at the same location).

Rules state that each other investigator at the same location as the investigator taking the test may commit one card with matching symbols.

**Comment by rubcar91** [comment]
I ran into this same problem. Ursula could not commit cards to a test by Leo.

**Comment by halogenandtoast** [comment]
<img width="306" alt="Screenshot 2024-08-15 at 19 00 49" src="https://github.com/user-attachments/assets/06cc47b3-5fc5-4168-873e-65baa780357e">

Did you click specifically on the eye here?

The first game on this issues is deleted so I can't check it anymore.

**Comment by halogenandtoast** [comment]
I wasn't able to recreate the issue. In all cases I checked the option to commit one card was available.

**Comment by Sqwirril** [comment]
Resolved. thanks - user error with UX.

**Comment by halogenandtoast** [comment]
No worries, at some point I'll add an instruction pane when you create a multihanded solo game that covers stuff like this. Glad it is working though.
