### ISSUE TITLE
Cannot spend clues to advance the act

### ISSUE THREAD

**Issue by rubcar91** [halogenandtoast/ArkhamHorror#198]
Playing Extracurricular Activity in Dunwich Legacy. In a 2 player game, we need 6 clues to advance the act. I have 6 clues but there is no option to spend them to advance the act.

Game ID: https://arkhamhorror.app/#/games/ff1b99bc-ae4a-4ece-ac30-2123313d8fcf

EDIT: Apparently, because it was the beginning of the investigation phase I had to choose a player to take their turn before the option to advance the act was available. However, even after choosing an investigator (Leo Anderson), I had to use or skip his beginning of turn trigger before the option to advance the act was available.

**Comment by halogenandtoast** [comment]
You can only advance the Act during a regular Fast player window which is why you had to wait and skip the beginning of turn trigger.
<img width="948" alt="Screenshot 2024-08-17 at 0 34 15" src="https://github.com/user-attachments/assets/ef965b1a-c5f8-4b3e-8a0c-bfadd6eaea50">
