### ISSUE TITLE
Dim Carcosa 

### ISSUE THREAD

**Issue by corwinburdick** [halogenandtoast/ArkhamHorror#199]
Game: 0c73cae0-4a96-40ef-a66c-ab06f2c63ad2

I took a run through most of Dim Carcosa for what ended up being a pretty big stress test. I hope these reports are helpful and not too spammy!

## Black Market:
- [x] #238
- [x] #239
- [x] #240

## Stealth:
- [x] #243
- [x] #244
- [x] #245

## Lost Soul:
- [x] #246
- [x] #247

## Other
- [x] #236
- [x] #237
- [x] #248
- [x] #255
- [x] #249
- [x] #250
- [x] #251
- [x] #252
![image](https://github.com/user-attachments/assets/2a6db52e-d32c-4747-9d4a-e1ad24de7567)
- [x] #242
- [x] #253
- [x] #254
- [x] #256
    * For more details since this was the most complex bug I saw, here's the most basic sequence that triggered this error:
        * Investigate using Uncanny Growth
        * Commit Deduction and Perception
        * Succeed by 3
        * Trigger Experimental Hypothesis reaction
        * Trigger Perception, drawing Lost Soul
        * Skip other triggers
        * Try to move to the Lost Soul test, but I can't get to it revealing a token without going out of sync

**Comment by halogenandtoast** [comment]
@corwinburdick I tried to recreate the last issue, but it worked for me. It's possible all the other things I've been fixing lately someone resolved it. Let me know if you run into it again.

**Comment by halogenandtoast** [comment]
Also this report was super helpful! I just had to be disciplined to break it up, but so much got fixed!
