### ISSUE TITLE
Cannot move to a new location with engaged enemy

### ISSUE THREAD

**Issue by ghdevo** [halogenandtoast/ArkhamHorror#201]
Trying to move to a new location with engaged enemy.  I'm expecting to take damage but the game highlights the enemy.  Clicking the enemy doesn't seem to do anything and typical horror/health buttons do not activate.  Leaving the game at this state.

https://arkhamhorror.app/#/games/020cd482-8fbb-49d4-9059-a1498bb85838

**Comment by halogenandtoast** [comment]
> Clicking the enemy doesn't seem to do anything and typical horror/health buttons do not activate. 

When I just tried this the health and horror buttons activated for me.

**Comment by halogenandtoast** [comment]
Ohhhhh I bet I know what might have happened. The abilities menu was being hidden, so clicking the enemy popped up the prompt to do the "Forced" but you couldn't see it. That was fixed recently so you should be able to continue now!
