### ISSUE TITLE
Overlay issue for actions 6c1f9da2-569a-4718-af6f-423c3088eea4

### ISSUE THREAD

**Issue by Thrawp** [halogenandtoast/ArkhamHorror#202]
Hello,

I'm running Return to The Gathering and my weakness came out and is now covering the space next to the ghoul I'm engaged with and when I try to attack using my machete it puts the action choice overlay under the weakness instead of over it so I cannot select the "fight" action.

**Comment by halogenandtoast** [comment]
Might just need to refresh. I fixed this earlier and checked out your game and it seems okay now.

**Comment by Thrawp** [comment]
Yup, it's working now, I apparently missed the other post. Thanks
