### ISSUE TITLE
Student Union Location Causes Sync Issues

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#205]
Moving to the (previously unrevealed) Student Union in Extracurricular activity, then resolving the **Forced** effect seems to cause problems (i.e, can't continue the game from that point). Something about the Dormitories already being in play, maybe? I'm not sure. 
The game ID is c3ec2fcf-0193-4122-ab61-04e668a9085b
I had this issue on a previous game also.

Additionally, what an incredible project! Its release will surely not have a negative impact on my productivity!

**Comment by halogenandtoast** [comment]
Thanks for the kind words!

Yeah Dormitories being in play was creating an issue. There is a fix incoming.
