### ISSUE TITLE
When Arkham Woods in NotZ Senario 3 all Investigate actions use Fist regardless of if you are investigating the location

### ISSUE THREAD

**Issue by BlazeInt** [halogenandtoast/ArkhamHorror#208]
When on Arkham Woods in NotZ Scenario 3, all Investigate actions use Fist. Not all Investigate actions performed at this location should use Fist. Only if you are investigating the location should Fist be the skill used.
I'm playing as Jenny and trying to resolve Searching for Izzy but it is forcing me to use Fist instead of Book.

**Comment by eike** [comment]
No, I think this is correct. Investigate actions *always* investigate a location (hence why they use the shroud value), usually your current one. So when Searching for Izzie, you are still investigating the Arkham Woods, and whenever you do this, you are forced to use Fist.

**Comment by halogenandtoast** [comment]
This is the correct behavior, you will be forced to use fist for any basic or bold **Investigate** action.
