### ISSUE TITLE
`Cannot return card from discard pile with Yorick when drawing an elder sign

### ISSUE THREAD

**Issue by paradoxcat** [halogenandtoast/ArkhamHorror#209]
Game ID: https://arkhamhorror.app/#/games/bdf14c40-0a7b-4ac4-874c-867af1e0a5a1

Great job on the project!

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/54e14755-c52a-491d-8352-1e999906206c)

You have this guy preventing it.

Thanks for using and enjoying the project!
