### ISSUE TITLE
Unable To Resign From Scenario

### ISSUE THREAD

**Issue by Blujacket** [halogenandtoast/ArkhamHorror#216]
Scenario 1 of Path to Carcosa is having a syncing issue only when trying to resign from the scenario. I can take other actions as normal.

Game link ID is 4aa43966-af14-4884-90fb-d88ce4f97ef3

**Comment by lariatstoboy** [comment]
Just to add to this, I had the exact same issue on game: 28706b3d-cb4b-4fe6-9b07-4d2a44e01ce9

I advanced the turn once and was able to resign after that. 

However, now on Resolution 1 I'm getting a continuous loop of de-sync and re-syncing every time I try to resolve the text box
