### ISSUE TITLE
Swarming Enemy doesn't die

### ISSUE THREAD

**Issue by nicksephton** [halogenandtoast/ArkhamHorror#219]
I was engaged with two swarming enemies. I attacked one using Mind over Matter (using investigate as combat) and it died. I attacked the second one, and it just has a damage on it but isn't dying, despite having only one health. 
![Screenshot 2024-08-15 220034](https://github.com/user-attachments/assets/c1691b61-fadb-4f82-8675-1b9831f80bc4)

**Comment by halogenandtoast** [comment]
Can you provide the game id?

**Comment by halogenandtoast** [comment]
Ah actually I think I know what might have happened. If that damage was already on the swarming enemy I need to add a check after a swarm dies to check the host.

**Comment by nicksephton** [comment]
> Can you provide the game id?

43095263-0092-43a9-8f09-dea141baa883
