### ISSUE TITLE
Occult Lexicon not adding Blood-Rites

### ISSUE THREAD

**Issue by DilirConfar** [halogenandtoast/ArkhamHorror#224]
**Provide a Game ID**
ee2292aa-af8c-4d6f-b063-cbe9fe50bc52

**Describe the bug**
Played Occult Lexicon(3), I had no blood-rite added to the hand and deck-size didn't increase.

Thanks for the amazing work anyway, this app is wonderful!

**Comment by halogenandtoast** [comment]
I have a fix for this one, but you won't be able to see it during this scenario, it will take place during the next scenario you do though (once deployed).
