### ISSUE TITLE
Hyperphysical Shotcaster is not discarded the moment no aether remains on it

### ISSUE THREAD

**Issue by kortatu** [halogenandtoast/ArkhamHorror#226]
**Provide a Game ID**
GameID: 0ea5ba4b-bf57-4f98-8e19-7edddece0bbc

**Describe the bug**
Shotcaster should be discarded the moment the fourth ether is used (not at the end of the combat/investigation/evasion but inmediately). Currently is not discarded at all. What should happen with Yorick is that when the fourth aether is discarded, the shotcaster is inmediately discarded (before even the skill test starts), and if that skill is a a fight and defeats an enemy, Yorick can use his ability to retrieve and play again the shotcaster from the discard.

**Comment by kortatu** [comment]
The Shotcaster is still not discarded after I spent all aether. Do I need to restart the game? I tried adding aether and spending it again.

**Comment by halogenandtoast** [comment]
It needs to be a new "instance" of the shotcaster for it to work. But you can enable debug mode and manually discard it if you would like your game to keep going.
