### ISSUE TITLE
Lost in the Wilds effect is persistent

### ISSUE THREAD

**Issue by ggdabuh** [halogenandtoast/ArkhamHorror#228]
Lost in the Wilds prevents you from exploring. At the end of the turn, the card is discarded but the effect persists

**Comment by halogenandtoast** [comment]
Do you have a game id for this? I did not implement this as a lingering effect.

**Comment by halogenandtoast** [comment]
I've run some tests and could not recreate this issue. I'll wait to see if you have the game id for the game that had this issue.

**Comment by ggdabuh** [comment]
https://arkhamhorror.app/#/games/84d11721-4d5d-4828-ac8c-f8e8604bc962

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/ed7b5e25-078c-4fba-b28c-cfac2406a408)

Gloria does not have the compass so she needs 3 resources. If I give her the necessary resources,. the explore option becomes available again.

![Image](https://github.com/user-attachments/assets/0cd53be0-49e7-4319-b0e3-1066ed3f97b1)

Going to close this one, but if you run into other troubles, don't hesitate to let me know!
