### ISSUE TITLE
Fingerprint kit - unable to use action

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#229]
Game id: d1613880-cd27-4696-8417-f553b6fc6d3b

Joe has the Fingerprint Kit equipped with 3 supplies but cannot activate/exhaust it to investigate the location.

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/ad3b24e9-1212-49d6-89d7-bb35a4d11712)

That location cannot be investigated due to the Locked Door.
