### ISSUE TITLE
Can't Proceed when Hunting Horror is in the Void in Miskatonic Museum

### ISSUE THREAD

**Issue by Jekkum** [halogenandtoast/ArkhamHorror#234]
**Provide a Game ID**
02dba79d-6e91-4e21-8ed9-0fc3423e8985

**Describe the bug**
When playing the Miskatonic Museum scenario and Hunting Horror is in the void at the beginning of the Enemy Phase, the game state locks up and is unable to move forward. I need to click on Hunting Horror and activate its Forced ability, however the popup to activate the ability is outside of the game window so the "Forced" button cannot be clicked.

**Comment by morg16** [comment]
Haha, I encountered this issue as well - for me, I found there was maybe a 1-pixel wide area below the game bar where the forced button could be clicked? That was my workaround for the time being.
