### ISSUE TITLE
I can't log in or register

### ISSUE THREAD

**Issue by HyperboreanSorcerer** [halogenandtoast/ArkhamHorror#258]
**Provide a Game ID**
The id is the series of numbers and letters in the url for the game. After filling the bug please do not delete the game.

**Describe the bug**
A clear and concise description of what the bug is. Feel free to add screenshots if it will help explain.

Well, the title is self describing. Suddenly, when I went to play the game, I had been logged out and couldn't either log in (it's says the password is wrong) or even create a new account.

**Comment by fspoettel** [comment]
The login service was down for a brief moment, it should work now (at least it does for me).

**Comment by halogenandtoast** [comment]
Yup should be resolved now!
