### ISSUE TITLE
Dowsing Rod not available to use after exhausting

### ISSUE THREAD

**Issue by HyperboreanSorcerer** [halogenandtoast/ArkhamHorror#261]
**Provide a Game ID**
73a685a0-ac2d-4ea8-95f4-0801a4189868

**Describe the bug**
So, according to the rules after exhausting Dowsing Rod for its effect, you can still actually use its action ability (you can't choose the first option again, since you need to exhaust it, but the second option is still available. The same thing happens for Hallowed Chalice and Ceremonial Sickle).

**Comment by HyperboreanSorcerer** [comment]
Okay, update: I was using Dowsing Rod at Orne Library, which requires 2 actions to investigate. Maybe that's why I couldn't re-use the Rod. My bad.

**Comment by halogenandtoast** [comment]
No worries! The best bugs are the ones I don't have to fix!
