### ISSUE TITLE
Suddenly kicked out game and logged back in

### ISSUE THREAD

**Issue by thecatkeith** [halogenandtoast/ArkhamHorror#262]
Game ID: 645ed282-6798-408c-b8bd-73f13959dd7d/ 

Game suddenly becomes unsynced, and when try to log back in all registerred login credentials failed for all 4 players.

**Comment by thecatkeith** [comment]
Sorry title meant can't log back in

**Comment by halogenandtoast** [comment]
Should be fixed, there were some issues with the server.
