### ISSUE TITLE
Out of sync when trying to move (that costs 2 actions)

### ISSUE THREAD

**Issue by morvael** [halogenandtoast/ArkhamHorror#265]
546bc623-88ee-40e0-b67a-a6db9da94d7f

![image](https://github.com/user-attachments/assets/7125f623-f028-4fe0-b1e0-55e1377200c7)
Have 3 actions.
Frozen in Fear says move will cost 2 actions.
Out of sync when I try to move to Notre-Dame.

**Comment by halogenandtoast** [comment]
So this is actually the result of something else I fixed, but this game not having up to date as a result. Currently each unrevealed location is saying it takes too many actions. I can't really fix this directly, but not to leave you hanging here I added a debug menu option to locations that says `Reset` so if you enable debug (either by pressing `D` or using the menu bar) and then hit debug for Notre Dame, you can reset it and then move in normally. You will likely need to do this for all unrevealed locations.

After that you should be golden and it won't affect further scenarios. This feature isn't live yet though, but once I mark this issue done you should be set to try it out.

**Comment by halogenandtoast** [comment]
Deployed, you should be able to use the reset option now
