### ISSUE TITLE
Not able to use Aquinnah power after first use

### ISSUE THREAD

**Issue by ZelteHonor** [halogenandtoast/ArkhamHorror#268]
**Provide a Game ID**
b99a8134-8f11-4cba-970f-1035db588367

**Describe the bug**
I was not able to use Aquinnah power to block the attack of the boss and it defeated me when I was trying to play around with the debug menu to fix that.

**Comment by halogenandtoast** [comment]
I can't step the game back, likely because something has changed since the game was created.

Can you describe the situation a bit more. Was is Aquinnah 1 or 3? Was she exhausted? What was the other enemy at the location with the boss? Any other things that would help me recreate this issue?

**Comment by ZelteHonor** [comment]
It was Aquinnah (3). I don't remember her exhausting (like going to the side) when I did use her ability before. Could it be that she was exhausted but not showed as such? Its very possible I was not able to block because she was exhausted.

**Comment by halogenandtoast** [comment]
Okay going to close this. If you run into the issue again, either reopen it or create a new issue.
