### ISSUE TITLE
Arrogance Returning to Hand on Failed Test

### ISSUE THREAD

**Issue by Ruduen** [halogenandtoast/ArkhamHorror#269]
**Provide a Game ID**
26645c44-a300-4d9e-8368-68a16f721a5d

**Describe the bug**
Arrogance is still returning to hand after a failed check, even though it should move into the trash afterward.

**Comment by halogenandtoast** [comment]
It seems like it's getting discarded correctly, but it looks like the next time you pass one it goes back to your hand. I have a solution for this going live soon.
