### ISSUE TITLE
Trying to use the last resources on Schoffner's Catalogue cause the game to go out of sync

### ISSUE THREAD

**Issue by ZelteHonor** [halogenandtoast/ArkhamHorror#277]
**Provide a Game ID**
98a425c6-3fb2-4472-92aa-48e1ce4a8e38

**Describe the bug**
Trying to use the last resources on Schoffner's Catalogue cause the game to go out of sync

**Comment by halogenandtoast** [comment]
I think this might have been fixed by something else I did earlier. It at least doesn't seem to happen to me anymore.
