### ISSUE TITLE
After drawing Paranoia weakness at the end of the round the investigator should have a resource

### ISSUE THREAD

**Issue by kortatu** [halogenandtoast/ArkhamHorror#282]
**Provide a Game ID**
46a7c5ff-202e-4125-93a6-7bc1107c4f31

**Describe the bug**
It was clarify by FFG that the card draw is before the resource at the end of the round. Paranoia will discard all resources from the investigator pool but then they will gain a resource, ending the round with one resource instead of 0.
<img width="619" alt="Captura de pantalla 2024-08-18 a las 20 54 27" src="https://github.com/user-attachments/assets/1fe6bcd2-e93e-406c-87db-099212993fa0">

**Comment by halogenandtoast** [comment]
> It was clarify by FFG that the card draw is before the resource at the end of the round.

I didn't know about this! Where did they clarify it?

**Comment by kortatu** [comment]
I saw that in some discord. Now is in Arkham Cards FAQ at least. 
![Screenshot_2024-08-19-11-24-18-21_61b7c3dffdd71c6a07bb416b85eae11f](https://github.com/user-attachments/assets/eae3cf1c-6bd7-4627-a119-fc9d498d09b9)
