### ISSUE TITLE
Grim Memoir not drawing weakness

### ISSUE THREAD

**Issue by HyperboreanSorcerer** [halogenandtoast/ArkhamHorror#284]
**Provide a Game ID*
faaa0b42-3158-4b95-bb52-b50a93ccbeac)
**Describe the bug**
When I use Grim Memoir with Daisy to draw a card (that happens to be Silver Twilight Acolyte) instead of drawing the enemy and proceeding as normal, the game just goes back to the skill test result where I need to choose to draw or not. If I try to draw again, the same error occurs and I'm back to the skill test. The only way to proceed as normal is choosing not to draw the card.

**Comment by halogenandtoast** [comment]
I think this game got deleted so I'll need to recreate the issue myself.

**Comment by halogenandtoast** [comment]
I chose to draw a card and it worked correctly for me. Without the original game I won't be able to tell what was happening here. I'm going to close this for now, but if you still have the game and I missed it somehow or you run into the issue again, please reopen this.
