### ISSUE TITLE
Attempting to play 'Glory' results in sync issue

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#285]
**Provide a Game ID**
https://arkhamhorror.app/#/games/462be556-4d8e-4d8b-a0a6-248fc82d043b

**Describe the bug**
After defeating rats, trying to play 'Glory' results in an out-of-sync issue and the game returns to the state before playing the card.

**Comment by halogenandtoast** [comment]
I believe this is fixed now.
