### ISSUE TITLE
Finn Edwards - Elder Sign

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#295]
046fa79e-7733-4e2b-9450-bfdb98eac93e

This one is weird, it worked once previously in the scenario but this time didn't. I had Magnifying Glass on the table - UI shows correctly that my intelect is 5, I drew Elder-Sign and it didn't update my skill value (+1) so the ability didn't kick in to discover additional clue.

[arkham-debug(1).json](https://github.com/user-attachments/files/16657911/arkham-debug.1.json)

**Comment by halogenandtoast** [comment]
@sedlakm-jamf Finn's eldersign is +1 for each exhausted enemy. I don't see any exhausted enemies in this game so you are getting +0 here?

**Comment by sedlakm-jamf** [comment]
You are very right! thanks
