### ISSUE TITLE
Aloof not set on new criminal enemies in "The House Always Wins" 

### ISSUE THREAD

**Issue by AUscarface79** [halogenandtoast/ArkhamHorror#297]
**Provide a Game ID**
dccf72e5-a8b9-4c8d-90d6-3f1141a7910e

**Describe the bug**
Criminal enemies drawn from the encounter set spawn engaged with you during Agenda 1a of "The House Always Wins" instead of being "Aloof".

**Comment by halogenandtoast** [comment]
I think this might be fixed now with the release of some other change. I tried your file and they went to the location correctly now.
