### ISSUE TITLE
Pushed into the Beyond's effect triggers when a copy of the chosen card was already in the discard pile

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#298]
**Provide a Game ID**
1d20ac4d-a3b3-4204-9d25-faa6652169a8
**Describe the bug**
After playing "Pushed into the Beyond" I chose to discard Sefina's Ritual Candles (because I had already discarded my other Ritual Candles during my mulligan) - this shouldn't have caused the effect to take 2 horror to trigger, but it did (I guess because it found the other ritual candles on the discard pile and thought it had been discarded during the drawing of the 3 cards as indicated by the treachery)

**Comment by halogenandtoast** [comment]
Pushed into the Beyond shuffles the card you choose into your deck before discarding. So in this case I think the candles you chose got shuffled in, and then were discarded. I double checked the code and it only looks at the discarded cards.
