### ISSUE TITLE
Midnight Masks - Encounter deck - too many cards

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#299]
046fa79e-7733-4e2b-9450-bfdb98eac93e

This does not look right.
https://imgur.com/a/O65zmzX

There are too many Cultists card in the encounter deck on setup.

**Comment by halogenandtoast** [comment]
3 of those are in your discard.

**Comment by halogenandtoast** [comment]
It will no longer show the cards in the discard in the next deploy
