### ISSUE TITLE
Game reports "out of sync" when moving to new location

### ISSUE THREAD

**Issue by Felixderh4se** [halogenandtoast/ArkhamHorror#302]
**Provide a Game ID**
c4359e28-6157-4d0a-802a-830fe1f95bd4

**Describe the bug**
When I try to move Agnes to Orne library the game reports that it is out of sync. Other locations seem to be fine.

**Comment by halogenandtoast** [comment]
If you started this game a bit ago there was a change on locations that results in some oddities around unrevealed location. HOWEVER, you can fix this by loading the debug menu either press `D` or use the Debug menu bar item. Then hit the debug button on that location and then hit `Reset`, this should fix it.
