### ISSUE TITLE
Follow-up issue with Waking Nightmare Start

### ISSUE THREAD

**Issue by lariatstoboy** [halogenandtoast/ArkhamHorror#303]
**Provide a Game ID**
74af8532-439b-4a42-ac83-a256acc00057

**Describe the bug**
Follow up to the issue here: https://github.com/halogenandtoast/ArkhamHorror/issues/287

Was able to progress through the intro and mulligan, up to the point where I started my first turn, but I got a looping sync issue again when picking my first-turn investigator.

I've been posting a lot of these, so I hope you're ok with that. The project is super cool and I keep wanting to test the system to see what works and doesn't, and how far you can get on certain missions.

**Comment by halogenandtoast** [comment]
No these are great, I am sorry for all the troubles on these. Basically it keeps holding on to data related to older games, so I have to add checks to remove them, I think this should be the last time this happens ha ha ha
