### ISSUE TITLE
Drawn to the Flame breaks the game and can't continue

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#304]
c7190b36-5bf8-45c3-ac11-9db7b97f53ff

Can't continue. When I play Drawn to the Flame and do the test it breaks the game. When I then press End Turn it says: Your game is out of sync and can't progress.

**Comment by sedlakm-jamf** [comment]
Ok, tried different scenario and it seem like if the last card in my hand is Watcher From Another Dimension it breaks the game.

**Comment by halogenandtoast** [comment]
Did you delete the previous game? I get a 404 when I try to access it.

**Comment by halogenandtoast** [comment]
If it's a Watcher issue it will probably work once the next deploy goes out. I just tried locally on my machine and didn't hit the issue when it was the last card in my hand.

**Comment by sedlakm-jamf** [comment]
this should work: 
#/games/c7190b36-5bf8-45c3-ac11-9db7b97f53ff
