### ISSUE TITLE
Fight Action from False Surrender does not use Agility

### ISSUE THREAD

**Issue by lariatstoboy** [halogenandtoast/ArkhamHorror#305]
**Provide a Game ID**
65dc9a45-fb7b-4fda-ba05-307e8d01ee87

**Describe the bug**
Played False Surrender and used its action to fight an enemy. It should use agility, but instead defaulted to Strength

**Comment by halogenandtoast** [comment]
Waiting on the deploy, but it should correctly use agility now.

Additionally I noticed the Don Lagorio card was showing the other side so I think I've fixed that too for all the cards in that scenario.
