### ISSUE TITLE
Move with engaged enemy did not trigger AoO

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#311]
Game-ID: 9e719822-fd93-4245-8b57-b99a657e17a3

Playing as Ursula, the move with an engaged enemy (Boa Constrictor) triggered Ursula's reaction ability (free investigate), but not the Attack of Opportunity from the enemy.

Game state is right after resolving the move+investigate (before end turn).

**Comment by grabben2** [comment]
Same thing in this game: 6af65bbe-ea66-4d40-91f7-4e6e30cd716e

**Comment by halogenandtoast** [comment]
I think Jake is keeping you safe here.

![Image](https://github.com/user-attachments/assets/f0aacaf4-ec90-4056-b223-31228c31c75c)



![Image](https://github.com/user-attachments/assets/a37dfda8-83e9-49f8-a9c6-922aedc5c910)

**Comment by grabben2** [comment]
Oops, my bad 😅 Need to start reading the cards properly.

**Comment by halogenandtoast** [comment]
I wouldn't worry about it. Happens to the best of us. At some point in the future this sorts of modifiers will be more visible in the app somehow. Haven't decided what I'm going to do though.
