### ISSUE TITLE
Hiking boots reaction doesnt work ont the last clue

### ISSUE THREAD

**Issue by Vexerd** [halogenandtoast/ArkhamHorror#315]
a68e7d6d-5b48-4c69-b88b-b4dec20b881b

Hiking boots reaction doesnt work ont the last clue

**Comment by halogenandtoast** [comment]
In your example you don't have a valid location to move to

> Move to a connecting location with at least 1 clue, or to a connecting unrevealed location.

Miskatonic Quad doesn't have any clues and Alchemy Labs is blocked.
