### ISSUE TITLE
Cat mask

### ISSUE THREAD

**Issue by Vexerd** [halogenandtoast/ArkhamHorror#316]
a68e7d6d-5b48-4c69-b88b-b4dec20b881b

Cat mask could be activated on EVERY test

**Comment by halogenandtoast** [comment]
While annoying, it can be activated on every test as increasing a stat (even if not relevant to the skill test) is changing the game state and there are sometimes reasons you'd want to do this. In the future I'll add a feature that allows you to "smart" disable these so they don't activate during skill tests you aren't using a relevant skill for but it needs both UI and development work still.
