### ISSUE TITLE
Can't commit Prepared for the Worst

### ISSUE THREAD

**Issue by morvael** [halogenandtoast/ArkhamHorror#317]
eb40df72-a08d-4d36-baa8-11c229f47199

Elusive can be committed but this not?
![image](https://github.com/user-attachments/assets/8b5a1cd4-258e-403a-9b8e-5eb960d01e2e)

**Comment by morvael** [comment]
![image](https://github.com/user-attachments/assets/4e3693a4-c54d-4615-b312-a80e5fd0de54)

**Comment by halogenandtoast** [comment]
AH yeah there are technically two fast player windows in the skill test, but at the moment they are difficult for me to display since I don't track those steps yet. In the future I'll extend this UI, but glad to know you could commit.

**Comment by morvael** [comment]
Ah right, that's what's missing - separate step boxes for player windows.
