### ISSUE TITLE
I can't load a debug export

### ISSUE THREAD

**Issue by HyperboreanSorcerer** [halogenandtoast/ArkhamHorror#321]
So, I'm trying to load a debug export, but nothing seems to happen.

**Comment by HyperboreanSorcerer** [comment]
Ok, I managed to do it with a different export this time.

**Comment by halogenandtoast** [comment]
Ah the debug exports are mainly for me to test with locally. Usually the file size is too big to send to the server. 

I should probably disable the UI on production, but out of curiosity what did you want to do with the export?

**Comment by halogenandtoast** [comment]
Going to close this since it's not a bug, but as mentioned above I'd be curious to know the usecase because I might be able to make a more reasonable export for other use cases.
