### ISSUE TITLE
Mind Over Matter doesn't change commit requirements

### ISSUE THREAD

**Issue by ChooJeremy** [halogenandtoast/ArkhamHorror#324]
**Provide a Game ID**
ce9cbe2e-380c-4232-90f6-8e11a3c7cfc1

**Describe the bug**
When using Mind over matter, the FAQ says:
When making a Combat or Agility skill test, you may make an Intellect test instead. If you do, apply only bonuses to your Intellect for this test, and ignore any bonuses to Combat or Agility. You can only commit cards with an Intellect or Wild icons to this test.

While this was active and using book instead of fist, I was unable to commit intellect cards (notice that Emergency Aid is not highlighted, while Guard Dog and Personal Training is)
![image](https://github.com/user-attachments/assets/5ce89564-9f55-4096-9795-e8cafa5d661e)

**Comment by halogenandtoast** [comment]
I believe this got fixed at some point between this issue being opened. Let me know if you still run into this issue.
