### ISSUE TITLE
Game Out of Sync when resolving Bought in Blood's Discard Ally in Hand effect

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#325]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6

**Describe the bug**
Trying to select the "discard ally from hand" effect on the Bought with Blood card causes the game to show the out of sync error.

**Comment by foodiemonster** [comment]
A bit more info: if you choose the other option, to discard an ally in play, the game can proceed normally. Of course if I do this I'd be doing something that I don't want and make my life in the scenario harder! Otherwise I'm stuck at Out of Sync and cannot progress the game further.

**Comment by halogenandtoast** [comment]
What scenario did you run into this issue. I am trying to undo back to when this happened.

On a clean attempt (my deck, my scenario), I wasn't able to recreate the issue.

**Comment by halogenandtoast** [comment]
Closing for now, if you hit this issue again, please feel free to reopen.
