### ISSUE TITLE
Hunting Horror not Spawned by Slithering Behind You

### ISSUE THREAD

**Issue by Jekkum** [halogenandtoast/ArkhamHorror#326]
**Provide a Game ID**
02dba79d-6e91-4e21-8ed9-0fc3423e8985

**Describe the bug**
When Hunting Horror is in the Void and the Slithering Behind You treachery was drawn, 1 doom was placed on it instead of spawning it. Very similar to another issue I encountered the other day, which was fixed: https://github.com/halogenandtoast/ArkhamHorror/issues/264.

This project is awesome by the way, thanks for doing all this and releasing it!

**Comment by foodiemonster** [comment]
I'm also seeing this same issue and I echo that this project is amazing!
Game ID: 515931bc-9645-4953-8d64-f5907c944db6
![image](https://github.com/user-attachments/assets/601ba295-da36-4c79-b969-ffbbc110bdf2)
