### ISSUE TITLE
574cdcc7-ba09-4794-b0fe-d196d93b1cdb   Vincent's "on the mends" is not being added to players hands after being healed and hawk eye folding camera is not adding evidence automatically not counting towards skill tests.

### ISSUE THREAD

**Issue by Abost28** [halogenandtoast/ArkhamHorror#327]
**Provide a Game ID**
The id is the series of numbers and letters in the url for the game. After filling the bug please do not delete the game.

**Describe the bug**
A clear and concise description of what the bug is. Feel free to add screenshots if it will help explain.

**Comment by halogenandtoast** [comment]
Do you know which cards you were using for healing?

**Comment by halogenandtoast** [comment]
The game was deleted so I am having some difficulties recreating the issue. I am curious if you know which healing cards you used. I think the camera is fixed now, the token type was incorrect on it before.

**Comment by Abost28** [comment]
> Do you know which cards you were using for healing?

Bandages and painkillers

**Comment by Abost28** [comment]
> The game was deleted so I am having some difficulties recreating the issue. I am curious if you know which healing cards you used. I think the camera is fixed now, the token type was incorrect on it before.

I haven't played it in a while, but I know the camera now counts the stat boosts, but it wasn't automatically adding resources when another character (at the same location) discovered the last clue.

**Comment by Abost28** [comment]
Attachment available until Sep 22, 2024
If it helps here is the debug file 
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAdxghDU-S1OCaxNvvI9uueWTHpawAWfwrb-YmCFPXIZ5i9Nd9SKI7RUn%2F%24%7Bf%7D%3Fo%3DAv-vHdae91PSyqVPxhYr4ufjqrFfvKZAXE8_bdajN9iW%26v%3D1%26x%3D3%26a%3DCAog81h3m8yLZgeYL9B5pNq9o37tXJUiAhvJWjeNopFvdkoSeBDW1Kf5lzIY1uSizaEyIgEAKgkC6AMA_z-LNn1SBJMelrBaBIjtFSdqJhLG3zguQ_KUP0aV4-CV580-zYpnrtRW1DRCKS_z1t3D80Y4sZymciY1XTQmR4IqRAG_BiQbMYsVel_UxWipR3a5C6qLcDJF5GwJV2SzzA%26e%3D1727007339%26fl%3D%26r%3DC51AF212-38B0-4E39-833D-7A5B563BEA8D-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D3A0AA211-61EE-448A-A18B-EA730DDB19CB%26p%3D162%26s%3DoD8w9lgn4KpgBZovW9gGquODEzU&uk=0VM7y7DABVi8JDKsgfQhkw&f=arkham-debug%20%283%29.json&sz=40579573>arkham-debug (3).json
40.6 MB

**Comment by halogenandtoast** [comment]
I think I just fixed the camera, as far as the on the mends go, for some reason they are no longer in your game, I am not sure why, I can't undo far back enough. But in my testing they seem to be working in new scenarios. So I'm going to close this for now, but if they aren't working by the next scenario, please let me know
