### ISSUE TITLE
Out of Sync Error when attempting to use Rite of Sanctification to reduce the cost of another investigator's card

### ISSUE THREAD

**Issue by Jekkum** [halogenandtoast/ArkhamHorror#334]
**Provide a Game ID**
52cc39a9-4a70-407c-83a7-8aad56bdd7df

**Describe the bug**
Sister Mary has Rite of Sanctification with 4 sealed bless tokens on it. Minh with 1 resource is attempting to play a Dark Horse, which she should be able to do by paying 1 resource, with Mary releasing a bless token, but instead I get an Out of Sync error. The same error occurs when attempting to play Mariner's Compass, which should also cost 1 w/Rite of Sanctification. Thanks!

**Comment by halogenandtoast** [comment]
I think this got fixed with another issue as it works for me now.
