### ISSUE TITLE
Ancient Covenant picture is broken

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#336]
**Provide a Game ID**
The id is the series of numbers and letters in the url for the game. After filling the bug please do not delete the game.
7a275f24-71f2-423b-b406-17c6fe79a63f
**Describe the bug**
A clear and concise description of what the bug is. Feel free to add screenshots if it will help explain.
The photo for Ancient Covenant is broken. It still works though.

**Comment by halogenandtoast** [comment]
In this case I had the taboo list image that gets applied to it incorrect. I fixed the code, but it would still be broken for your game so I added an extra image for the time being. It should be fixed now.
