### ISSUE TITLE
Hyperphysical Shotcaster in Telescanner form does not allow to get a clue from the investigator location

### ISSUE THREAD

**Issue by kortatu** [halogenandtoast/ArkhamHorror#340]
**Provide a Game ID**
0ea5ba4b-bf57-4f98-8e19-7edddece0bbc

**Describe the bug**
I'm investigating Back Alley with Yorick. There is one clue at the location. When I succeded, I didn't get any clue and there is still a clue on the Back Alley (there is no other location with clues). I understand by the text, that I can select my own location as "at any revealed location". There is also another weird thing. Even though I didn't get any clue (Yoirck 0 clues, Back Alley 1 clue). When I resign, suddenly 2 clues appear at the Back Alley.

**Comment by halogenandtoast** [comment]
I believe the other clue is coming from Dr. Francis Morgan. I believe clues on assets you control are considered controlled by you. I have a fix for not being able to get a clue from your location coming up.
