### ISSUE TITLE
Agenda deck not showing and preventing advance

### ISSUE THREAD

**Issue by DilirConfar** [halogenandtoast/ArkhamHorror#344]
b8c933d0-54c9-4ace-b8e3-31b9ae7fab8a

In miskatonic museum,
Also tested with beta/non beta branch, seems to affect other scenarios as well

**Comment by halogenandtoast** [comment]
That game no longer exists. Would you be able to get a game in the same state?

**Comment by DilirConfar** [comment]
444a04db-c35f-47c2-9686-3252afcf1096

There. Maybe it has something to do with the browser (firefox). I tested it on a different computer with edge, seemed to work fine there.

I'll test a bit more and get back to you

**Comment by halogenandtoast** [comment]
Closing for now. If you hit the issue again, please feel free to reopen the issue.
