### ISSUE TITLE
Can't play Unique Allies with on a Charisma slot if Mitch Brown is in play

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#348]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6

**Describe the bug**
The game won't allow me to play Leo de Luca if I have Charisma + Mitch Brown in play - Mitch Brown only allows for Non-Unique Allies in its extra slots, but Charisma doesn't have that restriction (and I only have 1 Ally slot used at that time with Mitch Himself).

**Comment by foodiemonster** [comment]
![image_2024-08-20_124915029](https://github.com/user-attachments/assets/9c8f2ff8-8121-4ccc-83c8-b55d4838a53c)

**Comment by halogenandtoast** [comment]
This took me too long to notice. You can't play Leo because Sefina already has a Leo in play

**Comment by foodiemonster** [comment]
Ooooh, of course. It's unique. Totally missed that.
