### ISSUE TITLE
Hunting Horror doesn't Hunt

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#356]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6

**Describe the bug**
Hunting Horror didn't Hunt after Sefina when during the Enemy phase, and I believe it should've since it was ready and has the Hunter attribute.

**Comment by halogenandtoast** [comment]
I think I have a fix for this, but it will be hard to see in your game. Basically it was being marked as defeated when it went to the void, but came back into play as defeated so it thinks it should not move. I've updated that but you won't see it until either it gets defeated again OR if you step back to the last time it got sent to the Void.

In the meantime if you want to simulate this, before you end your turn if you turn on debug, you can drag the enemy to your location manually.
