### ISSUE TITLE
Dragon Pole doesn't deal +1 damage with 2/3 Arcane Slots filled

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#362]
**Provide a Game ID**: 2d914add-debd-4998-a398-269a151f5e96

**Describe the bug**
Fighting a Ghoul Minion with Dragon Pole with 2x Brand of Cthugha in play, the attack only dealt 1 damage, necessitating another attack.

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/0078694a-b627-437a-b7c8-81f63543e36d)

This is why.

![Image](https://github.com/user-attachments/assets/624b6437-3766-476d-bdf4-e2d2a0c7c619)

**Comment by halogenandtoast** [comment]
I think the near distant future, I will display the relevant token effects in the UI, but that is a ways out currently.

**Comment by mniksa3** [comment]
In the meantime, perhaps I should work on reading the scenario reference more closely. Thanks for taking a look and sorry for the spam.

**Comment by halogenandtoast** [comment]
No worries, these sorts of things are bound to happen. The game has so many moving pieces and while the app does the right thing, it's not always obvious what it is doing. That was a hard thing to balance and something I'll need to go back card by card to adjust.
