### ISSUE TITLE
Secrets replenished by Enraptured via Written in the Stars onto Scroll of Secrets (0) caused 4x Recall the Future in hand

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#363]
**Provide a Game ID**: 2d914add-debd-4998-a398-269a151f5e96

**Bug**: Sorry, title is a mouthful. I activated Scroll of Secrets in the fast window and pulled Recall the Future from the bottom of my deck into my hand. This left Scroll of Secrets with 2 secrets on it. Later, I discarded Enraptured via Written in the Stars and then investigated my location twice, succeeding both times. In both cases, I placed a secret onto Scroll of Secrets, ending my turn with 4 secrets on it. The next two times I activated Scroll of Secrets, even with 2x Recall the Future in my hand, I pulled an additional Recall the Future from the bottom of my deck into my hand, resulting in 4 total copies of Recall the Future. I'm unsure if the "phantom" copies of Recall the Future could be played/committed or if I'd discard them with my hand size at >8. 

![Screenshot 2024-08-20 190833](https://github.com/user-attachments/assets/8ea9a7c2-d0d0-471d-9f3a-2bb77953161c)

**Comment by KooBonchan** [comment]
Error from scroll of secret:
if you choose to draw it, the card remains at the bottom and the copy of it is drawn.
if you choose to put it at the bottom, the card puts its copy at the bottom.
else, work as intended.

Same problem with scroll of secret(seeker 3)

![Image](https://github.com/user-attachments/assets/417d866e-1e27-46a4-9f47-1f0bf2896acf)
before use
![Image](https://github.com/user-attachments/assets/59d15f7f-350b-464a-91aa-6f2ea291f918)
after use
