### ISSUE TITLE
Mitch Brown + Charisma gives you an ungodly amount of Ally slots

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#365]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6

**Describe the bug**
I'm running a Leo deck with Charisma and Mitch Brown is in play, and I've realized I have way too many allies in play - By my estimations I should be able to have a maximum of 4 allies total (1 extra from Charisma and 2 non-uniques from Mitch). At the moment I have 2 beat cops, 1 guard dog, 1 Venturer and Mitch Brown (and one Story ally that doesn't take a slot). I see I have more open slots available.

**Comment by foodiemonster** [comment]
Possibly related to bug #348

**Comment by halogenandtoast** [comment]
Not related, but this is a fun one. Basically I wasn't clearing the slots out between scenarios so those keep carrying over. I'll put a fix in and the extra slots will disappear after you begin a new scenario. That is, after I mark this as deployed.

**Comment by foodiemonster** [comment]
I'm not sure where to say this but I am super impressed by what you are doing with this project. Why don't you set up a Patreon or something so we can pitch in and make it worth your time and we can help make sure this keeps being developed?

**Comment by halogenandtoast** [comment]
> I'm not sure where to say this but I am super impressed by what you are doing with this project. Why don't you set up a Patreon or something so we can pitch in and make it worth your time and we can help make sure this keeps being developed?

I don't want to accept any form of payment due to licensing issues. If I ever get permission I would, but I don't think I will.

On this issue though, I realized I was wrong and you do indeed just get a ton of slots by playing Mitch so I still need to find a fix.

**Comment by foodiemonster** [comment]
Fair enough! Here's to hoping you'll keep working on this for then, it's absolutely amazing and really convenient. The TTS mod is great but it's way less convenient because you need that other game and it requires connecting to dropbox servers that get blocked in a lot of networks. This just works and is awesome.
