### ISSUE TITLE
"Ashcan" Pete and Duke not working correctly when un-exhaust multiple time

### ISSUE THREAD

**Issue by Dreadnote** [halogenandtoast/ArkhamHorror#366]
Game ID: 55498f17-ce41-4b1f-8cb6-958ce8642b5d

Was playing Ashcan and using his ability do discard cards to un-exhaust Duke. But when I get to un-exhaust him due Eldritch Sign effect, used him to investigate and then un-exhaust via discard ability I couldn't use Duke to investigate. He is ready, but not interactable.

**Comment by halogenandtoast** [comment]
The issue here is Frozen in Fear which should NOT be affecting this ability. I've made a fix, and tried to ensure the rest of the Duke kit still works correctly so here's hoping.
