### ISSUE TITLE
Your game is out of sync, trying to reconnect...

### ISSUE THREAD

**Issue by Man-Myth-Legend** [halogenandtoast/ArkhamHorror#372]
**Provide a Game ID**
4f96facf-4178-476b-a336-fdb448392a9f

**Describe the bug**
Pressing 'Continue' after reading the story intro to The Essex Country Express results in the above message.

**Comment by camipco** [comment]
Also having this issue, on House Always Wins. Tried debug to remove specific card issue started on and undoing a few steps, saving and restarting browser, issue still there.
