### ISSUE TITLE
Arcane Studies Triggering from other Investigator

### ISSUE THREAD

**Issue by wschlundt** [halogenandtoast/ArkhamHorror#375]
I think the card Arcane Studies is triggering incorrectly. It was deployed by Agnes, and should only target her, but I believe in two handed, it's being recognized for Carolyn as well.

https://arkhamhorror.app/#/games/8fb340e9-1c17-4615-8702-cbcbe272fded

[image](https://github.com/user-attachments/assets/5d08b4a0-0b1c-46be-aa52-e5b4fa7c89ed)

No real issue to just ignore the triggering, but thought you would want to know.

**Comment by halogenandtoast** [comment]
Actually this is allowed in the rules, increasing your stat is a game state change, even on another player's turn. I plan to make it something you can toggle.
