### ISSUE TITLE
Card previews have the wrong aspect ratio

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#378]
First of all, many thanks for this app.
I was used to help debugging it by deploying it locally until it exceeded the RAM on my computer.
Lots of progress, even before than I remembered. And now I can play in my mother language (will be game changing with the most recent expansions with a lot of text to read and make it much more enjoyable).

**Provide a Game ID**

I'm running this game: https://arkhamhorror.app/#/games/8d512b1a-4e0e-47ca-946a-8eafdb89e559

**Describe the bug**

I noticed that any card preview in the game has the wrong proportion (see pictures).
Maybe it's a mistake in the HTML style, it looks like the the longer side is 1 1/4 longer that it should be.

<img width="2032" alt="Screenshot 2024-08-21 at 21 53 24" src="https://github.com/user-attachments/assets/95edc3d9-950a-4799-873f-38435e3c6567">
<img width="2032" alt="Screenshot 2024-08-21 at 21 53 19" src="https://github.com/user-attachments/assets/ec686596-b095-4de7-aeb5-d7f2a6fc2327">

Many thanks in advance and for the app in general!

**Comment by halogenandtoast** [comment]
What browser, version, os are you using?

**Comment by stefano-bragaglia** [comment]
macOS Montery (v12.7.6)
Safari v17.6 (17618.3.11.11.7, 17618)

By the way, I've just noticed the issue disappears on Chrome Version 127.0.6533.120 (Official Build) (x86_64).
