### ISSUE TITLE
Shed a light does not discover third clue if no other locations have clues

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#381]
9b959b4e-4b4a-42d3-b809-8e430dbafa49 - though any game should be fine

Have encountered a few times, but this particular case is in the study, play and use old key ring, so shroud is 0, play shed a light and auto succeed. Darrell has two clues instead of 3. Evidently the 'from any location' is not triggering correctly, as that should apply to the investigated location.

**Comment by morg16** [comment]
Wow, I could have sworn that Shed a Light said "any other location", so I checked. And you're right! No wonder they taboo'd it.
