### ISSUE TITLE
Investigator mini cards disappeared

### ISSUE THREAD

**Issue by ghdevo** [halogenandtoast/ArkhamHorror#383]
**Provide a Game ID**
c7e3b45c-2a97-479a-89d0-60864f6662a6

**Describe the bug**
After successfully parleying with Lita Chantler, the investigator mini cards disappeared from the play area.

**Comment by halogenandtoast** [comment]
I think this should be fixed now. It was sadly a display bug I introduced.

**Comment by ghdevo** [comment]
Confirmed, they are back.  Thanks!
