### ISSUE TITLE
Steadfast - broken UI

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#385]
da28435b-b0f3-444c-8a82-bd770c6d6841

The UI for skill cards with a dynamic number of icons based on some conditions has broken UI most of the time. 
I mean the skill value.

<img width="673" alt="image" src="https://github.com/user-attachments/assets/6bd2efc8-efe0-4a0e-ba7e-ae75c93c141c">

**Comment by halogenandtoast** [comment]
I might manually go through and check every skill, but please create issues as you come across other skill cards.
