### ISSUE TITLE
Curtain Call - Act 3

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#387]
da28435b-b0f3-444c-8a82-bd770c6d6841

The Man In the Pallid Mask UI shows he has 3dmg on him from previous Act.

**Comment by sedlakm-jamf** [comment]
also when I attack him he should get 1dmg , instead he took 4th damage and dies. This first scenario is severely broken to be played.

**Comment by halogenandtoast** [comment]
@sedlakm-jamf in my defense here, The Man in the Pallid Mask never leaves play, so no tokens would be removed from him, technically with the Rules as Written he'd move and then immediately die again. However, the rules as intended are likely that all tokens are removed. At the moment I'll add some code to heal him, but if damage goes away it's likely I should get rid of all tokens and attachments.

> If a card leaves play, the following consequences occur simultaneously with the card leaving play:
>
> All tokens on the card are returned to the token pool.
> All attachments on the card are discarded.
> All lasting effects and/or delayed effects affecting the card while it was in play expire for that card.

I'll revisit this later, but for now the damage aspect should be resolved (for all Act 2s)
