### ISSUE TITLE
Can't trigger Guard Dog(2) reaction ability after Free Trigger ability resolves

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#389]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6

**Describe the bug**
When Guard Dog (2) was attacked as the result of its Free Trigger ability to engage the Aloof Whippoorwill, I wasn't given a chance to trigger the Guard Dog's reaction ability to kill it. Pretty sure this is because the card is exhausted, but I don't think the card being exhausted would prevent it from triggering the Reaction ability.

**Comment by halogenandtoast** [comment]
Turns out it would not respond to horror, only damage. fix incoming.
