### ISSUE TITLE
UI button is hard to press

### ISSUE THREAD

**Issue by Man-Myth-Legend** [halogenandtoast/ArkhamHorror#390]
**Provide a Game ID**
Not relevant

**Describe the bug**
When two enemies are in the same location, and the second enemy has a unique action tied to it, it is very hard to press as the UI keeps moving around.

https://github.com/user-attachments/assets/68a4eb21-6e5a-4298-99d2-65f1ab460baa

**Comment by halogenandtoast** [comment]
I think with some of the UI changes I've made it isn't as difficult as it was, but if you are still having the issue, let me know about which browser you are using.
