### ISSUE TITLE
Translucent Skill Test Window

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#393]
**Describe the solution you'd like**
If you give the skill test window a slight transparency when game objects trigger behind the window, you won’t have to move it to a corner in order to see it. (Not to mention that you can’t even move the window on Mobile) Now this could end up causing more problems than it solves so this is just a potential solution.

**Comment by halogenandtoast** [comment]
I've made it translucent again, and added a way to minimize it.
