### ISSUE TITLE
Can't progress Objective for Forgotten Age

### ISSUE THREAD

**Issue by JesterJayJoker** [halogenandtoast/ArkhamHorror#394]
aa2a1cff-c234-4e91-8159-4972bffcbd18

I'm trying to advance the Act on Guardian's Inquiry, but I can't select Objective.

**Comment by grabben2** [comment]
Same issue for me.
Same scenario, different act ("At the exhibit"), 

gameid: 242db258-66b9-4b0e-922b-f19144ffd260
