### ISSUE TITLE
Hoods (Rita's weakness) attacks when another enemy is evaded

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#400]
**Provide a Game ID**
a02aefb2-3c86-4932-8d69-853aea239c82

**Describe the bug**
Evading another enemy while engaged with "Hoods" triggers Hoods' forced attack. (Should only activate after Hoods are evaded)

**Comment by alhepal** [comment]
I saw this too.  Hoods was at another location to me, and it still attacked me when I evaded another enemy.
3ba9fcd8-f623-432f-8500-ebd3ee7bfa8f
