### ISSUE TITLE
Evading O'Bannions Thug doesn't allow me to play "I'll Take That!"

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#401]
**Provide a Game ID**
98c1db27-c11e-42e5-b3b6-9fe36d9d18d4

**Describe the bug**
Should be able to play "I'll Take That" after evading "Humanoid" enemy. The Thug's trait is "Human" but that has been errata'd to be the same as Humanoid.

**Comment by halogenandtoast** [comment]
I'll take that was broken because it wasn't calculating the reduction correctly. Fix incoming.

**Comment by grabben2** [comment]
Still doesn't work for me in this game, even after clearing the cache and undoing to a state before the Evade was initiated.

**Comment by halogenandtoast** [comment]
I believe in your game you had 0 resources and were only passing by 2. The cost is the only thing you could play so you needed to pass by 3 or have 1 more resource. Sent from my iPhoneOn Sep 3, 2024, at 4:48, grabben2 ***@***.***> wrote:﻿
Still doesn't work for me in this game, even after clearing the cache and undoing to a state before the Evade was initiated.

**Comment by grabben2** [comment]
You're absolutely right, completely missed that, thanks :-)

**Comment by halogenandtoast** [comment]
No worries, there was still a bug here so I'm glad you called it out!
