### ISSUE TITLE
Out of Sync starting Carcosa with Carolyn and Sefina

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#407]
**Provide a Game ID**
b2ef317e-2bfd-4046-a7c6-589f311ef925
a9ea9645-efa6-43ea-9105-d9c37d44460a

**Describe the bug**
Out of sync when starting Path to Carcosa with Carolyn and Sefina
Can start other scenarios with them fine.
Can start Carcosa with other investigators fine.

**Comment by halogenandtoast** [comment]
This was a weird issue with how promo investigators work. I think I have a solution for it. Which will go out in the next deploy.
