### ISSUE TITLE
Zoomed preview of customized cards too small

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#408]
**Provide a Game ID**
Any game

**Describe the bug**
The hover preview of the customized cards are very small, barely readable on small screen (laptop).
It's the same in both Safari and Chrome.

It's great that the customized card sheet appears beside it but it would be great if it was zoomed the same size as other cards.
<img width="405" alt="small preview customized" src="https://github.com/user-attachments/assets/60e14c5c-d6da-43a9-9334-db1356d8e707">

**Comment by halogenandtoast** [comment]
This should be fixed. There was an issue with the overlay container's width being constrained for both images.

**Comment by grabben2** [comment]
@halogenandtoast Is it fixed but not deployed? I still get the issue with new games.

Example screenshots, regular card size compared with customized card size
Regular: 
<img width="405" alt="regular" src="https://github.com/user-attachments/assets/680ef7af-dbde-4808-8b54-3f4da2c00bb6">

Customized: 
<img width="405" alt="customized" src="https://github.com/user-attachments/assets/a17c32ba-f3f4-4e45-8813-1f309a091eae">

**Comment by halogenandtoast** [comment]
It should be live. I've tested with Chrome, Firefox, and Safari. Maybe try a hard refresh? If you are still having issues can you confirm you OS and browser version?

**Comment by halogenandtoast** [comment]
I also, for the sake of posterity, checked against the card Grizzled specifically just in case that card was the culprit, but it's rendering correctly for me.

**Comment by grabben2** [comment]
Yep, clearing the cache did it, thanks. I'll make it a habit from now on before posting a bug :-)

**Comment by halogenandtoast** [comment]
No worries. Glad it's working. I did notice that there is a slight issue when some cards get attached, but I have a fix for that on the way too.
