### ISSUE TITLE
Friends in Low Places doesn't seem to work

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#410]
**Provide a Game ID**
e058db67-b78b-4b72-a31d-7844554dc291

**Describe the bug**
Playing "Friends in Low Places" and nothing happens (no deck search)

**Comment by halogenandtoast** [comment]
There was an issue where if no cards were found it would not display correctly. This should be fixed now, but if you are still running into the issue please feel free to reopen the issue.
