### ISSUE TITLE
Jacqueline Fine's Ability with Voice of Ra - cancel from all tokens?

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#413]
**Provide a Game ID**
112d84f5-7eb0-4dbc-b127-5034e0702d7b

**Describe the bug**
Jacqueline Fine's ability states "When an investigator at your location would reveal any number of chaos tokens: Reveal 2 additional tokens. Of the revealed tokens, choose and cancel 2 non-autofail tokens, or 1 autofail token."
When playing Voice of Ra, this implies that 5 total tokens should be revealed, and any 2 non-autofail tokens from that set of 5 can be cancelled. As it's currently implemented, it only allows the player to choose from three tokens to cancel (the other two are not shown yet while choosing).
If my interpretation on the ruling here is wrong, I wouldn't be surprised, either.

**Comment by halogenandtoast** [comment]
I think you are correct. This is actually going to be an extremely tough one to solve because the chaos bag drawing code is well.... chaos.

**Comment by halogenandtoast** [comment]
Okay I think I have a sort of fix here. I know Jacqueline's ability will work for basic token draws as well as voice of ra, but there might be other cases where it does not work correctly. If you come across any of these, please let me know.
