### ISSUE TITLE
Bewitching did not trigger when taking an action to Engage during the Investigation phase

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#419]
**Game ID**: e3594d12-5b87-4f6a-bf1b-3275f2483ca2

**Bug**: Bewitching behaves correctly and triggers if an enemy engages an investigator (in this case Alessandra Zorzi) during the draw encounter cards step of the Mythos phase or after ready/hunter movement during the Enemy phase, but did not trigger when I manually took an action to engage the enemy off of another investigator.

**Comment by halogenandtoast** [comment]
I think this was fixed with [#392](https://github.com/halogenandtoast/ArkhamHorror/issues/392)
