### ISSUE TITLE
Unable to play any cards from my hand

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#421]
**Provide a Game ID**
515931bc-9645-4953-8d64-f5907c944db6
**Describe the bug**
Literally that - started the next step of my campaign and my characters cannot play any cards from their hands. I can draw, get resources, but cannot play cards at all.

**Comment by halogenandtoast** [comment]
Should be resolved, let me know if you still have the issue. I deployed some bad code, but fixed it (mostly still an issue I am hunting down).

**Comment by foodiemonster** [comment]
Yup, its solved now. Thanks!
