### ISSUE TITLE
Darkened Hall is stuck on it's forced action

### ISSUE THREAD

**Issue by thomill** [halogenandtoast/ArkhamHorror#422]
**Provide a Game ID**
f4d88681-b765-49e9-8d1a-bb21b8ede06d

**Describe the bug**
In The House Always Wins, after moving into the Darkened Hall location and setting the 3 Back Hall Doorway locations into play, the game is still stuck prompting to use the Darkened Hall's forced action to set the 3 locations into play.
![image](https://github.com/user-attachments/assets/ac2163de-3bec-44d8-88a0-b1a300ef39ee)

**Comment by thomill** [comment]
I used debug to check that the VIP Area was put into play. After revealing that location through debug, it stopped prompting to use the forced action on Darkened Hall and allowed me to continue.

![image](https://github.com/user-attachments/assets/af5c2195-96e9-457c-8050-28a413729b03)

**Comment by halogenandtoast** [comment]
There might have been an issue here were in multi player games forced actions would trigger multiple times. I think this should be resolved now.
