### ISSUE TITLE
Acolyte forced ability triggers twice

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#423]
**Provide a Game ID**
The id is the series of numbers and letters in the url for the game. After filling the bug please do not delete the game.
73697035-7e46-4a9d-92b3-18ca6f91c63c
**Describe the bug**
A clear and concise description of what the bug is. Feel free to add screenshots if it will help explain.
The forced abilty on Acolyte triggers twice, adding a total of 2 doom to the enemy

**Comment by halogenandtoast** [comment]
This should be resolved now.
