### ISSUE TITLE
Not able to open the Hunch deck to move an insight when drawing Joe's Elder Sign

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#424]
**Provide a Game ID**
77775e5b-aaed-47a8-be42-d4a74f682584
**Describe the bug**
As described, if Joe draws an Elder sign token there doesn't seem to be a way to draw a card from the hunch deck to the main deck. Maybe I'm missing something though.

![image](https://github.com/user-attachments/assets/013cbb41-9746-4a81-b324-b9b9f204e731)

**Comment by morg16** [comment]
Yep, the elder sign effect allows you to move an insight event from your discard pile to the bottom of your hunch deck - so the discard pile should be clickable if there are any insights in there.

**Comment by foodiemonster** [comment]
I confirm that I was being stupid and I was reading the effect wrong - everything works as expected so closing this one.
