### ISSUE TITLE
Kōhaku Narukami ability doesn't work properly 

### ISSUE THREAD

**Issue by Seltyiel** [halogenandtoast/ArkhamHorror#425]
**Provide a Game ID**
ac063ad6-9620-43bd-8ad4-2d5cdeeadd37

**Describe the bug**

Kōhaku Narukami ability should remove 2 and 2 tokens from the chaos bag to give an additional action but when used, the additional action is granted but instead of removing tokens they are added to the bag. Also can't use the debug function to go further because there is only the option to add tokens and not remove them.
Hope it's helpful.

P.s. I'm a new player and I might have missed something 

Best regards

**Comment by halogenandtoast** [comment]
Nope I was accidentally returning them to the chaos bag (from the chaos bag) and the code there didn't deduplicate so we duplicated the tokens.

So I've:

* Fixed it so Kohaku returns them to the POOL not the bag
* And, just in case, I don't duplicate the tokens that get returned.
