### ISSUE TITLE
Royal Emissary bug

### ISSUE THREAD

**Issue by BlazeInt** [halogenandtoast/ArkhamHorror#427]
**Provide a Game ID**
The id is the series of numbers and letters in the url for the game. After filling the bug please do not delete the game.
7fb312b7-153c-4d08-8aa7-ce5d77d8064c

**Describe the bug**
A clear and concise description of what the bug is. Feel free to add screenshots if it will help explain.
After Royal Emissary is defeated there is nothing else to click and advance the game

**Comment by halogenandtoast** [comment]
This was an issue with forced windows triggering multiple times and has since been fixed. You should be able to continue without issue if you hit undo twice, and then apply results again, the forced ability will pop up, but clicking it will dismiss it.
