### ISSUE TITLE
Using Jacqueline Fine's ability on the Forced effect of Dark Future results in sync issue

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#429]
**Provide a Game ID**
87046399-389a-4f3c-a260-68b7007b8b95

**Describe the bug**
At the end of my turn, I am forced to reveal tokens for Dark Future. I click the reaction symbol for Jacqueline Fine's ability, but this ends up in a sync error and it doesn't trigger.

**Comment by halogenandtoast** [comment]
I adjusted her ability and this seems to be fixed now.
