### ISSUE TITLE
TCU:prologue, Wraith does not attach to location on defeat

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#431]
**Provide a Game ID**
0c5ea351-ef74-4cd6-a437-f80ece6b623a

**Describe the bug**
Killed the Wraith with a knife which should attach it to the location. Instead it goes to the discard.

**Comment by halogenandtoast** [comment]
Turns out, I had not even implemented this card. Fix coming soon. Also, what a wild card to implement, the effect is quite cool, but hard to model.
