### ISSUE TITLE
Game is locked after Investigation phase

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#436]
**Provide a Game ID**
3a0ad12c-e4f2-4d09-8ccf-6b5555e4eb35

**Describe the bug**
After ending the turn nothing happens and nothing to click

**Comment by halogenandtoast** [comment]
There seems to be a forced effect on the agenda? Maybe refresh and see if it shows up?

**Comment by grabben2** [comment]
Yeah, that's correct, I was not seeing the Forced, because the Agenda was completely missing. See attached screenshot.

Refreshing didn't help, but loading it up on another computer and browser did. Agenda missing in Safari, working in Chrome.
![no agenda](https://github.com/user-attachments/assets/c0035b29-2763-4c95-844d-760652b75eb4)

**Comment by halogenandtoast** [comment]
That's weird, I'm checking in Safari and it is definitely showing up for me. Can you confirm which version of safari and maybe which version of OSX you are using?

**Comment by grabben2** [comment]
Update: probably some caching issue on the original laptop. 
Tried with both Safari and Chrome on the other laptop, both work. But I've seen the agenda disappear in some of my other games as well.

**Comment by halogenandtoast** [comment]
I'll keep an eye out for it, but without it happening for me I can't really debug what is going on there. The Act should be there, and I don't think I am doing anything too funky with the act that I am also not doing with the agenda that would cause one to render and not the other.

**Comment by grabben2** [comment]
Yes, I understand. Will see if I can figure out what causes it and let you know.

**Comment by halogenandtoast** [comment]
Going to close this for now. Feel free to reopen if new info becomes available.
