### ISSUE TITLE
Silas Marsh - Can't commit a skill card from my discard pile upon drawing the Elder Sign - effect doesn't trigger

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#438]
**Provide a Game ID**
53a832da-b5af-4d53-a1f9-da80010332b8
**Describe the bug**
Silas Marsh - Can't commit a skill card from my discard pile upon drawing the Elder Sign - effect doesn't trigger.
![image](https://github.com/user-attachments/assets/0cf20133-95c5-4495-93ce-f6b0f8d271f1)

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/235488de-ae23-4116-950c-ffee5ae662e1)

This is why
