### ISSUE TITLE
Threads of Fate: Stuck in test after advancing Act 2e

### ISSUE THREAD

**Issue by Loerpiou** [halogenandtoast/ArkhamHorror#443]
**Provide a Game ID**
b1a923ad-f0af-4fff-8be2-19bdada4e009

**Describe the bug**
It looks like the app doesn't recognise Maria as "Ithcata's prey". This leads to being unable to end the test since the game wants me to advance again (which if I do causes a sync error). So the game is kind of at a freeze right now as even on Toggle debug, I can't end the test or fix this issue.

![image](https://github.com/user-attachments/assets/31930052-6793-4555-9b7f-425acf75c855)

PS: this is a different issue [than this one](https://github.com/halogenandtoast/ArkhamHorror/issues/440), for which I commented a temporary solution.

**Comment by halogenandtoast** [comment]
I think I fixed this issue recently. Going to close this, but if it is still happening please reopen the issue.
