### ISSUE TITLE
Midnight Masks - Tablet token

### ISSUE THREAD

**Issue by alhepal** [halogenandtoast/ArkhamHorror#448]
I failed the Forced test at the Graveyard and drew a Tablet.  I was forced to drop a clue, but the game took 2 clues off me.

**Comment by foodiemonster** [comment]
Please provide the game ID as well for repro

**Comment by alhepal** [comment]
Sorry, I deleted the game :)  I will remember for next time

**Comment by halogenandtoast** [comment]
> Sorry, I deleted the game :) I will remember for next time

No worries turns out this was a very easy to locate issue, I literally had a 2 where there should have been a 1. Thanks for the report! I'm surprised it had not been caught before now!
