### ISSUE TITLE
Frozen in Fear applying one horror when skilltest fails

### ISSUE THREAD

**Issue by xvGold** [halogenandtoast/ArkhamHorror#456]
**Provide a Game ID**
a6a3935c-31d7-474d-8221-688f3c489dac

**Describe the bug**
Got Frozen in Fear in my threat area. Did skill test and failed by 1. On applying the test results the game wants me to add 1 horror to the Investigator. The card makes no mention of that and there's nothing I can see would cause this effect.

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/d6fe20ad-7184-4d83-b803-c8d1b82d99da)

It's the token effect.
