### ISSUE TITLE
Explore and Voice of the Jungle Bugs

### ISSUE THREAD

**Issue by EzieBaikUben** [halogenandtoast/ArkhamHorror#463]
[arkham-debug.json](https://github.com/user-attachments/files/16792225/arkham-debug.json)
**Provide a Game ID**
6328451d-a30e-4c0c-99c2-da26e6cb7697

**Describe the bug**
After performing an explore action twice with Winifred and drawing treacheries, the explore promp has disappeared and I'm unable to select it as my third action. Then on Mateo's turn, I'm unable to initiate an action on voice of the jungle in Wini's play area to attempt a test to remove it.

**Comment by halogenandtoast** [comment]
I believe you could no longer explore because of this.

![Image](https://github.com/user-attachments/assets/14b1aee5-38d9-4581-9737-f23c6bcad49d)

Looking into the Voice of the Jungle still.
