### ISSUE TITLE
Quick Thinking Extra Action

### ISSUE THREAD

**Issue by AUscarface79** [halogenandtoast/ArkhamHorror#473]
**Provide a Game ID**
dccf72e5-a8b9-4c8d-90d6-3f1141a7910e

**Describe the bug**
Commiting "Quick Thinking" to another investigator's test and succeeding gives the immediate action to the investigator who initiated the test and not to the one who commited the card.

**Comment by mniksa3** [comment]
this is a duplicate of
https://github.com/halogenandtoast/ArkhamHorror/issues/462
