### ISSUE TITLE
Hunted Down

### ISSUE THREAD

**Issue by alhepal** [halogenandtoast/ArkhamHorror#476]
a6a62626-9448-4be9-9b4d-ccb4b73a6163

This treachery forced me to Engage the Pit Boss when it moved to my location, even though it was Agenda 1a, and Criminals should be Aloof.

**Comment by halogenandtoast** [comment]
I think you just clicked too fast and it triggered Tony Morgan's engage ability., I tested this in your game and it doesn't seem to engage. Going to close this one, but if you still encounter this issue, please feel free to open it back up.
