### ISSUE TITLE
Healing with Carolyn's Elder Sign effect did not trigger her reaction ability

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#477]
Healed another investigator's ally with Carolyn's Elder Sign effect. This should trigger the reaction ability to give a resource to the ally's controller but it didn't

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e50b4e256dcf8810545be6d8dffdd6be53a49937ae76fed5871f3a22d89a7bc1.json

**Comment by grabben2** [comment]
Btw, great feature with the "File Bug" button :-)

**Comment by mniksa3** [comment]
**Game ID**: e58226d1-0d95-44f8-a350-0033b3d53a4f

Also happens here. Regardless if I heal myself, Peter (2), or Field Agent, I don't gain the resource off of the Elder Sign heal

**Comment by grabben2** [comment]
Doesn't seem fixed in this game: e058db67-b78b-4b72-a31d-7844554dc291

I hit "undo" until before the test was initiated. Cleared the browser cache. Still no resource after the test ended.

**Comment by halogenandtoast** [comment]
> I hit "undo" until before the test was initiated. Cleared the browser cache. Still no resource after the test ended.

I think maybe somehow the fix hadn't been deployed? I just tried locally and I see Sefina going from 3 to 4 resources. @grabben2 can you try one more time?

**Comment by grabben2** [comment]
My bad. I didn't realize I had to switch back to Carolyn to manually activate the reaction ability.  Carolyn's mini portrait was highlighted to show this but it was hidden under the skill test window.
In conclusion: it works, apologies.. :-)
