### ISSUE TITLE
Forewarned not working

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#482]
I used Forewarned, and still resolved Snake Bite

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ffabf756dd63e0c0cadedfbce18efd54b8969ccb1bbf341f29fe83be70cb7786.json

**Comment by halogenandtoast** [comment]
I happened to notice this as well yesterday and deployed a fix for it so you should be all set now.
