### ISSUE TITLE
Fast triggers on other investigator's tests

### ISSUE THREAD

**Issue by camipco** [halogenandtoast/ArkhamHorror#487]
Feature request. A setting to turn off fast self-pump triggers on tests taken by other investigators. For example, investigator A has Sparrow Mask in play. Investigator B initiates an investigate test. Sparrow mask triggers twice during the test. Technically within the rules, this is correct, but I can think of no circumstance where investigator A would want to boost their own foot during investigator B's investigate. With multiples of these effects in play (higher education is another example) triggering twice on every single test, it becomes tedious to click through. The ability to turn that off would be a significant QoL.

Amazing game, thank you!

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ac484d4ed403d0e389860545e549396fb820c22be4933bd38917a9cf6db3294c.json

**Comment by halogenandtoast** [comment]
Agreed, it's on the agenda for being implemented as a thing you can toggle, and with a default setting that keeps it from triggering. It will be one of the first things I do when I get the bug list more reasonable.
