### ISSUE TITLE
A weakness enemy of a resigned investigator

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#502]
should leave play when resigning

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6a5e46e09e5f1554abadf1fdf8212a605089caa76eb70407f9e66615e6b14064.json

**Comment by halogenandtoast** [comment]
I think it should remain in play:

Per the elimination rules section:

> Any card that player owns but does not control that is in play remains in play, but if that card leaves play it is removed from the game.

The player would not control a weakness enemy.

If I have this wrong please re-open the issue.
