### ISSUE TITLE
Set Aside Location does not spawn

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#504]
After I successfully investigated, the set aside location that was meant to appear by the card's effect did not get put into play.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ade5cea2db8946dfc43e0a68b19d7ea1584529376a9b7112f80c7a5721c04a53.json

**Comment by foodiemonster** [comment]
I believe the reason for this is that using Lockpicks or Rite of Seeking to investigate is only performing the basic investigate action and not actually triggering the card's special investigate action.

**Comment by foodiemonster** [comment]
I've bypassed the issue by giving toggling debug, giving myself an extra action, do a normal investigate and pass with +1 from the chaos bag and that spawned the set aside location. Will do this to be able to play the scenario going forward if I successfully investigate with either Lockpicks or Rite of Seeking. Still a bug though, just sharing my workaround!

**Comment by halogenandtoast** [comment]
@foodiemonster I don't think you can trigger the "special" investigate action by using Lockpicks or Rite of Seeking. You have to take the specific activate action to do so.

**Comment by halogenandtoast** [comment]
Okay I confirmed in the rules channel that this is the case. The alternative effect is tied specifically to that action (they changed this in the return to, which I just started working on).

Going to close this issue.
