### ISSUE TITLE
Activation St Hubert's Key

### ISSUE THREAD

**Issue by LeDonF** [halogenandtoast/ArkhamHorror#506]
When reaching the horror limit to avtivate St Hunert's Key you can't. There is an error message "your game is out of sync".

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ad5155a373f46e6f7448da3cffb0c552e3672d32b01326147dd8e7af1a1d8164.json

**Comment by halogenandtoast** [comment]
I think something else I fixed before has since fixed this.
