### ISSUE TITLE
Slowdown State

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#507]
The slowdown has been gradual since the start of the game but it has become untenable at this point

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/a4ff5e21fea3ad01823a7a86dbd4517e4fdf71f9f3fe3d24c0d28f782b0757a2.json

**Comment by halogenandtoast** [comment]
I believe some JS updated improved this situation.
