### ISSUE TITLE
Hunter's armor

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#508]
Hexdrinker doesn't draw a card (there is no option to exhaust), though Mark Harrigan ability did draw a card

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/978c1dcd1db3b96fae0f3d401d735b4b1f1ca4f0931dcfcffea9ebfb0dd87362.json

**Comment by halogenandtoast** [comment]
I might need a little clarification here. Not sure if you are talking about the damage that was applied to it before the snapshot above or from the treachery after.

For the damage before the snapshot that was damage from an enemy, not a treachery, so it would not have triggered.

For the damage afterwards I see the trigger, but realize it's not optional like it should be so I am adding a fix for that part.

**Comment by halogenandtoast** [comment]
Closed due to no additional details.
