### ISSUE TITLE
Prey-Only

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#510]
The thing that follows should not automatically engage an investigator whose deck is not where it is from

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8da5a1eb96e674b5db1bf3cfd106c326e5032e64fd05c5f5e42a268f66744422.json

**Comment by zsoltmoravcsik** [comment]
Also I have and issue with the The Thing That Follows : after defeated it is not shuffle back my client says: The game is out of sync, trying to reconnect

**Comment by halogenandtoast** [comment]
@zsoltmoravcsik can you post the game id (the url will suffice), or grab a debug file and upload it
