### ISSUE TITLE
"Voice of the Jungle" treachery action can not be triggered by another investigator

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#517]
Actions on treacheries in your threat area should be triggerable by other investigators on your location.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/fe8ec355bec0d13e18294312287527977076d58ed0324bd209c169ed4ba39d17.json

**Comment by foodiemonster** [comment]
Are you sure you can't? You can switch to the other investigator's view (either clicking the name or the little eye icon, they do different things so try both) and it should let you select it.

**Comment by grabben2** [comment]
Yeah, pretty sure. I've clicked all the eyes and names in every possible way.

If I haven't misunderstood, I should be in the perspective of the investigator trying to do the action, and then click the name of the investigator with the treachery. But I've tried all the other ways as well.

**Comment by halogenandtoast** [comment]
Whatever was preventing it before seems to be fixed now.
