### ISSUE TITLE
Matchbox entered play with 0 supplies

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#522]
https://arkhamhorror.app/#/games/0d2bbc35-20a7-4757-8007-e11b838acdb2
Game state is after I used debug to add the charges.

Played it a few turns ago and didn't need it, realised it had no charges on it.

**Comment by halogenandtoast** [comment]
@p-sin just a heads up there is a big issue that my tests caught and likely a ton of stuff will be broken until I fix it. Let me get back on the couple of issues you opened before you continue playing.

**Comment by p-sin** [comment]
@halogenandtoast I've pushed on a few turns as hadn't experienced too many issues. But I'll pause the game here for now.

**Comment by halogenandtoast** [comment]
I think the issue would only affect the playing of assets, but not sure yet.

**Comment by halogenandtoast** [comment]
Deploy going out that should fix this, but it take about 1 hour to finish.
