### ISSUE TITLE
To much actions 

### ISSUE THREAD

**Issue by Greyfax77** [halogenandtoast/ArkhamHorror#526]
Action 1: Playing "Old book of Lore" for 3 Resources from hand in playing area
Aciton 2: Exhaust Old book of Lore for effect
Action 3: Playing Scrying from hand to playing area
But I still have an action available.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/45a66aff7938d52ff47292a3e421a084e1a50c6f08fec6a82869c4f5216ec7f3.json

**Comment by Greyfax77** [comment]
The sidebar shows me that the use of Old book of Lore was not counted

**Comment by grabben2** [comment]
@Greyfax77 Are you playing as Daisy? She has an extra action to use Tome abilities.

**Comment by Greyfax77** [comment]
Sorry about the circumstances, that is of course absolutely correct.
