### ISSUE TITLE
Joe's Investigation Forced Ability Cause CRUSH

### ISSUE THREAD

**Issue by kaixinqi** [halogenandtoast/ArkhamHorror#530]
file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4270e79e2ffc95d2a3b887c2abdcad020bbd50d33ba618f8bc72b3f5ca134e58.json

**Comment by halogenandtoast** [comment]
I am not able to recreate an issue here, so I think maybe it has been fixed since you opened it.
