### ISSUE TITLE
Failing to explore at Rope Bridge "moved" me to River Canyon instead of "placing" me there, and did not end my turn.

### ISSUE THREAD

**Issue by Douggernaut** [halogenandtoast/ArkhamHorror#538]
With Track Shoes equipped, after I failed an exploration at Rope Bridge, my turn was not ended, and Track Shoes were allowed to be triggered. Since I was "placed" there and did not "move" there, Track Shoes shouldn't work anyway, even if my turn wasn't ended.

Track Shoes text (emphasis mine):
> Limit 1 Footwear per investigator.
> You get +1 .
> [reaction] **After you move**, but before enemies at your new location engage you, exhaust Track Shoes: Test  (3). If you succeed, move to a connecting location.

Rope Bridge test (emphasis mine):
> **Forced** - When you attempt to explore while at Rope Bridge: Test  (2). If you fail, cancel the exploration, take 2 damage, lose all remaining actions, and **end your turn**. **Place your investigator in the River Canyon** (if it is not in play, search the exploration deck for River Canyon and put it into play first; shuffle the exploration deck).

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5b7a307f8e3f2271a57ccad8ede53415854f9c630aa8e0dafeed9ab0980d6806.json

**Comment by halogenandtoast** [comment]
I do think technically if the Track Shoes reaction could be triggered it would not matter whether your turn ended or not. Either way I improved the logic/ordering here. And you are very right about the rope bridge interaction, nice catch! Fix coming soon.
