### ISSUE TITLE
Evading Ichtaca did not disengage and exhaust her, it put one clue on her, as if I had parleyed her.

### ISSUE THREAD

**Issue by Douggernaut** [halogenandtoast/ArkhamHorror#539]
I evaded Ichtaca successfully as Rita, and did not get to use Rita's [reaction] ability, then I noticed that Ichtaca was still engaged with me and had one clue on her.

Ichtaca's text:
> Alert. Retaliate.
> Parley. Test [intellect] (4) to convince Ichtaca you are not her enemy. If you succeed, place 1 clue on her. If you fail and Ichtaca is ready, she attacks you.

There is no text on Ichtaca, my location (River Canyon), the agenda (Intruders), or the act (Huntress of the Eztli) which would have caused this interaction.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/427e56eed176adfbc7ef4e50b581e07c1a2e8d132d98a10ff4c2b2bdaa7b2320.json

**Comment by morg16** [comment]
Just had this happen to me as well, 
919afc46-8f3e-4ffa-a681-575642738077
