### ISSUE TITLE
First "You handle this one!" didn't work, second one did.

### ISSUE THREAD

**Issue by Douggernaut** [halogenandtoast/ArkhamHorror#541]
I drew an enemy and played "You handle this one!", and nothing happened. I had to play a second one to send the enemy to the other player.

"You handle this one!"'s text:
> Fast. Play after you draw a non-peril encounter card, but before resolving that card's effects.
> Choose another investigator. That investigator is considered to have drawn that encounter card instead. Gain 1 resource.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b343f8cd8d5f0007cfd65caa491e25c04083759d0348faccec8da144bfe7c661.json

**Comment by halogenandtoast** [comment]
I think for this one you just have to skip the window for it to resolve. I'll see if I can update it so it plays more naturally.
