### ISSUE TITLE
safeguard

### ISSUE THREAD

**Issue by wwwwandian** [halogenandtoast/ArkhamHorror#545]
when i upgrade lv2 safeguard, it cant use anymore, i cant follow other investigators

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/406d9af0176b9075fb114420a51348040824e08b06e4ec5b364d580d97ee6745.json

**Comment by halogenandtoast** [comment]
I might have fixed this with something else, but make sure you click the eye icon to switch perspectives for this one:

![Image](https://github.com/user-attachments/assets/5fe69c52-e682-42bc-9950-e8c0af138739)
![Image](https://github.com/user-attachments/assets/6c0d5707-f1b8-4a64-af3d-1a0f1a9445da)
![Image](https://github.com/user-attachments/assets/e6fca28f-1dcc-48a7-bb6a-838bb543060c)
