### ISSUE TITLE
skill test window doesnt disappear

### ISSUE THREAD

**Issue by LeDonF** [halogenandtoast/ArkhamHorror#546]
After a skill test (fight) the skill test window is not disappering and overlays a card it seems i have to activate to progress the game.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/87d14db6ad7568c385fbf4ea041568a494aee1972e87bec34fb6e566eb243841.json

**Comment by halogenandtoast** [comment]
I've added an option to minimize it, but you are meant to drag it out of the way. Hopefully minimizing solves this issue for you. The deploy should only take another 30 minutes or so.

**Comment by LeDonF** [comment]
Yes, sorry, the problem was just a stupid user.
    
  

 Von: Matthew Mongeau ***@***.***>Gesendet: Donnerstag, September 19, 2024 2:31 PMAn: halogenandtoast/ArkhamHorror ***@***.***>Cc: LeDonF ***@***.***>; Author ***@***.***>Betreff: Re: [halogenandtoast/ArkhamHorror] skill test window doesnt disappear (Issue #546) 
I've added an option to minimize it, but you are meant to drag it out of the way. Hopefully minimizing solves this issue for you. The deploy should only take another 30 minutes or so.

**Comment by halogenandtoast** [comment]
I wouldn't say it's a user issue so no need to apologize. Any time the UI
isn't being helpful it is very useful for me to know so I can improve it.
Hopefully the re-addition of some transparency, plus the new minimize
functionality should make it slightly better. There is still room to
improve of course.
