### ISSUE TITLE
game out of sync, try to reconnect

### ISSUE THREAD

**Issue by moregontrail** [halogenandtoast/ArkhamHorror#549]
Won't progress to the next agenda card, just keeps saying out of sync, trying to reload

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d544e578e224f753755ea37a201f93539f105232e8c0676f22cfaa06427850ca.json

**Comment by moregontrail** [comment]
a7ae4141-918f-4cc4-8024-888b134cea08

**Comment by halogenandtoast** [comment]
The issue was the grappling horror trying to move from the threat area to a location that no longer existed. Fix going out for this.
