### ISSUE TITLE
Can't distribute resources or supply tokens when playing level 3 Emergency cache

### ISSUE THREAD

**Issue by GapTainPrice** [halogenandtoast/ArkhamHorror#551]
Players allow to distribute resources and supply token. However, the system help me to gain 4 resources directly instead of let me choose

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1a84572211a77807c21cea0b8cda2819fa84f2e68ce4bf7b91cdddd2e1f66423.json

**Comment by morg16** [comment]
The wording on Emergency Cache (3) means that supplies can be distributed among other investigators, but only you can be the one to gain resources from playing it. Not sure if this is your exact issue, but I hope it clarifies things!

**Comment by GapTainPrice** [comment]
Sorry for my poor presentation. The emergency cache allows me to distribute supply tokens to my asset. I have a cleaning kit with empty supply at that time, but the game did not allow me to put supply token to this asset.

**Comment by morg16** [comment]
My bad then, sorry for assuming you didn't know how it worked!
