### ISSUE TITLE
Connect the dots not triggering

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#553]
https://arkhamhorror.app/#/games/47ea38c3-18d8-49a4-9914-adc0df21caaa
Sorry! Deleted the game without thinking!

You'll need to go back to turn 4 or so to see it

Darrell discovers the last clue in 'Green room' (shroud 5), both hawk eye camera and crack the case trigger (last clue), but connect the dots does not.

Lighting box is in play (4 shroud) and I have 5 resources.

**Comment by halogenandtoast** [comment]
Without the game I won't be able to tell what happened here. I tested locally in the same scenario with the same cards (locations) and it seems to be workign for me. If you encounter this again, please reopen the issue.
