### ISSUE TITLE
Katana Succed by 2 broken

### ISSUE THREAD

**Issue by Grffiin** [halogenandtoast/ArkhamHorror#556]
I succeeded an attack against an enemy using Katana while succeeding by 2, but was not given the option to exhaust the Katana to deal +2 damage

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/fe68cfbe9f3bf0b96ef797885fa83fa442eee52e9ed3417e6c0e6249a52b19fe.json

**Comment by halogenandtoast** [comment]
It looks like the fight in the debug file is not using Kataka (it should appear to the right of your investigator). When I use it and get +2 I get the trigger

![Image](https://github.com/user-attachments/assets/5299e9ff-57b6-4a97-8b31-abf181b1a81f)
