### ISSUE TITLE
Honed Instinct's Fast trigger can't be skipped

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#559]
**Game ID**: 98796129-d209-406a-8456-c8e152e629c7

**Bug**: I've Customized Honed Instinct with the Muscle Memory selection, allowing me to play Honed Instinct as a fast immediately after I play an asset. However, playing Honed Instinct in this window is optional, yet the game does not allow me to skip this trigger after I play either one of my assets (in this case, as || Rex, either Book of Solomon or Press Pass). I tried moving further along in the game to test the other conditions but was only able to trigger the bug with Muscle Memory.

**Comment by mniksa3** [comment]
Was able to trigger Honed Instinct in another game and confirmed it was an optional play for Gut Reaction (a treachery enters your threat area) so the issue may just be with Muscle Memory specifically.

**Comment by halogenandtoast** [comment]
Sort of a funny issues. I have code that ensure that if you play a card you can't afford it forces you to not be able to skip reactions/fast triggers until it can be played. HOWEVER, it wasn't checking the window timing and was checking during the after window (after you've already paid and shouldn't need to anymore) so the game things you can't afford it and therefor more use whatever triggers you have until you can.

Fix incoming.
