### ISSUE TITLE
Stick to the Plan

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#562]
When playing Tommy, I cannot play cards under Stick to the Plan

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2cc15dc4928ba82931d7d6d4200bf6f2df7dad9c423925e19169c4f3edfa3f0a.json

**Comment by halogenandtoast** [comment]
In the file you sent me, you have no firearms and no assets in hand, so none of the cards under Tommy are playable. After I drew becky they becky you can see the corresponding card is playable 

![Image](https://github.com/user-attachments/assets/db71a38b-516f-4b36-8acf-dc966da370c5)

and if I play becky the firearm cards are playable

![Image](https://github.com/user-attachments/assets/38d964a8-e58d-4675-add0-5a4fdfd112e3)
