### ISSUE TITLE
Hunter's Armor  will take up two arcane slots

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#563]
I found that Hunter's Armor  will take up two arcane slots, this happened when I whated to play Enchanted Blade

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2cc15dc4928ba82931d7d6d4200bf6f2df7dad9c423925e19169c4f3edfa3f0a.json

**Comment by mniksa3** [comment]
**Game ID**: 95635931-2192-48d4-8d07-8655d993df5a

During an Ever Vigilant (1) play, I played Winchester, then Spirit of Humanity, then Hunter's Armor with the Enchanted upgrade. After playing Hunter's Armor I was forced to discard Spirit of Humanity even though I already had one Arcane slot free.
