### ISSUE TITLE
Cannot start any standalone scenario

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#567]
Game throws an error about no available settings for them, but I have played Curse of the Rugarou before and finished it successfully. Now none of them work.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/18a1ba8a110fba58822afc03e132f85e630c9af016a1c84c4a5fb2dac7d9bd17.json

**Comment by halogenandtoast** [comment]
Should be resolved. You will need to delete any games you could not start though as they won't progress, but anything new should.
