### ISSUE TITLE
Unable to advance act "At the exhibit"

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#568]
Can not advance the act even though I have the requisite number of clues and am at the correct location

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e977397f9a44a568c68161ac3c622bb9daa9201014c483f593ba4c3708ffdfdf.json

**Comment by halogenandtoast** [comment]
If you step back to right before the Eztli Exhibit enters play and resume from there this should be resolved.
