### ISSUE TITLE
Selecting deck results in 'game out of sync'

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#570]
I have just tried to start a Carcosa game, and also tried on FA.
FA game link: https://arkhamhorror.app/#/games/041a3655-795d-45b3-904a-ff5890ab0605

When trying to select a previously imported deck, I am getting the 'out of sync' error. Tried reloading and remaking the games a few times.

**Comment by foodiemonster** [comment]
Whatever is causing this, it's also causing #567

**Comment by halogenandtoast** [comment]
Should be resolved. You will need to delete any games you could not start though as they won't progress, but anything new should.
