### ISSUE TITLE
"Tear Through Space" Surge activates even when using the ability on the Act

### ISSUE THREAD

**Issue by morganF0** [halogenandtoast/ArkhamHorror#571]
**Provide a Game ID**
112d84f5-7eb0-4dbc-b127-5034e0702d7b

**Describe the bug**
Act 1a in "Lost in Time and Space" allows you to discard te top 3 cards of the encounter deck and resolve the 'revelation' ability on a location that was discarded. If the "Tear Through Space" location is chosen, it also activates the Surge keyword on that location, rather than only the revelation ability.

**Comment by foodiemonster** [comment]
I've seen this happen as well and at the time I thought it was intentional, but apparently rules as written, Surge should only apply when the car is drawn normally and not when it is drawn because of another card's effect that specifically states to only resolve the revelation ability on it.

**Comment by halogenandtoast** [comment]
I think I fixed this between then and now. I made some improvement to the out of this world UI (to show all the cards regardless).
