### ISSUE TITLE
Parley with Arkham Officers does not remove 1 doom from them

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#574]
It still gives me the clue, but their doom counter doesn't decrease.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5680979a38177ee542d8b45e76e8181d8e796d65820ecc1c1e5e6360959b1b67.json

**Comment by foodiemonster** [comment]
On this topic would it be possible to add an option to add/remove tokens from all cards? If the enemy card debug had the option to remove all tokens and then manually add the correct ones, it would at least let us bypass the issue temporarily.

**Comment by halogenandtoast** [comment]
> On this topic would it be possible to add an option to add/remove tokens from all cards? If the enemy card debug had the option to remove all tokens and then manually add the correct ones, it would at least let us bypass the issue temporarily.

Sure, added this, but also fixed the issue.
