### ISSUE TITLE
Healing multiple horror from Rational Thought may be broken?

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#575]
With both Hypnotic Therapy and Rational Thought weakness in play, using Soothing Melody should heal 2 horror from Rational Thought. 
The game lets me click for a Horror heal on carolyn (which does nothing) and then I can heal a horror on Rational Thought.
Maybe I am misinterpreting the rules, but I would think that I should be able to heal 2 horror from Rational Thought with this combo.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/0e52bf51cf6bf69f2f5de8711c23f665caa4921e6a07745606cea7c12f9c40c6.json

**Comment by halogenandtoast** [comment]
I think this works now, you just have to click each horror healed one at a time.
