### ISSUE TITLE
Occult Scraps doesn't appear in my hand after being revealed

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#576]
As described, the Occult Scraps weakness is meant to be in your hand after drawn and I cannot see it there to be able to deal with it.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8b2beb649f2514a6cfe330de28f0ca4535a29a8eb99fd5eb7786486dff9d1e13.json

**Comment by halogenandtoast** [comment]
Not sure what was going on, but when I checked it just now, it seems to work fine.
