### ISSUE TITLE
impossible de jouer partie

### ISSUE THREAD

**Issue by nikos0673** [halogenandtoast/ArkhamHorror#577]
Impossible dy jouer on me demande choisir deck dans parcourir mais rien

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6ff8a9d6036d7dce6766d36b1f7816ec920378d2037dde2124eaa01069f3897d.json

**Comment by foodiemonster** [comment]
Did you add a deck first in the My Decks tab?

**Comment by nikos0673** [comment]
Justement cette manipulation ne fonctionne pas j’ai pas peu

Le ven. 6 sept. 2024 à 13:51, foodiemonster ***@***.***> a
écrit :

**Comment by halogenandtoast** [comment]
I believe this should be fixed now, but please reopen if you are still seeing this issue.
