### ISSUE TITLE
Advanced 'Buried secrets' causes the game stop

### ISSUE THREAD

**Issue by KooBonchan** [halogenandtoast/ArkhamHorror#582]
Monty Jack attempted to draw the advanced 'buried secrets', and out of sync error occured.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/011c56b825dede10afe8d6820ef942808704e203cd9fc242624808d360d0392e.json

**Comment by halogenandtoast** [comment]
I believe this was fixed recently.
