### ISSUE TITLE
Vow of *drzytelech doesn't apply it effect

### ISSUE THREAD

**Issue by Aetyhs** [halogenandtoast/ArkhamHorror#586]
I play Trish (6 horror pool) and draw the vow for Dry for weakness.
When i reach 5 horror the game didn't kill my investigaor.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/008dd428d215bbbe541d2a12cd35bb099185126fa47b73a428df3656f9db3bf8.json

**Comment by halogenandtoast** [comment]
I have a fix for this, but you won't be able to see it during this game as the fix involves the placement of the asset (it was placed in your play area but it's supposed to be in the threat area).
