### ISSUE TITLE
"parley" of police officer doesnt work in excelsior

### ISSUE THREAD

**Issue by solarbeam7** [halogenandtoast/ArkhamHorror#588]
I parleyed police officer and succeeded but his dooms are not removed. Just I got a clue. I cant fix it myself  

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/268ef05e39fffa5773b8343250820c8ab244f43c66ba1095dcf12893402fd042.json

**Comment by foodiemonster** [comment]
Already been bugged here: #574 

Not being actioned yet though. I agree that it'd be helpful to have a debug on enemy cards that lets us do more on them (add or remove tokens for example)
