### ISSUE TITLE
Untimely Transaction Isn't Working

### ISSUE THREAD

**Issue by Tharrix** [halogenandtoast/ArkhamHorror#589]
Dexter Drake selects Cyclopean Hammer and I don't have the option for Hank Sampson to play it, even though he is at the same location as Dexter. The only option available is "No One Pays".

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/691a5448bf4e4e0192b522137b98a9182a842a87575bd31cfec2c3667ebcd3f0.json

**Comment by halogenandtoast** [comment]
So the UI might be a bit confusing here, but if you look at Hank Sampson the eye in the tab is blinking. This means Hank has an option available to him. In a normal two player game that player would be the one prompted, not the player who played Untimely Transaction, so when you click on that eye:

![Image](https://github.com/user-attachments/assets/57684d0f-b0c4-4ac4-9a8f-ce4b11682f39)

You will see the prompt for Hank to play it:

![Image](https://github.com/user-attachments/assets/376eabd8-73aa-49ec-a3ed-2c80ff2a5b2f)
