### ISSUE TITLE
Jeremiah Kirby Double Triggers or More?

### ISSUE THREAD

**Issue by Tharrix** [halogenandtoast/ArkhamHorror#590]
Played Jeremiah Kirby first round of the scenario and triggered his Enters PLay effect. Now it is triggering again right after. Maybe because Cryptic Writings triggered a reaction off the original reaction??

I saw someone recently claim they could do infinite triggers, hopefully this is an example.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/475f46faaabafd1f321f56e29c749e36c6bd6554d633e6b392dc1106c6c70839.json

**Comment by mniksa3** [comment]
Also having this happen in **Game ID** e5395719-7a91-4e21-9b63-2a0d26658161, with Jeremiah Kirby as a Geist in my || Jim's Spirit Deck. He triggered once and then immediately triggered again.
