### ISSUE TITLE
Midnight Masks Lita Chantler Trigger

### ISSUE THREAD

**Issue by Vlad17P** [halogenandtoast/ArkhamHorror#593]
In Midnight Masks I played Lita Chantler in my second ally slot(with Charisma). Her +1 combat stat was added to my combat rolls, but her +1 damage trigger ability never triggered after successful combats. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/a44ea93869bf3424d6c5e3b0e7aecb7359030ec250abd1a755c5da26cddb4830.json

**Comment by foodiemonster** [comment]
Are you sure the enemies meet the criteria for Lita's bonus to trigger?

**Comment by halogenandtoast** [comment]
She won't add extra damage to anything that is not a monster, so the only enemies in this scenario you get the bonus damage for are the hunting nightgaunts.
