### ISSUE TITLE
Royal Emissary hunted in the wrong direction

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#599]
He is meant to go after Lowest head, but he went after Agnes (who has a higher value on that stat)

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/9cec6bda2c3a1ab16dd19e1de3759d4f6e67d04f0364b0924861126f031999a4.json

**Comment by halogenandtoast** [comment]
Soooo fun fact but the Theater isn't connected to the Balcony (but the Balcony is connected to the Theater, by falling). And since prey only breaks ties Agnes is closer.

**Comment by foodiemonster** [comment]
Huh, didn't think of that. Good call. Sorry about the bogus bug!

**Comment by halogenandtoast** [comment]
No worries at some point I’ll add some sort of direction indicator but just have not done it yet. Sent from my iPhoneOn Sep 15, 2024, at 17:15, foodiemonster ***@***.***> wrote:﻿
Huh, didn't think of that. Good call. Sorry about the bogus bug!



On Sun, 15 Sept 2024, 08:00 Matthew Mongeau, ***@***.***>

wrote:
