### ISSUE TITLE
reaction ability skipping

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#614]
when I skip triggering Ursula's ability (skip trigger's' button), then I automatically skip Mark Harrigan's Safeguard trigger. I should be able to choose each trigger independently, regardless of order! sometimes I would like to move Mark first, but currently the system doesn't allow me to.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ac4bba2714263d5d90b8bf0a68006441f8418abce9f5bf873115f2ec3473d166.json

**Comment by halogenandtoast** [comment]
This might have gotten fixed between when you opened the ticket, but you should have been able to choose which one, you just need to switch the perspective to the investigator you want to trigger first (by clicking the "eye" icon in the respective investigator's tab).
