### ISSUE TITLE
Doom of Eztli Resolution

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#615]
Chamber of Time was in the victory display, but the 2 vengence for Yig's fury didn't count properly in the resolution.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1a61d43adea4e53469f3ea176c91680e2586957d6810a1c68a8711b590b2d569.json

**Comment by halogenandtoast** [comment]
Fixed this. I'll eventually add some sort of breakdown like I did for XP for vengeance.
