### ISSUE TITLE
Echoes of the past - hooded figure incorrect trigger

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#616]
https://arkhamhorror.app/#/games/0007484d-8c07-47d7-a977-494872bb19b5
Have played passed it though.

Drew the hooded figure on a test I succeeded on, but it forced me to add a doom to the seeker of carcosa.

**Comment by halogenandtoast** [comment]
@p-sin if you use the file a bug button it will snapshot the game at the time of the bug which will allow you to keep playing without losing the moment of the issue.

**Comment by p-sin** [comment]
@halogenandtoast Oooh, good to know
