### ISSUE TITLE
Inscription of the hunt allows moving and engagin aloof enemies

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#618]
I activated the axe and selected the Man in the pallid mask at a connecting location. I moved and engaged them.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6c2341f6de0abc2be1304f09fe91a033eb6e63f636f0720315226d6e6f2ba6fe.json

**Comment by halogenandtoast** [comment]
The game automatically did this by spending two charges for you, once for the move, once for the engage.

As such I believe it is working as intended but let me know if I misunderstood your issue.

**Comment by p-sin** [comment]
As with the other issue, you made the game too clever for me - making me forget they were aloof.
