### ISSUE TITLE
TCU: Evil Past Triggered Twice

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#623]
Evil Past reads: "Forced - When the encounter deck runs out of cards: Take two horror and test 3 Willpower. If you succeed, discard Evil Past." However, when the encounter deck ran out of cards (which there was also some dodgy business there because I feel like the agenda advancing didn't leave 5 cards in the deck but it was hard to tell) The forced ability triggered twice in a row.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/cfccd89e22177a362e6d9c45b83a7a6fa3ded766b7e545ce8f54bd75db322bb2.json

**Comment by halogenandtoast** [comment]
You were right about the 5 cards in the deck, fixed that. Which technically fixed the other issue, but I added an additional guard to handle it.
