### ISSUE TITLE
I can't distinguish which character I am selecting this for;

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#626]
and also, both options say that it removes a physical trauma, when each should say physical and mental

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/15e14ff395d5efc4244e37d3ec5b5471a62a3c4b5d6a830a3b66ea53f08bade9.json

**Comment by halogenandtoast** [comment]
Fix incoming for this. Also it was a little funny for me seeing the name of the campaign and realizing I knew was 발루시아 was.
