### ISSUE TITLE
XP calculation for Thread of Fate wrong

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#627]
additional XP from resolution is wrong; by not adding alejandro and Ichtaka I should gain 4XP, and 3 by finishing 3 act1 cards.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/74f40728326b809c94325dca0a07addd51a2e15d26b3c11a28e83e08720d042d.json

**Comment by halogenandtoast** [comment]
When I calculate the total xp I see 8 (which is how much the game is giving you):

1 point: From Harlan Earnstone in the Victory Pile
4 points: From Victory Point locations
3 points: Completed acts

> by not adding alejandro and Ichtaka I should gain 4XP,

I don't see in the rulebook where you get XP for not adding them, if you know can show me where it is, I will fix this, but I think I have it correct?

I do plan to add an XP breakdown soon so you can get a better idea of where the points are coming from.
