### ISSUE TITLE
The Boundary Beyond

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#630]
I spent gasoline Mark Harrigan had, but I still start with 2 less cards. Also, why are there 2 Expedition Journals in my deck?

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/82560f60b6e504c3797741d5e8f611d0d3f448d1490a5f42dd8cb3ba5b301247.json

**Comment by halogenandtoast** [comment]
Trying to work on this one but I have a question.

When you upgraded your deck did your deck on ArkhamDB did your deck there include an expedition journal?

**Comment by halogenandtoast** [comment]
The gasoline prompt is whether or not you get to mulligan. If you have not forged a bond with Ichtaca you get the silent journey effect:

![Image](https://github.com/user-attachments/assets/96417a81-fdd8-4ecd-8916-c30a2e574eac)

I plan to incorporate more of the campaign log into the scenarios at some point so these things will be more obvious.

**Comment by zzdldl31** [comment]
Oh yeah, that's right!

I did put in the Expedition Journal because I upgraded my deck via ArkhamCards app. The app automatically adds story assets into synced decks

**Comment by foodiemonster** [comment]
That's how I ended up with two copies of the man in the pallid mask in my
deck. It wasnt pretty.

**Comment by halogenandtoast** [comment]
Yeah I might be able to, at least with unique story assets, to check for this before adding them.

**Comment by halogenandtoast** [comment]
Added some code to protect against the duplication.
