### ISSUE TITLE
Wizard of the Order's Force effect resolves twice

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#632]
At the end of the Mythos Phase, the Wizard of the Order's Forced effect resolves twice (2 doom is placed). Scenario: Echoes of the Past

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e8f8d0c90c0a59b475973eac9359c820558cdf70ca89574976e47a47d6dbb68c.json

Game-id: 5c8cbb46-86a5-4fe5-bef5-783cf4991b2e

**Comment by halogenandtoast** [comment]
This should be resolved now.
