### ISSUE TITLE
Charlie has +1 ally slot

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#633]
Just realised I have 5 allies in play, but no charisma

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8f8a630ab584165255d70ab2dfea9a14ce771d0f09d4124dd6e97fb25e605240.json

**Comment by halogenandtoast** [comment]
The issue turned out to be Bonnie not taking up an ally slot. fix incoming.
