### ISSUE TITLE
Can't commit cards to other investigstors tests

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#634]
I think this is the case for every test really, in this test, I can't use gumption or any card.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/540181e8c71a2bd68a5d164f825e612f69dcb0cbf7d9fbb97762b95ab418520b.json

**Comment by halogenandtoast** [comment]
You need to click this eye to switch to that investigator's perspective

![Image](https://github.com/user-attachments/assets/ef8ffa20-cf4b-487f-9759-ad92d7ef4b87)

![Image](https://github.com/user-attachments/assets/8379fcac-3f4a-4fa4-96da-613b3402a325)

**Comment by p-sin** [comment]
Well huh, I did not know that clicking the eye did something different to just clicking their name.

**Comment by halogenandtoast** [comment]
Yeah... you're not the only person to not notice. I keep meaning to add an "instructions" section when you choose multi-handed solo. But it has been a low priority.
