### ISSUE TITLE
Scene of the Crime didn't discover 2 clues with an enemy at my location

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#636]
**Game ID**: 5e5f3142-d0a7-4cd4-ac65-b8ab25d492c4

**Bug**: Bit of a complex setup since I'm playing with the Advanced Cover Up weakness, but when I play Scene of the Crime with the Serpent from Yoth in play and choose to activate the reaction ability on Cover Up, only one clue is removed (from 4 to 3) instead of the expected 2. I wish I could confirm the same behavior for discovering clues off of my location, but there's only 1 clue where I am.

**Comment by halogenandtoast** [comment]
Scene of the crime can't "discover" more clues than are on the location so I believe this interaction is working as intended. If I bump a locations clues to 2, both are removed from Cover Up.

**Comment by mniksa3** [comment]
I guess because there's only one true clue at my location, and not 5 in the sense that there's one on my location + 4 from cover up, then yeah it's working as intended. This game continues to test my reading comprehension, that's for sure

thanks for looking into it anyway :)
