### ISSUE TITLE
Check your supplies screen (TFA) bug

### ISSUE THREAD

**Issue by JesterJayJoker** [halogenandtoast/ArkhamHorror#640]
I can't proceed past the First Scenario since I can't pick anyone to read Low on Rations.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/29ecb605516c9bfb65473111e6fe591b58f9940717c7783c33d8e735ab730f25.json

**Comment by halogenandtoast** [comment]
This should work now. Let me know if you have issues with it still, but you should be able to click on any investigators card to have them read it.
