### ISSUE TITLE
Chainsaw (4) & Cleaning Kit (3) not valid targets for Emergency Cache (3)

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#641]
**Game ID**: 08de87c1-c483-4d32-a243-6d35c1838d39

**Bug**: Playing Emergency Cache (3) correctly gives me the option to gain the resource or place a supply on an asset at my location; however, when selecting "supply," I am only able to place supplies on Lockpicks (1) and Fingerprint Kit. Chainsaw (4) and Cleaning Kit (3) also have "Uses (x supplies)" but aren't highlighted and can't be selected.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b0a395cb37b232b71cdea34f0d3b4a63d345a6e48f8317efeb9e382d6f680fd6.json

**Comment by halogenandtoast** [comment]
This has been fixed.
