### ISSUE TITLE
Twilight Abyss/Court of the Great Ones forced on enter bug

### ISSUE THREAD

**Issue by morvael** [halogenandtoast/ArkhamHorror#643]
**Provide a Game ID**
45d3c416-bc94-4e6b-9fd7-d34a0cb17693

**Describe the bug**
I think both Twilight Abyss and Court of the Great Ones didn't force me to make a test on entering while moving from Keziah's Room effect.
![image](https://github.com/user-attachments/assets/30fe5838-dce6-4a8d-b7f5-e59084142027)

**Comment by halogenandtoast** [comment]
I believe this has been fixed.
