### ISSUE TITLE
Molly Maxwell gives no option to name a Trait

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#646]
**Game ID**: 16c541fc-a5ff-403d-83c7-088cf0915945

**Bug**: When activating Molly Maxwell's Lightning ability, I am given no window or indication to name a Trait to search for a matching asset in my deck. Perhaps I'm just missing it or it's hidden somewhere but I can't find it.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e4d491dbb679eebb550c3e70842d1131aae5ad9503d5b906409b6ab9b21ed886.json

**Comment by halogenandtoast** [comment]
It wasn't showing, but I've fixed that.

BUT there is another issue with it (only in standalones) where it will give you no options. I've made a fix for that, but it won't fix your game sadly.
