### ISSUE TITLE
Parallel Jim's Investigator Ability didn't fire after Elder Sign was revealed & treated as Skull

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#656]
**Game ID**: e5395719-7a91-4e21-9b63-2a0d26658161

**Bug**: I revealed an Elder Sign with Olive McBride (2) and chose to resolve it as a Skull token. While Living Ink correctly triggered its Reaction due to Macabre Depiction (which would have worked either way, as an Elder Sign is also a symbol), my investigator ability reaction did not happen even though both Arcane Insight and Living Ink are valid assets that can receive an additional charge.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5c17d9b704c7c146966d76823466aab67f5aea6fdba9f1ff8ee7f9dbff497769.json

**Comment by halogenandtoast** [comment]
While the ability didn't work anyways. Neither Arcane Insight nor Living Ink were valid targets due to be a "replenish". When replenishing a charge you can't exceed the printed uses value.

That being said it was completely broken anyways and I've made some fixes.
