### ISSUE TITLE
Ancient Hall Forced Action

### ISSUE THREAD

**Issue by EzieBaikUben** [halogenandtoast/ArkhamHorror#661]
In the doom of Eztli, it looks like the ancient hall locations forced effect procs twice at the end of the round for some reason.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/7037f01a68c51b3b210995a6f30d41e081f8462e129a981bda933f57b0ca57b3.json

**Comment by halogenandtoast** [comment]
This seems to have been fixed with another fix.
