### ISSUE TITLE
Grift

### ISSUE THREAD

**Issue by EzieBaikUben** [halogenandtoast/ArkhamHorror#662]
Using grift to parley an enemy engaged with another investigator seems to soft-lock the game and does not allow me to select the intended target

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/707e72e4ae361445f38bca5c6af1ae55814ed10d7c6f8902f496b996ca88ab55.json

**Comment by halogenandtoast** [comment]
Seems to work now, you just need to click the other player's tab (not the eye icon) to see their threat area.
