### ISSUE TITLE
2 Winged Serpents

### ISSUE THREAD

**Issue by morvael** [halogenandtoast/ArkhamHorror#669]
I think the code doesn't take into account the variant that I'm playing this scenario for the 2nd time, and has just spawned second Winged Serpent.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e82ac4692b1a8ea8671586a0b004f36e78d13d7d5d9ef60f3b0575e80ae7834d.json

![image](https://github.com/user-attachments/assets/e3c98dab-44e4-42f4-8e08-01d6ce0652d5)

**Comment by morvael** [comment]
"If you have played this scenario before during this campaign and have reached act 2 before, flip act 1a over and place it in the Mouth of K’n-yan."

I guess scenario needlessly creates another act 1a card for this case.

**Comment by halogenandtoast** [comment]
> I guess scenario needlessly creates another act 1a card for this case.

Yeah it should have been skipped
