### ISSUE TITLE
Power Word commands are not available

### ISSUE THREAD

**Issue by DennievanderStarre** [halogenandtoast/ArkhamHorror#670]
I've upgraded Power Word to have "Betray", "Confess" and "Distract". I also have the Tonguetwister upgrade so I may give 2 different commands. But after succeeding the Parley test, I can only choose "Go" and not the other commands.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2250799caa4358ee78c4d44708d0335f1dcc221610014a0f4f517c16dcdde356.json

**Comment by DennievanderStarre** [comment]
As far as I know, Betray and Cofess should be able to target the enemy himself (in this case the Rats). Confess should work, because Rats gain +2 health from the current Agenda, and the Shroud Value of the location is 2.

**Comment by halogenandtoast** [comment]
I had programmed this to not allow you to target the enemy itself, fix incoming.
