### ISSUE TITLE
Stuck on Upkeep 4.6 - Last King 2H Solo

### ISSUE THREAD

**Issue by timefades** [halogenandtoast/ArkhamHorror#672]
A few rounds into The Last King, I seem to be stuck on step 4.6. The game won't progress any further, and I can't find anything that needs to be triggered, and the "Skip Trigger" buttons on both characters are greyed out.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1407464bee121c28a746a743bff46a0c603f99a99be743b8ec1e25b39ab65274.json

**Comment by halogenandtoast** [comment]
What browser are you using? There is a forced effect on Ooze and Filth which is attached to the agenda.

**Comment by timefades** [comment]
> What browser are you using? There is a forced effect on Ooze and Filth which is attached to the agenda.

Google chrome on a chromebook. The agenda deck doesn't seem to have loaded in. I've never played Carcosa before so I wasn't sure if that was intended or not.

**Comment by halogenandtoast** [comment]
Ah ha, there is some sort of css (or other) issue, but I can't recreate it to debug easily. The agenda deck should definitely be there.

**Comment by halogenandtoast** [comment]
I tried to put a fix in for this, going to close this issue, but let me know if this is still a problem (please re-open the issue if it is).
