### ISSUE TITLE
Canals of Tenochtitlan

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#678]
8 tokens are put on top instead of 4; in 2 different timing windows. Not sure what caused this;;

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/38160f4320f2139bd4e2527d1c8889a94fd230f6e5e61e3754b01fdb95c5f7ba.json

**Comment by halogenandtoast** [comment]
This has since been fixed, if playing this game step back to before the explore cards show.
