### ISSUE TITLE
Act3a "Planning the Escape" does not advance

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#691]
I completed 4 of the tasks, but I guess its not being tracked anywhere? I completed setting fire to the kitchen, inciting the fight,  know the guards' patrols and recalled the way out. It should have been sufficient.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ff95f921ca533d31e45eafa179b049cefe8eee533094812a676dfce10c6e0f8b.json

**Comment by foodiemonster** [comment]
I debugged my way out by moving to the Garden, removing the clue there and adding myself enough actions to pass the test  and that made the Act tick over. I'm guessing one of the other four events must have not triggered.

**Comment by halogenandtoast** [comment]
@foodiemonster It looks like you only did 3 tasks? Luckily I've just updated the UI to show them in the log:

![Image](https://github.com/user-attachments/assets/1c401b4d-ea2c-4819-b44b-b17df9f5e331)
