### ISSUE TITLE
I have two copies of the Pallid Mask Man in my deck and I rejected the Tattered Cloak but still have it

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#692]
I have two copies of the Pallid Mask Man in my deck and I rejected the Tattered Cloak but still have it

there's no obvious way of getting rid of either, I tried to debug my way out.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/978b6e6e64d5bde1692ebd05c25fe6c90979158f26d58877f90e4ed09e4e16ec.json

**Comment by halogenandtoast** [comment]
I went back and played through rejecting the tattered cloak and I don't see it in the deck afterwards so maybe there was a misclick? I don't have a way to fix that.

I've added some code to prevent duplication.
