### ISSUE TITLE
Discarding The Harbinger from the top of my deck revealed another The Harbinger underneath it

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#698]
**Game ID**: eecd66a1-c1db-4b43-a3f7-0c86bd4da8c5

**Bug**: In the previous round, with The Harbinger on top of my deck, I instead opted to  move 3 times, so the Harbinger remained on top of my deck through the end of this round and beginning of the current one. Perhaps due to a separate bug with The Harbinger and Forced Learning (here: https://github.com/halogenandtoast/ArkhamHorror/issues/697), after the Mythos phase concluded and I took the double action to discard The Harbinger, a second copy of The Harbinger was underneath it. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/fb8ff7fdfbe9bdde76572748186521ef93c01601cec408e84faabd5ea4803d51.json

**Comment by halogenandtoast** [comment]
Yeah so basically the bug was because forced learning actually "drew" cards it put another copy of The Harbinger on top of your deck. Fix incoming.
