### ISSUE TITLE
Add an option to start a campaign from a given scenario

### ISSUE THREAD

**Issue by Whimsical-Cloudheart** [halogenandtoast/ArkhamHorror#70]

**Comment by halogenandtoast** [comment]
@Whimsical-Cloudheart for clarification, you want to start the campaign on a scenario rather than as a side scenario?

**Comment by halogenandtoast** [comment]
The foundation for this now exists, need to go back through some of the campaigns to allow you to pick settings, so please open any bugs for scenarios that require settings.
