### ISSUE TITLE
Seal of the 7th Sign only triggers on own tests

### ISSUE THREAD

**Issue by camipco** [halogenandtoast/ArkhamHorror#702]
Seal of the 7th Sign works correctly losing charges when controlling investigator draws symbols, but doesn't notice when other investigators draw symbols. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/248fd9a31d39efd99fede84a1224f2c9448e24dc85cf8e957c7edb5513362d96.json

**Comment by halogenandtoast** [comment]
Fixed this recently.
