### ISSUE TITLE
Defeating a Weakness Enemy doesn't trigger Yorick's ability

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#708]
Killed Graveyard Ghouls, expected to play an item from my discard pile but wasn't offered the possibility to do it. I had not asset in my discard pile, so it can be completely normal, but usually you get a visual clue and have to interact even though there is only one option.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/17f8f13e8cdc475fb1eb2d07e92f768a21e98a004c8507f9b868ba4478ecadac.json

**Comment by halogenandtoast** [comment]
Usually if there are no valid options a reaction will not trigger. This is the case here.
