### ISSUE TITLE
Scene of the Crime on a Location with two Enemies didn't grant any clue (0 clues)

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#709]
Played Scene of the Crime, got 2 resources removed, but no clue was gathered (not 1, nor 2 even though there 2 enemies at my location).

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f335b9304baf12cba662047031bbb3357c4d831a1f0f2f5bd530c108a8fda79c.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/a9e958f6-02b7-4f90-a81c-9720ca8c22c8)

The card itself should not be playable, so I've updated it to no longer be playable if you can't discover clues for some reason.
