### ISSUE TITLE
Restricted hall in Miskatonic museum

### ISSUE THREAD

**Issue by DilirConfar** [halogenandtoast/ArkhamHorror#712]
Restriced Hall spawned first, while it should be in the bottom 3 cards of the exhibit decks.
Bug seems fairly new, never had this before

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5fd263f9033672347f7dc581233b839a94d1df65e5c3f9c683d93d0df18d49bd.json

**Comment by halogenandtoast** [comment]
This should be fixed now.
