### ISSUE TITLE
New display change causes some of the map to be obscured

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#714]
The zoom functionality is a much-welcome addition. However, for maps with lots of verticality, once you zoom in a bit, the top locations get hidden behind the scenario info area. I normally play on Chrome at 125% zoom. Zooming out to 100% puts everything in a visible area, but then using the new zoom slider moves the top locations out of the way again.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ef112f31213773581352d4adfb34be8
![Screenshot 2024-09-25 101740](https://github.com/user-attachments/assets/0e2a782c-bc33-44e5-905d-1ed172701a79)
f87a37e8db4736f38e7c57ed4b0fde3d9.json

**Comment by halogenandtoast** [comment]
I think this got resolved in the last deploy, so going to close this, but if you are still seeing it, please reopen the issue.
