### ISSUE TITLE
Olive McBride doesn't work as intended

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#719]
I picked 2 tokens out of the three and it kept drawing tokens even though I would've already passed the test on the first 0 + Bless

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6a3e9e5dd26b5b64bdcacbd8a555945687583a40a18718a0bd4db1490c7d80b4.json

**Comment by halogenandtoast** [comment]
But the bless token has to resolve which triggers drawing another token, which drew another bless so you draw another token, which drew a bless and then finally you drew an autofail, I believe this is working as intended
