### ISSUE TITLE
Rehearsal Room Forced Effect Wrong Timing

### ISSUE THREAD

**Issue by GuerricS** [halogenandtoast/ArkhamHorror#725]
Simple one here; the Forced Effect on Rehearsal Room is resolving during Step 7, when it should resolve during step 6

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/eebf48b2c9bf71e0db92c705f5a3940350d68ecbe9c57c669e58ca75a7a27392.json

**Comment by halogenandtoast** [comment]
I have a feeling fixing this is going to open a whole can of worms of issues, but I've split up the timing. Will be live soon.
