### ISSUE TITLE
Nathaniel getting 2 basic weaknesses

### ISSUE THREAD

**Issue by Kittithara6509611544** [halogenandtoast/ArkhamHorror#727]
I just started the game and I somehow got "Damned" and "The Tower" with opening hand/already in play

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b57d04e3a30d4f968f25b1ce5afb06221013a05c89a239033bcfa451a402beb3.json

**Comment by halogenandtoast** [comment]
I think I fixed this, but it's hard to tell, you should be able to step back and reload your decks. (After I mark this as deployed.)
