### ISSUE TITLE
I can't play live and learn

### ISSUE THREAD

**Issue by Kittithara6509611544** [halogenandtoast/ArkhamHorror#728]
I purposfully trying to investigate with low skill to use live and learn but there is no trigger for me

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f3f92252ec3254df892dbe25887c898c567ceee17ad9084a05736d23d82bd69d.json

**Comment by halogenandtoast** [comment]
If I give you 2 resources before taking the test, it becomes playable

![Image](https://github.com/user-attachments/assets/6e671c8d-beca-4000-a244-86703b85fd1b)

**Comment by halogenandtoast** [comment]
Sorry some of the text from the last message disappeared. Your location increases the cost of each card in your hand by 2 and you don't have enough resources. Which is why giving you 2 resources above causes it to become playable.

**Comment by Kittithara6509611544** [comment]
Ohhhh, my bad. Reading text on location is literally my weakness. I always forgot them
