### ISSUE TITLE
Out of sync error

### ISSUE THREAD

**Issue by Kittithara6509611544** [halogenandtoast/ArkhamHorror#729]
After I just submit issue #728 I can't play live and learn I was gonna continue playing but when I pressed end turn on Stella I just got out of sync error

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ee19e01b0acc794e6b7c5b388362e0b5a70844a61c2ac8a9fe08f36ba3203473.json

**Comment by halogenandtoast** [comment]
I think this might be fine now? Let me know if you are still unable to progress.

**Comment by Kittithara6509611544** [comment]
After I go back to home page and come back again it was already resolve. Sorry I forgot to tell that. I thought it might still be error for you.
