### ISSUE TITLE
TFA Scenario won't finish.

### ISSUE THREAD

**Issue by johnsmith7979797** [halogenandtoast/ArkhamHorror#731]
After completing R1 of the first scenario of TFA, pressing 'continue' does nothing except persistently display a 'this game is out of sync' message.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c4381063072090aed82316f9bf78c577ff7f658af8b8490cd8ff6ff5cc611e3f.json

**Comment by halogenandtoast** [comment]
I believe this is fixed now.
