### ISSUE TITLE
Locations shuffled into encounter deck at the start of scenario

### ISSUE THREAD

**Issue by Vexerd** [halogenandtoast/ArkhamHorror#736]
Locations shuffled into encounter deck at the start of scenario

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/bc9e4e80947bfa885e7e6f096dabeb030824889e3f49380cd088ff07109b5bc4.json

**Comment by halogenandtoast** [comment]
This has recently been fixed so it should not happen again.
