### ISSUE TITLE
Carcosa VI - The Pallid Mask setup error

### ISSUE THREAD

**Issue by KooBonchan** [halogenandtoast/ArkhamHorror#737]
Tomb of Shadows (and Blocked Passage) should be in the bottom 5 of the catacomb deck, thou it came out too early.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/0cdcc682e55fb3b75230955e2142ff3f906323b61351c38de9d7d9e897fb9e87.json

**Comment by halogenandtoast** [comment]
This should be resolved now.
