### ISSUE TITLE
Agenda 2 Dunwich Scenario 2

### ISSUE THREAD

**Issue by pventrella20** [halogenandtoast/ArkhamHorror#738]
The 2a agenda advances but the game it's stucked on the 2b text

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/7c007c7d811ce5f7445e2e84eefc58b95615b890b2de334a2d4b99fa31eb4a16.json

**Comment by halogenandtoast** [comment]
This should be fixed now.
