### ISSUE TITLE
Yig's Fury

### ISSUE THREAD

**Issue by Sephi97** [halogenandtoast/ArkhamHorror#739]
In this round, Ursula is defeated, and therefore, the scenario ends. However, Vengeance points are added to Yig's Fury after checking if it's 3 or higher, so the campaign isn't over. This app adds those 3 Vengeance from Victory zone (making Yig's Fury 4) and all my investigators die, provoking a game over.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/210fc034164953ea236b79d28fbaffde5d045d47ad68c80be6c643c42255a03e.json

**Comment by halogenandtoast** [comment]
This was accidentally triggering the investigator defeat section multiple times. Fix incoming.
