### ISSUE TITLE
Act of Desperation

### ISSUE THREAD

**Issue by dadebat** [halogenandtoast/ArkhamHorror#749]
It is many times that I try to play Act of Desperation and is says that "the game is out of sync", but it works fine when I play any other card.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6bd77a56d1944819dec2544216f5bc34dde4666a2ef4cb12ebdd323aa238c6f2.json

**Comment by halogenandtoast** [comment]
I think in this case it shouldn't be playable because you have no hand slots items, fixing it so it doesn't show up as playable in this case.
