### ISSUE TITLE
Upgrade Deck

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#751]
How can I upgrade the deck? It does not seem to work.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/058110c302bead5d123fc2dba85c1a7cc0a9de1266f419bc598564831571a6cc.json

**Comment by halogenandtoast** [comment]
I assume the additional issue and video might have helped resolve this issue, so going to close it, if you are still having issue can you update the other issue.
