### ISSUE TITLE
Skill Test hangs

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#752]
I don't see any reason why the test does not  continue.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/9038d537570c8433ba358cdeaece29fc2df704931b378d2a5eaa0fe7bdc4199c.json

**Comment by halogenandtoast** [comment]
You have to commit arrogance to continue:

![Image](https://github.com/user-attachments/assets/e0c87d39-a52c-4e28-8c39-b97a91d7931a)
