### ISSUE TITLE
Drew Clover Club Pit Boss from the encounter deck

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#757]
On Rex's first encounter draw of the game, he drew a second copy of the Clover Club Pit Boss, in addition to the one which was already in play at his location

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ff6bd326a79b0d2f86db577eafd6bced211819c68ee333a6915cf00c851c0abb.json

**Comment by halogenandtoast** [comment]
Can't fix this for your game, but it will be fixed for future games.
