### ISSUE TITLE
Game hangs

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#758]
Game hangs after skill test success

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/90fec0fe84db78c3ee7e7dbffc6b8d160ff3aa03baee70fa5b5e3072435f054a.json

**Comment by halogenandtoast** [comment]
This was because Yorrick's elder sign ability triggered requiring you to return a card from your discard. It might have been hard to notice, but the game has been updated to show the discards in the skill test window to make it easier.
