### ISSUE TITLE
Uncage the Soul 3 doesn't play from discard

### ISSUE THREAD

**Issue by camipco** [halogenandtoast/ArkhamHorror#759]
On casting Uncage the Soul 3 on a spell in the discard, that spell does not resolve, in fact just kinda disappears. Happens with both asset and event spells. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c0b8263a73396eb05ae7ea07c8c934927247a68523d98b4b666263db328cb9d0.json

**Comment by halogenandtoast** [comment]
I believe this is fixed now.
