### ISSUE TITLE
Stuck in end of skilltest

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#761]
![01-10-2024_07-42-24](https://github.com/user-attachments/assets/309bc872-b61d-4c02-b796-0701eddc0e7e)
Successful skill test but the game seems to be stuck.
If no bug, but not that visible next step:
The game should point out more clearly what the next step is to continue.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f30b828ff9b7ecfd833d989456bb9a718f41adf6bf71c25ba9c11bfd659be452.json

**Comment by halogenandtoast** [comment]
Abilities that trigger things in non-visible areas are sometimes hard for me to incorporate in ways that are obvious. In this case you used Yorrick's response, so there is an active card in your discard, but the discard isn't visible. In this case I can "focus" the discard in the skill test window so I'll do that here. You will just need to step back and redo the reaction (once I've marked this fix as completed):

<img width="532" alt="Screenshot 2024-10-02 at 16 22 15" src="https://github.com/user-attachments/assets/58598b46-a0f2-4272-baef-c4ded16ef844">

**Comment by adrian-vogler** [comment]
Couldn’t You pop up a message window with the information?

Von: Matthew Mongeau ***@***.***>
Gesendet: 02 October 2024 09:23
An: halogenandtoast/ArkhamHorror ***@***.***>
Cc: adrian-vogler ***@***.***>; Author ***@***.***>
Betreff: Re: [halogenandtoast/ArkhamHorror] Stuck in end of skilltest (Issue #761)


Abilities that trigger things in non-visible areas are sometimes hard for me to incorporate in ways that are obvious. In this case you used Yorrick's response, so there is an active card in your discard, but the discard isn't visible. In this case I can "focus" the discard in the skill test window so I'll do that here. You will just need to step back and redo the reaction (once I've marked this fix as completed):
Screenshot.2024-10-02.at.16.22.15.png (view on web)<https://github.com/user-attachments/assets/58598b46-a0f2-4272-baef-c4ded16ef844>

**Comment by halogenandtoast** [comment]
> Couldn’t You pop up a message window with the information?

My plan is to do something like that here (as in the screenshot I posted). I just manually have to find all the relevant other places and do the same thing so there might be other cases where this is missing after this fix.
