### ISSUE TITLE
The lowest result in a test is 0

### ISSUE THREAD

**Issue by dadebat** [halogenandtoast/ArkhamHorror#768]
It is not posible to get a negative result in a skill test. If your skill is 1 and you draw a -2 token from the bag, the result of the test is 0. So for a test which you need to get a 3, you have failed by 3, not by 4.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/99fe821f57a57ae2a68dcc3343dc9aa71237a6a18108131a4295e0bfbc0e30b0.json

**Comment by halogenandtoast** [comment]
This is really just the frontend UI showing you the wrong result. The backend actually handles this correctly. If you notice Finn only takes 3 damage the value is correctly bounded. I need to bring some of that logic to the display on the frontend.

**Comment by halogenandtoast** [comment]
The frontend should be better about this now.
