### ISSUE TITLE
XP in At death doorstep

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#770]
I think there is a problem with the XP on the victory display. Josef MEiger is 2XP and the Nether Mist 1. Plus 1 rogue event

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d16d3b436b266682cb111130ad57214ad6be5a4050c3fea15402ca2b18e40c35.json

**Comment by halogenandtoast** [comment]
Also in the future it will start to say the name of the card (or effect) that granted the XP

<img width="1077" alt="Screenshot 2024-10-03 at 8 55 47" src="https://github.com/user-attachments/assets/eafef0e0-5f03-4890-99bf-4e63eca5eb4a">
