### ISSUE TITLE
TFA: The Untamed Wilds drew a location from the encounter deck

### ISSUE THREAD

**Issue by ShadowK2300** [halogenandtoast/ArkhamHorror#771]
My final action of the turn was an explore, in which I drew a treachery. When it came time to draw an encounter card however, I revealed a location, which was put into play but I didn’t get moved to it.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ac98a1f16a14bd8b5c8c6e91429de3b1b7d77662c3444d39fa124c7ed099206d.json

**Comment by halogenandtoast** [comment]
This has recently been fixed, they got shuffled into the deck during setup, but will not longer be shuffled in.
