### ISSUE TITLE
Cannot go back to standard view

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#774]
As the split view is flawed (see other bug) wanted to go back to standard view butr the menu command does not work.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/61d062eb23fd43f2e3b4856da597dd9d0c0b29c7e22079fc8a8b1990e48993ba.json
![image](https://github.com/user-attachments/assets/3ff244bd-98bb-4885-8141-32474b43fc59)

**Comment by halogenandtoast** [comment]
I'm reverting the automatic split view, which will make the toggle work correctly. Fix incoming.
