### ISSUE TITLE
Context Menu items not accessible

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#775]
Context menu items that appear here are not really accessible. Instead there is a switch between the investigators. There should be mopre room so that context menu items are completelly visiblke an accessible.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3c08e3976a0abec05aac5035a042d14319550f62fb9f26848d9c3d3f228ac64e.json
![image](https://github.com/user-attachments/assets/8b97d6eb-d1e7-4720-a4c5-8dec18c9e7e1)

**Comment by halogenandtoast** [comment]
This should be fixed.
