### ISSUE TITLE
Other campaigns, esp. Edge Of The Earth

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#779]
Will other campaigns, esp. Edge Of The Earth, be added to the game?

**Comment by halogenandtoast** [comment]
Yes I am currently about halfway through adding The Innsmouth Conspiracy and Edge of the Earth will be next after that.

**Comment by foodiemonster** [comment]
You are doing the work of gods among men.
----
*Javier Altman*
*Senior Gameplay Animator @ Rockstar Games (Edinburgh, UK)*
