### ISSUE TITLE
Rougarou does not move after receiving damage.

### ISSUE THREAD

**Issue by Flipy38** [halogenandtoast/ArkhamHorror#780]
After you do any damage to the Rougarou he should disengage and move to the furthest location but after a 2 damage attack playing solo it does not move and stays engaged with me. Then I undoned and try to do a 1 damage atttack and it works properly. 
I checked a couple of forums just in case and the consensus is, it should move after receiving any amount of damage. 
I also tried to debug to move the Rougarou manually but I couldn´t find the option.
Sorry for the long writing I hope it helps.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4b21e6d283146727a795d0cad6c44f9ae61c93fd34262e1c33c65a7e68bce713.json

**Comment by adrian-vogler** [comment]
Have the same problem.
How do I get it into a trap?
