### ISSUE TITLE
Agenda will not advance

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#781]
Will not advanced. The game is stuck on this side of the agenda.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e8ba694c79da1f87a1398728117cc86217918d7a3d377378814c9f1512b3e23c.json
![image](https://github.com/user-attachments/assets/41db6f13-d657-4cdc-8661-d600a28922a2)

**Comment by halogenandtoast** [comment]
No idea what caused this initially, could not recreate it.
