### ISSUE TITLE
Stepped back and Agenda still won't flip again

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#786]
Stepped back and Agenda still won't flip again
See video here: https://youtu.be/BfVjrxPW4jc

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/a99c7248a85ebd342c12d0f99ffcf986d2e72c35a5de4f6602a7658f69e9f8ae.json

**Comment by halogenandtoast** [comment]
Discussed via email.
