### ISSUE TITLE
Beginning of TPTC Scenario 6

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#787]
Just to get the JSON file

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/345f3c9c75429f3efd63fd741bcceb6075b0a4004e8c54f99f4306220e122f69.json

**Comment by halogenandtoast** [comment]
By the way if you want to export the json the debug menu has a debug export option which generates this file as well.
