### ISSUE TITLE
TPTC Scenario 6 - Wrong Agenda Deck Card displayed

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#789]
Wrong Agenda Deck Card displayed in TPTC Chapter 6

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/e19d82c2c53e15b38ab1587596990866c966f9ddad86897dd99e0af63692fd33.json
![image](https://github.com/user-attachments/assets/eca5419a-7d1e-44db-88c5-f64065a30c38)

**Comment by halogenandtoast** [comment]
Specter of Death is the other side of that encounter card, you just need to click it to have it spawn.
