### ISSUE TITLE
Special ability of investigator not triggered

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#791]
Special ability of investigator not triggere. Minh should get a "?" for the skilltest.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/98d43cc8d20f8154a31434e496849ea6366ec91a40b751057478c3ca04342ce7.json

**Comment by halogenandtoast** [comment]
I think maybe you accidentally skipped her trigger? I stepped back and did it and it worked fine. There is also a possibility that I fixed something between when you opened this issue and now.
