### ISSUE TITLE
House in the reeds forced action not working

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#793]
the title. furthermore, i already have a "choose" menu that are acoming from  previous scenario?

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4ed188bbe15016e97778d5dd60afc7e5413a3340efda9cc0fa162051bd4e0846.json

**Comment by halogenandtoast** [comment]
I found the issue that caused this initial prompt not to go away, but it is the thing that is messing up this game. You can fix this if you right click, hit show inspector and in the console type this:

```
sendDebug({"tag": "FinishedSearch"})
```

And press enter.
