### ISSUE TITLE
Wrong trigger activated?

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#801]
Why is this activated? It doesn't fit the skilltest.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ab3faf6790d8db8af771078cce0f0ccc77b9f022f9650bef39f1e23e91455323.json
![image](https://github.com/user-attachments/assets/1668c9af-b59c-4716-a4d7-b2d6bfc8ebbe)

**Comment by halogenandtoast** [comment]
I've changed how this works, but there are reasons you might want to trigger things that don't affect the skill test directly. For instance if you were running Dark Horse with this card, spending the 2 resources would allow you to get the benefit. However the default settings now keep this card from always triggering.
