### ISSUE TITLE
Cant spend clues on act 1 phantom of truth

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#806]
Cant seem to advance act 1 of phantom of truth even though I had the required amount of clues 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ae31053576ee4e2c916495e77af39c45801cace223a4de01c906378f90f7365f.json

**Comment by halogenandtoast** [comment]
When deployed you will just need to step back playing Sixth Sense, and then play it again, afterwards the objective should be available.
