### ISSUE TITLE
Option is missing from the local actions

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#808]
Option is missing from the local actions

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/92d5606e69ff885a46c545c2931731706afc868792146fc89bb06854668b07c9.json
![image](https://github.com/user-attachments/assets/a769abf1-a7d1-47f5-b5fe-4cf8a91ff0c0)

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/5c94b4a0-567c-442e-8e29-2443912715aa)

No torches.
