### ISSUE TITLE
Fast action does not trigger

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#812]
Fast action does not trigger

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/29fbf7c1812dbe39019aebb3e5dbc6f7ed1480c60ecc93964b55ec08609e1ccb.json
![image](https://github.com/user-attachments/assets/022a315b-74b8-4290-a19f-7413ba1df7f4)

**Comment by halogenandtoast** [comment]
You don't have the two resources to play it.
