### ISSUE TITLE
Gamebreaking bug: stuck in agenda 2 of black stars rise

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#818]
I had both 2nd agendas in play, and they progressed at the same time. Now, when i click agenda 2c, it says the game is out of sync.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/126965d2082b3021800780d8736df6f74ae46fe2ff0365ec479481a8e36a1f7e.json

**Comment by mniksa3** [comment]
Also happening here: 83bb67c7-aea6-4163-b164-8d0005857969

Agenda 1a had 5 doom on it, Agenda 2c had 7 doom on it, so both agendas would advance at Mythos start. Only agenda 2c is highlighted, and I get an out of sync error when attempting to advance.
