### ISSUE TITLE
Sometimes, free triggers on player cards get highlighted without option of skipping them between player actions / turns

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#819]
In this case, the Empty Vessel highlights and can't be skipped unless you enter debug mode to exhaust it so the trigger disappears.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/687c18e78501c2e06973adfa1c6408c1f7c210186b06297e1ddb106b71142615.json

**Comment by halogenandtoast** [comment]
You need to click the glowing eye to change player perspectives.
