### ISSUE TITLE
Unable to draw card

### ISSUE THREAD

**Issue by gustavoberman** [halogenandtoast/ArkhamHorror#82]
During investigation phase I'm unable to use an action to draw a card. The deck is highlighted but clicking on it does nothing.

**Comment by halogenandtoast** [comment]
Were you able to draw cards previously and it just stopped working? If so I have a feeling this is due to an issue with Prey Bearer enemies that I can fix.

**Comment by gustavoberman** [comment]
> Were you able to draw cards previously and it just stopped working? If so I have a feeling this is due to an issue with Prey Bearer enemies that I can fix.

Example: 
Start a new Night of the zealot, 1 player, first action I try to click on deck and nothing happens
Same in any previous round with or without an enemy.

**Comment by halogenandtoast** [comment]
I pushed up some random fixes, can you try now?

> Not sure if the above can help, can I suggest to add a button to the “cheat” menu to dump the state of the game? It will download a file with info about the game that we could report to you to facilitating the debugging.

Yeah I will consider adding this soon. I had not had a lot of people reporting bugs so it was less necessary

> Also, do you have a good resource to learn Haskell? I worked a lot with Prolog and I would like to help, if I can!

You can feel free to ask me any questions you want and I'd even be willing to pair on some features. Other than that, the Haskell Programming From First Principles book is highly recommended, I just sort of learned Haskell by programming things though.

**Comment by halogenandtoast** [comment]
> Not sure if the above can help, can I suggest to add a button to the “cheat” menu to dump the state of the game? It will download a file with info about the game that we could report to you to facilitating the debugging.

Added a button that exports your current game, which I can then import:

<img width="526" alt="Screen Shot 2022-06-01 at 9 46 27 AM" src="https://user-images.githubusercontent.com/201288/171432818-f679cf4d-ed72-45d7-a812-3778642c5f18.png">

**Comment by stefano-bragaglia** [comment]
Amazing, I'll have a look ASAP! Thanks!

**Comment by stefano-bragaglia** [comment]
Just did:
>>> git pull
>>> docker build -t arkham .
>>> docker-compose up
and started a new regular Night of the Zealot campaign.
<img width="2032" alt="Screenshot 2022-06-07 at 11 03 13" src="https://user-images.githubusercontent.com/4399978/172354796-82231052-595a-42d2-8a4e-62e5e24c4b83.png">

Drawing a card worked fine, but had an issue with Frozen if Fear (at the end of my turn, the forced button appeared just below it but it wasn't styled like every other button, and when I clicked it nothing happened: no prompt for a Willpower test to possibly discard it) and then I noticed that the "Debug Export" button wasn't there (see attached pic)...

**Comment by halogenandtoast** [comment]
@stefano-bragaglia you might need to hard refresh in order for the new JS to get picked up.

@stefano-bragaglia and @gustavoberman I will mention that I recently pushed a heavily refactored version of the app and so there may be many things broken, I'm going through and trying to fix them now.

**Comment by stefano-bragaglia** [comment]
Hi @halogenandtoast,
thanks for the update. I've just

    git pull
    docker-compose up --force-recreate --build -d

and I get this error message:
<img width="1387" alt="Screenshot 2022-06-15 at 13 56 59" src="https://user-images.githubusercontent.com/4399978/173827448-cb3e0b41-0b3c-4383-ac7b-2afcdd695da4.png">

Then, I did:

    docker-compose up

which started the server, but I think the former image was loaded. I'm using Safari as a browser so I empty the cache and reload the page, kill the current campaign a create a new Night of Zealot but I still can't see the Debug Export button.

Is there anything else that I can try? 
Maybe completely delete any image and build a new one from scratch?

Anyway, I've played a few Gathering and everything worked as expected (some Forced button weren't styled but were working correctly) the only issue I had was that the Act didn't advance to a Resolution when I defeated the Ghoul Priest.

**Comment by halogenandtoast** [comment]
Actually just `docker-compose down` should suffice.

**Comment by stefano-bragaglia** [comment]
I've tried with `docker-compose down -v` or `docker compose down`, and `docker-compose up --build --force-recreate`, but I still can't compile the `web` service... I'll try deleting the project folder and start from scratch...
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/4399978/174676132-05d4ba1f-db94-4b92-bcb2-de6f22ad4b8d.png">

**Comment by halogenandtoast** [comment]
@stefano-bragaglia give me a few moments to look at this again.

**Comment by halogenandtoast** [comment]
@stefano-bragaglia sorry there was a change to class symbols that broke the validate command. It should be resolved now.

**Comment by halogenandtoast** [comment]
>  I feel, however, there might be some problem with js.

What do you mean? The file dialog? That is there for me to debug, it isn't pretty, but I wanted to get something out quick. If you are expecting contents to appear and they aren't can you show me the web inspector content? Also for a quicker feedback look, it might make sense to move this discussion to the discord channel: https://discord.gg/262FKVXQ
