### ISSUE TITLE
Not able to commit Unexpected Courage

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#820]
Intellect test on a treachery. Committing Unexpected Courage is not possible.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/73422c9d8f6e3be44893bdf7ced2076cc905c520be2e438aa215cae6d5a36183.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/23cac473-0a1c-464a-93da-576049c0fabf)

So the real bug is it seems like Charlie can!

**Comment by halogenandtoast** [comment]
Nevermind, Charlie can't commit skill cards (but can commit cards that aren't skills). Either way the game is working as intended in this case. Eventually I will make things like this more obvious when I can figure out how to represent this in the UI.

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/61a6c889-9a1a-4d5d-b4db-9f60a80abc95)

Adding this.
