### ISSUE TITLE
Scrying Mirror Nonfunctioning

### ISSUE THREAD

**Issue by GuerricS** [halogenandtoast/ArkhamHorror#823]
Using Scrying Mirror appears to remove a secret correctly but fails to resolve the "reveal chaos tokens" step immediately as it is supposed to

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8d646b5657125fca40a0a8bc51d4f3de6b46114aeab550811e74e4c7cd03e0d2.json

**Comment by GuerricS** [comment]
On further investigation what appears to happen is rather than rearranging the steps of the skill test upon activation, it resolves the test normally up until the reveal chaos tokens step, after which it creates additional free trigger windows and an additional commit step. This is functional but incorrect, not to mention unintuitive.

**Comment by halogenandtoast** [comment]
By rearranging do you mean in the UI?

>  it resolves the test normally up until the reveal chaos tokens step

I don't think this is the case, it definitely skips the commit step and then only asks after you draw your token. Running through the example I only ever get to commit once.

However there do seem to be 3 fast windows (and there should only be two)
