### ISSUE TITLE
Why can't I choose from the options presented?

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#826]
Why can't I choose from the options presented?

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/372865fd5c3e4ad65d37fd6e5e05366a5b02d84f14a5254cf0af64e7c33adf1e.json
![image](https://github.com/user-attachments/assets/9325494f-7a4f-4cde-9d1c-cda1f6a7af11)

**Comment by halogenandtoast** [comment]
Seems to work now, not sure what was up.
