### ISSUE TITLE
Unfinished Business story card disappears after clicking it

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#827]
I killed the spectral enemy, revealed the story side which I'm meant to keep until I resolve its effects but as soon as I click it it goes away and I cannot find it anywhere in the app.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6342f5749373dc439a8ceb406c4bf863eadc6d7e7b8da4befbcf4e22ad37dd9f.json

**Comment by halogenandtoast** [comment]
It looks like it's just in Diana Stanley's tab

![Image](https://github.com/user-attachments/assets/17929d81-e473-4d80-bb5a-5438dcc12ec1)
