### ISSUE TITLE
HELP! Game will not load!

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#828]
Please help. I am near completion of Forgotten Age and the game will not load.
https://arkhamhorror.app/#/games/40ac5ad4-3c4f-407e-b3e5-063a36b17859

**Comment by halogenandtoast** [comment]
Should load now.

**Comment by adrian-vogler** [comment]
Yes, it does load, so it was out of sync in the beginning.

**Comment by halogenandtoast** [comment]
Does this mean it is working correctly now or is there still something blocking you from progressing?Sent from my iPhoneOn Oct 12, 2024, at 17:03, adrian-vogler ***@***.***> wrote:﻿
Yes, it does load, so it was out of sync in the beginning.
