### ISSUE TITLE
Spanish Images Failing to Load in the App

### ISSUE THREAD

**Issue by Nemeq** [halogenandtoast/ArkhamHorror#832]
**Describe the bug**

The image is available in both the repository and the digest file, and it loads correctly in local development. However, it fails to load in the production app.

Image URL:
[Link to the image](https://assets.arkhamhorror.app/img/arkham/es/cards/03010.avif)
`https://assets.arkhamhorror.app/img/arkham/es/cards/03010.avif`

Repository Location:
[Image in the repository](https://raw.githubusercontent.com/halogenandtoast/ArkhamHorror/refs/heads/main/frontend/public/img/arkham/es/cards/03010.avif)
`https://raw.githubusercontent.com/halogenandtoast/ArkhamHorror/refs/heads/main/frontend/public/img/arkham/es/cards/03010.avif`

Digest File Reference:
[Reference in es.json (Line 336)](https://github.com/halogenandtoast/ArkhamHorror/blob/main/frontend/src/digests/es.json#L336)
`https://github.com/halogenandtoast/ArkhamHorror/blob/main/frontend/src/digests/es.json#L336`

Despite being present in both locations, the image is not rendering in the live app.

Screenshot for reference:
<img width="1602" alt="image" src="https://github.com/user-attachments/assets/db22189c-8115-41c0-bef9-850850c7a5b0">

**Comment by halogenandtoast** [comment]
I needed to sync the images to S3, should be fixed now.
