### ISSUE TITLE
Forced "Fast" trigger before last player's turn

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#836]
In the game state the trigger for Keen Eye is activated without an option to skip the trigger. I've seen this happen more often with free triggers. Exhausting the card in debug mode usually helps, but it should give the option to skip the trigger.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3b46e5b181307047482970dbe4b595e6662cd8ce578e81936c8b99386797f64f.json

**Comment by halogenandtoast** [comment]
You just need to click the glowing eye icon to switch back to Finn
