### ISSUE TITLE
Game forcing player to commit

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#837]
At this point in the game state, the game basically forces the player to commit the highlighted card. Committing it and then undoing is the only way to not have to commit the card to the test when this happens.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/008be79fae7349162911edb57de0393c7e813ca503b77f86f13841fb8ea324de.json

**Comment by Kvothe-The-Bloodless** [comment]
I have had the same many times (and also discovered the same workaround ;) I actually came here to share it but I see you already found it yourself.)

**Comment by ChrisIsMyMiddleName** [comment]
I found another solution. Apparently what happens in this kind of situation is it has for some reason changed the point of view of an investigator who is currently not doing the skill test. If you change the point of view back to the correct investigator (clicking the eye icon to the right of the name) it switches the view to the investigator doing the skill test and you can proceed as normal.

**Comment by halogenandtoast** [comment]
Right, clicking the eye is the intended way to deal with this. The system tries to intelligently determine which persective you want to be in when playing multi-handed solo but it isn't 100% able to do this so sometimes you need to switch back.

Are you guys not seeing the glowing animation on the eye, and the tooltip, to help navigate you to that solution?
