### ISSUE TITLE
Grand Rue (Black Stars Rise) adds Doom on non-Investigate tests if you succeed by 1 or less

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#838]
**Game Id**: 83bb67c7-aea6-4163-b164-8d0005857969

**Bug**: The Grand Rue location reads "Forced - After you succeed at a skill test by 1 or less while investigating Grand Rue: Place 1 doom on the agenda with the most doom." However, even when I'm not investigating, the game forces me to add a Doom if I succeed by 1 or less. In this particular example, I am taking a Willpower test in the Mythos phase and succeeded by 0.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/77879a38416c9c01c67335108bbf915155ac28c4d66a5a06d857b9e5c1511adb.json

**Comment by mniksa3** [comment]
oops, duplicate of https://github.com/halogenandtoast/ArkhamHorror/issues/703

**Comment by halogenandtoast** [comment]
Fixed the original
