### ISSUE TITLE
Investigating with Burglary doesn't get rid of Obscuring Fog in case of success

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#84]
I've successfully investigated the `Hallway` with `Obscuring Fog` using `Burglary`.
I've got the resources, but `Obscuring Fog` wasn't discarded.
<img width="2032" alt="Screenshot 2022-06-22 at 11 47 48" src="https://user-images.githubusercontent.com/4399978/175011630-65133fb5-3652-4758-af33-9cd66594c77d.png">
[arkham-debug-3.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/8956905/arkham-debug-3.json.gz)
(Add to gzip the debug file to attach here.)

**Comment by halogenandtoast** [comment]
Fixed in 897b638f660f153b7aa676efdd1611a999740e92
