### ISSUE TITLE
Telescopic Sight

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#842]
Telescopic Sight is not taboo version

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4290c272dd22546149703a10716efd96afa693d8f4934a847cdd56a7e34cd82d.json

**Comment by halogenandtoast** [comment]
A few fun things here (cards like this are very very difficult). It was the taboo version BUT:

* The ability can't be triggered if you are engaged, so it could be triggered when it should not
* There was a slight issue with targeting overrides and they were overriding in the wrong situation
* The taboo wasn't correctly handling one part

I've got a fix coming for all of this.
