### ISSUE TITLE
Shed a Light does not trigger

### ISSUE THREAD

**Issue by IngenieroYeah** [halogenandtoast/ArkhamHorror#845]
I activated the Old keyring to investigate at 0, it does not let me trigger Shade a light it goes directly to peebs and take a token.

Not apply with Gumption either

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4ad2be20327bf188a639fe75e8c47b3011cdaed9fec282833f10ad6430dd0227.json

**Comment by halogenandtoast** [comment]
@IngenieroYeah the window for that card is triggered when you click the token icon. So in your game just click on the big token and then you'll be given the window to play it.
