### ISSUE TITLE
1st Forced Effect of Agenda 3a/The Gathering moves unengaged Ghouls to the Parlor

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#85]
The effect triggers correctly, but moves the Ghouls to the `Parlor` directly, instead of 1 location towards the `Parlor`.
Specifically, the Ghoul Minion` correctly moved from the `Hallway` to the `Parlor`, while the `Icy Ghoul` has moved from the `Cellar` to the `Parlor` instead of stopping at the `Hallway`.
<img width="2032" alt="Screenshot 2022-06-22 at 11 42 35" src="https://user-images.githubusercontent.com/4399978/175013121-31ff17d6-49e3-4faf-8b7f-02df3562ad76.png">
[arkham-debug-2.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/8956948/arkham-debug-2.json.gz)

**Comment by halogenandtoast** [comment]
Fixed in 224de93ece703dbdb67c912936b16d8804cc5fbb
