### ISSUE TITLE
Extra ability on location not showing.

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#853]
Lodge Cellar says the Lodge Gates gain an action ability to spend a clue and reveal the Lodge Cellar, but this ability is not selectable. Edit to say a similar problem occurs in the "you are members of the lodge" version of the scenario.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/00deb7e265b64655e3cb81acc7630a5210c20dc69d1b363998713b02495504c2.json

**Comment by halogenandtoast** [comment]
That ability requires 1 clue per investigator which means you'll need 2, but only have one because you lost the other one to Beneath the Lodge.
