### ISSUE TITLE
Cannot obtain Alchemical Concotion

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#859]
I tried investigating a billion times (debugged myself a few actions to test) and no matter what I do I cannot seem to gain control of the out of play asset to try and defeat the monster with.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5a9349263e2a0d30b91e3bd2689d68c4d911176c6a8be85f722074f4364b1810.json

**Comment by halogenandtoast** [comment]
@foodiemonster if it is out of play then you cannot get it. The ability specifically says it must be underneath. 

One slightly annoying thing is that the way the ability is worded you can still perform it, even though you wouldn't want to

To alleviate this, I'm adding a notice to the tooltip that you won't get the Alchemical Concotion

![Image](https://private-user-images.githubusercontent.com/201288/379041825-437cdd47-358d-480b-8072-d7927aa97b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDAyNzIsIm5iZiI6MTcyOTYzOTk3MiwicGF0aCI6Ii8yMDEyODgvMzc5MDQxODI1LTQzN2NkZDQ3LTM1OGQtNDgwYi04MDcyLWQ3OTI3YWE5N2I1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQyMzMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2RjYzBjYmVjNTMwMzVkOTdhNDlkNzQ1YzRjODExNmMyYWMxYTEyNmNiM2Y1ZGNkYTcyZWQyMjZhYTAyZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QGXtEzMWtnCuCQqVeGMz0wLIpExpCDoD8xKN7MMG5I8)
