### ISSUE TITLE
Winnie Elder sign

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#861]
I think the Elder sign does not work correctly, as if you commit 2 cards and you are succesful by +4 you should return both of them

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/dfe0977827d7858eb7a9f423c48a0040e7983bd2fa0862b922bfa49787c63a5e.json

**Comment by halogenandtoast** [comment]
In your game, both Momentum and Savant were returned to your hand, the game just asked you which card you wanted to return "first", and then because there was only 1 card left, it was added to your hand automatically afterwards.
