### ISSUE TITLE
Out of sync when Zoog should spawn

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#862]
Failed a test. This triggered spawning a Zoog enemy. Clicking on Apply Results instead just causes out of sync.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6b5541d370415aee63c0f80da4844eb94f62c5e40efc1910a189d67f42b4f63f.json

**Comment by halogenandtoast** [comment]
So Zoog Burrow should have been removed earlier but the set it was in was marked incorrectly. I've fixed that and changed the zoog burrow not to fail if nothing is found.
