### ISSUE TITLE
Stuck after Quick Thinking

### ISSUE THREAD

**Issue by JesterJayJoker** [halogenandtoast/ArkhamHorror#863]
Played Quick Thinking on Nathaniels test, passed by -1 and chose to take an additional action with Monterey Jack. No choices after that.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f96cc8b33de2e19b3f5e906ed71b5dba5759f348ec876c29d21f6574955e657a.json

**Comment by halogenandtoast** [comment]
This was technically fixed a while ago so I'm not sure what happened exactly here, but to fix this you just need to step back to before you drew the token and it should resolve correctly.

However I noticed the action granted by quick thinking would not let you play Backstab so I have a fix for that going out soon.
