### ISSUE TITLE
The Raven Quill's Supernatural Record doesn't trigger a search for the named Tome/Spell Asset

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#865]
**Game ID**: 332b228a-97a3-4638-9c38-d2d5adb4725a

**Bug**: The Supernatural Record customizable upgrade for the Raven Quill reads: "When you play The Raven Quill, instead of attaching it to a named asset you control, you may search your deck, discard pile, and hand for a copy of a named asset and play it (paying its cost). Then, attach The Raven Quill to it." In this game, I have Gray's Anatomy as the named Tome asset which is correctly reflected in ArkhamDB though not in the in-game customizable hover window. When playing the Raven Quill (with no assets on board) it simply enters the discard pile (and costs the printed 3 resources) without allowing me to search for Gray's Anatomy in my deck. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1f2dfd3a86edccf3a12d7a074bd2a0f36b696e5f05e9d0b755841a467f871fc0.json

**Comment by halogenandtoast** [comment]
So I have a fix for this (will deploy tomorrow), but it would require you to reload the deck so you won't be able to have it work correctly in this scenario unless you undo to before you upgraded your deck (once I mark this as complete).
