### ISSUE TITLE
Sleight of Hand results in Game Out of Sync error

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#867]
**Game ID**: c1b85170-8e79-4043-8b08-5e2d03718e26

**Bug**: As Dexter, I'm attempting to play Colt Vest Pocket (2) with Sleight of Hand onto a board that currently has no available hand slots, but the game throws an Out of Sync error when Sleight of Hand is selected.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/91eeeca2e2350bf447904909b2284c043eb769e4549d7169d0aa6212f8f6a46d.json

**Comment by halogenandtoast** [comment]
Plot twist the error was actually Fool Me Once (1), Fix incoming.
