### ISSUE TITLE
Lola Santiago

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#869]
Lola Santiago is spending less ressources than the shroud of the location. She was working fine, so I do not know if it is related to the scenary (the yithians one)

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2742b0d38d4ca62f358fea3820cff35b8a8ea8304396c17e21e7089ec8c7c181.json

**Comment by halogenandtoast** [comment]
The issue was related to body of a yithian and how I programmed Family Inheritance, fix incoming.
