### ISSUE TITLE
All damage/horror is direct (cannot be directed to an ally)

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#87]
The `Ghoul Priest` attacked me and I was going to soak some horror on `Lita Chantler` but I can only target myself.
I couldn't rectify the situation with "Toggle Debug" because damage/horror cannot be adjusted on allies.
<img width="734" alt="Screenshot 2022-06-22 at 14 45 36" src="https://user-images.githubusercontent.com/4399978/175045366-2a0be588-71db-43d1-813e-ffb1bb1a3022.png">
[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/8958209/arkham-debug.json.gz)

**Comment by halogenandtoast** [comment]
This was recently fixed, can you pull and restart and see if it works for you. There was previously an issue with the UI that just does not show the option.

**Comment by halogenandtoast** [comment]
By restart I mean you will need to pull, docker-compose down, docker-compose up

**Comment by stefano-bragaglia** [comment]
Sorry I pulled last night my time, and I didn't realise there were already new changes to pull.
Just updated everything, and I see already the damage/horror counters below Leo De Luca that I just played.
Also tested with Guard Dog: all working fine! Thanks!
