### ISSUE TITLE
The Bedroom in A Thousand Shapes of Horror has no trigger for "found a cracked mirror"

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#874]
The Bedroom location in A Thousand Shapes of Horror has no way to spend clues for the "found a cracked mirror" trigger

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b3f98b1ac859567d71ec10c8fa0491121d4ba66a70d0dc233070a59c19c31080.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/c4c306c8-42fa-46b2-9b03-75a7eb58b522)
