### ISSUE TITLE
Kicking the Hornet's Nest seems broken

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#876]
This used to work, but now whenever I use this card it doesn't search the deck at a all - it just uses the resource and discards itself.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/033b69af3ac34c9ea6fa13130bc298d5fa44fa7386b13441410bab3a8121518e.json

**Comment by halogenandtoast** [comment]
It is just not finding an enemy here, but it should still show you the searched cards. I'll add a prompt for no cards found.
