### ISSUE TITLE
Suspicious Orderly not properly removed from the game

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#877]
In the game state, as you can see it is agenda 3a. In the resolution of agenda 2, it tells you to remove all suspicious orderly from the encounter deck and discard pile and remove them for the game. I still drew a Suspicious Orderly in the last mythos phase which should not be possible, because they should all be removed from the game.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f0297d1bfd9b1468e2f7b2a1ac960f854a3b1b6202cf0b9c0136e5abd77d0d4b.json

**Comment by halogenandtoast** [comment]
Turns out when the Corrupted orderlies were getting discarded they were reverting, I've put in a fix for this moving forward.
