### ISSUE TITLE
Out of Sync after prompt of dealing excess damage to host enemy

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#878]
Dealt 2 damage to a swarm enemy after it dealt damage to me. Received the prompt to deal excess damage to the host enemy. Clicking either that or "Do not deal excess damage" results in the game going out of sync

Edit: after refreshing the page it continues on after killing the host enemy from the excess damage, so that seems to have solved it.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d5e5ce648e8525d03940cdfe97f2c42971b5d3eb503a7f639c91e29379dcfbc5.json

**Comment by halogenandtoast** [comment]
I think the issue is that it's just getting clicked twice (because it takes so long) which causes it to error. Going to update the UI to not show the question anymore after you give a response and to show a sort of loader while it is processing.
