### ISSUE TITLE
Changing Skill test UI to be more organic and not to hide the current status of the test (so to decide if playing Fast cards or Reactions)

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#88]
A suggestion for an optimisation of the UI (since a refactoring of the UI is going to happens at some point).

When performing a Skill test, we are often prompted to "Skip playing Fast cards or using Reactions".
Once the Chaos Token has been extracted, the panel showing the current status of the test (the token extracted and, ultimately, if successful or not so far) disappears to ask to "Skip playing Fast cards or using Reactions". 
The player might decide to play a Fast card  or a Reaction depending on the current result of the test.
I propose that the status panel for the test stays visible all the time.

I also propose to implement the skill test interface as a modal pop-up in the centre of the display with the token, the status info and all other possible actions (Fast cards or Reactions) as buttons here. The current interface is a bit all over the place and is a bit confusing...

**Comment by halogenandtoast** [comment]
![image](https://github.com/halogenandtoast/ArkhamHorror/assets/201288/fbbd6f92-5af8-40d4-8f29-e74515672987)
