### ISSUE TITLE
Problem with database

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#885]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 216 for game ecd6846d-82bf-4bd4-a5ce-8739cef434cb without step 215", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f922425cbe6820a8633914a1cfb02d5b44aa629766460f785d4946837ce08f2c.json

**Comment by halogenandtoast** [comment]
It looks like you were able to make it past this.
