### ISSUE TITLE
Power word

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#889]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 626 for game 6630f671-b9ee-49dc-84a0-31cee7f30a16 without step 625", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4847120c3d38d98163883a10a6b44c8c5646a7666d4ebddc6fb7db600a164642.json

**Comment by halogenandtoast** [comment]
This is usually due to something going wrong when undoing, the debug seems to work fine so I can't investigate further because it looks like the game has been deleted.
