### ISSUE TITLE
crack the case

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#890]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 824 for game 6630f671-b9ee-49dc-84a0-31cee7f30a16 without step 823", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/74ce3e7a5a040d3d2c710dfadf334279d003f28cc4c7f15cd828ee6822ef33ef.json

**Comment by halogenandtoast** [comment]
Same as previous issue. I wonder if it was just the result of "clicking too fast"
