### ISSUE TITLE
move

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#891]
SqlError {sqlState = "P0001", sqlExecStatus = FatalError, sqlErrorMsg = "Cannot insert step 830 for game 6630f671-b9ee-49dc-84a0-31cee7f30a16 without step 829", sqlErrorDetail = "", sqlErrorHint = ""}

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ba2093425199dc48af9c47b03425006d89333b6fb31502dc9013d2497dfd752f.json

**Comment by halogenandtoast** [comment]
Same as previous issue. I wonder if it was just the result of "clicking too fast"
