### ISSUE TITLE
flamethrower issue

### ISSUE THREAD

**Issue by uygani** [halogenandtoast/ArkhamHorror#898]
No messages for chooseOne
CallStack (from HasCallStack):
  error, called at library/Arkham/Message.hs:1148:18 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Message
  chooseOne, called at library/Arkham/Investigator/Runner.hs:919:9 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Runner
  runInvestigatorMessage, called at library/Arkham/Investigator/Runner.hs:112:16 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Runner
  runMessage, called at library/Arkham/Classes/RunMessage/Internal.hs:15:29 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Classes.RunMessage.Internal
  liftRunMessage, called at library/Arkham/Investigator/Cards/RolandBanks.hs:37:26 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Cards.RolandBanks
  runMessage, called at library/Arkham/Investigator.hs:25:22 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator
  runMessage, called at library/Arkham/Entities.hs:200:51 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2843:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4573:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d5719f40604d5290b1f24c4d8a57152bb87cd9aeaba1eb394062bb7c83006831.json

**Comment by halogenandtoast** [comment]
Oh yes, you shouldn't be able to trigger the fight on the flamethrower if you are not engaged with an enemy. Fix incoming.
