### ISSUE TITLE
Waves of sin R2

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#900]
It does not advance when press continue...

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/97f6a39225a55a0c8f284f687d8a02b93775c93361888dd7332999f7e96b05c7.json

**Comment by halogenandtoast** [comment]
Sorry about this one when I deploy the fix you will need to undo a bunch of times until the resolution window goes away. Afterwards you can proceed like normal.
