### ISSUE TITLE
Game in unprogressable state during Mythos Phase

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#905]
Again, Luke was in his weakness version of Dream-Gate. Drawing any card referring to location would cause the game bug out. Tried to get around it by using select draw in the debug menu to draw a treachery that might trigger normally, but then got stuck on the Ward of Protection trigger for that treachery on Diana Stanley. Now there is no way to go back and no way to progress

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/27803e2528ad4be7600b381564f5683dbb978402f006be239c0c7666a90187a3.json

**Comment by halogenandtoast** [comment]
You should be able to proceed now.
