### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ppzo77** [halogenandtoast/ArkhamHorror#908]
no matching message
CallStack (from HasCallStack):
  error, called at library/Arkham/Classes/HasQueue.hs:148:14 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Classes.HasQueue
  insertAfterMatching, called at library/Arkham/Act/Cards/ArkhamAsylum.hs:57:7 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Act.Cards.ArkhamAsylum
  runMessage, called at library/Arkham/Act/Runner.hs:57:36 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Act.Runner
  runMessage, called at library/Arkham/Entities.hs:190:36 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2844:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4581:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/635cdc4a305e0fa7cdb9fee97e56bba0653a72d51cac6d2897492e5e1f08b19c.json

**Comment by halogenandtoast** [comment]
Should be fixed now.
