### ISSUE TITLE
multiple PMPs during another investigator's turn

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#914]
When using 2 copies of PMP in the same test, the system doesn't allow me to choose the second skill card?

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/7fb10563be0eb3146c0c8837481d702d19817c8ea19ffeab25e520f51051bb1d.json

**Comment by zzdldl31** [comment]
Also, after using PMP, I cannot commit using "the normal commit opportunity"

**Comment by zzdldl31** [comment]
Wait, why did my game start with 6 clues in the location when the location only holds 1-players worth of clues?

**Comment by halogenandtoast** [comment]
The clue issue will be fixed soon
