### ISSUE TITLE
Ward of Radiance

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#922]
Sister Mary is not in the location of Mateo and it gives you cancel the treachery

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2dad6b7ca639301e8d67879ecb7271357cf06f1e1fad0bc0057f93353814314c.json

**Comment by Lisabo1** [comment]
and it reveals 10 tokens ![image](https://github.com/user-attachments/assets/7209f620-ef5f-452e-92c7-e014800ce68d)

**Comment by Lisabo1** [comment]
And it does not cancel the treachery

**Comment by halogenandtoast** [comment]
> and it reveals 10 tokens

I think it's just showing the tokens twice, but yes, I should fix that.
