### ISSUE TITLE
Pay Day (1) appears to be granting 1 Resource fewer than expected

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#923]
**Game ID**: 697bc516-c464-45cb-a858-42c79695ade6

**Bug**: During this turn, Dexter's first action was to Move and his second was to Fight. My third action would be to play Pay Day, and since the card counts its own Play action as an action for counting resources, I should gain 3 resources. However, I only gain 2 upon playing Pay Day.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/6d2594bdb2703389f8aacca09f502b096f5560430d0ba5df5958d553d16bbb60.json

**Comment by Glitchy-Tozier** [comment]
I think this still occurs. I experience it with Tony Morgan + Haste.
