### ISSUE TITLE
Mind Over Matter playable in Mythos Phase

### ISSUE THREAD

**Issue by Malacante** [halogenandtoast/ArkhamHorror#93]
During the player window on a skill test on a Grasping Hands treachery drawn during Mythos Phase, I was allowed to play Mind Over Matter, which has "play only during your turn". The resource was spent and the card went to my discard pile, but seemed to have no effect; my agility score was still used for the test and there was no prompt to use intellect instead

**Comment by Malacante** [comment]
In a similar vein, Switchblade (2) is playable during the same window in mythos phase, despite that Fast assets are only supposed to be playable during your turn

**Comment by halogenandtoast** [comment]
I believe these are both fixed, if MoM is unplayable reopen this issue, if switchblade is not working can you open a new issue.
