### ISSUE TITLE
Wages of Sin resigning both investigators causes this bug.

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#931]
Can't progress through campaign.

no investigators
CallStack (from HasCallStack):
  error, called at library/Arkham/Game/Runner.hs:1733:13 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runGameMessage, called at library/Arkham/Game/Runner.hs:2856:13 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4581:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

Also, defeating heretics makes them disappear from threat area.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/ce938d6fee2eb4ce1910eeded1ec721cecda89db2d6303eedc69fa08d1f59422.json

**Comment by halogenandtoast** [comment]
Fix incoming for this, you'll need to step back to before resigning, but should work afterwards.
