### ISSUE TITLE
Can't proceed on The "Into the Depths" portion.

### ISSUE THREAD

**Issue by JesterJayJoker** [halogenandtoast/ArkhamHorror#932]
MissingEntity "Unknown treachery: 9c99d79e-c689-4c26-9735-5c331ce623a0\nCallStack (from HasCallStack):\n  getTreachery, called at library/Arkham/Game.hs:4363:10 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game\n  field, called at library/Arkham/Game/Runner.hs:2740:13 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner\n  runGameMessage, called at library/Arkham/Game/Runner.hs:2856:13 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner\n  runMessage, called at library/Arkham/Game.hs:4581:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game"

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/32f6b68397ba6abd35ca792c05e3888dd3a8ffbec2d0a38d5c1a3c31f4ec2c34.json

**Comment by JesterJayJoker** [comment]
I was able to fix it by going into Debug and discarding the two locked doors on the locations. It prevented the Objective from proceeding. I didn't test it on one or the other, I just discarded both.

**Comment by halogenandtoast** [comment]
Glad you got it working. I'd like to fix the underlying issue though so reopening this.
