### ISSUE TITLE
Confound (3) didn't automatically evade non-Elite enemy

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#936]
**Game ID**: 752c74de-6fb1-447e-a0b3-03dde1320355

**Bug**: I played Confound as Harvey, succeeded on the test by 1, and discovered the clue on my location but did not Evade the Pit Warden engaged with me.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/21c728e689fb51a0bc9e285766c6defbc2c2136640425ab71b4b517d0689877c.json

**Comment by halogenandtoast** [comment]
In this situation the card uses the term "Then" which means the preceding effect has to be resolved in Full. In this case the preceding effect is you must discover 2 clues, but you've only discovered 1. As such it won't trigger.

Via debug I added another clue and verified the interaction does work correctly in this case.

**Comment by mniksa3** [comment]
Wild. Thank you
