### ISSUE TITLE
Forbidden Tome (3) cannot be activated

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#937]
**Game ID**: 752c74de-6fb1-447e-a0b3-03dde1320355

**Bug**: When clicking Forbidden Tome (Secrets Revealed) to activate it, there is no Action indicator within the black box that pops up as expected. I have 12 cards in hand, so I should see a single Action icon. Though I don't think it works regardless of how many cards I have in hand anyways.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/4def9bc3d00c1a6f5dc0ef4a341e6cb4e1b8c3835a082539a5b440a650585f77.json

**Comment by halogenandtoast** [comment]
Fix incoming, I don't yet have a good way to show the reduced cost in the UI, but it will at least show the button with 4 actions symbols when you can use it.
