### ISSUE TITLE
Advancing to act 3 in Union and Disillusion leaves one of the locations missing.

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#944]
Advancing to act 3 in Union and Disillusion causes one of the locations to not appear in the center of the map, along with their investigator card. Moving fixes their avatar, but not the missing location.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3e93fda9ac7b088a3cda4fe8a1eea86a287c353a51ea795ff731682e43687dfd.json

**Comment by halogenandtoast** [comment]
I have a fix for the underlying issue, but if you want to fix your current game if you right click, hit inspect, find the console and enter:

```
sendDebug({"tag": "SetLocationLabel", "contents": ["b33abafb-8079-4995-813d-54cc5f2d8af9", "unvisitedIsle4"]})
```

It should fix it.

**Comment by kyle-tieng** [comment]
That fixed it thank you.
