### ISSUE TITLE
Opening a location causes spending of too many clues (as far as I can tell twice more than it should)

### ISSUE THREAD

**Issue by ChrisIsMyMiddleName** [halogenandtoast/ArkhamHorror#945]
Opened two locations. Both times I had to manually give back 2 clues through the debug menu to actually have 4 clues left from the 8 clues I've gathered in the first 2 locations. In the previous attempt of this scenario, I ended up in an unwinnable state because too many clues kept being spent when opening locations and I realized too late. This seems something was recently changed to the scenario in the app to cause this bug, because I have played this scenario in the app before and did not have this problem before today. It seems now it doubles the clue spending compared to the number of players. It spends 4 clues every time while it should only spend 2 with 2 players.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/dee63f940df4e785103bdbaf2c5bc83a8e075528fb402927ff485b02d1c15000.json

**Comment by halogenandtoast** [comment]
I was really worried about this being a bug, I made a change that I thought might cause this, but my initial testing avoided hitting this issue. Going to look into it and hopefully I can avoid breaking the other places I fixed with it.
