### ISSUE TITLE
Parley with Henry Deveau freezes page

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#946]
From the saved point, selecting the Parley action on Henry Deveau causes the entire page to freeze up. Refreshing doesn't fix the problem, but reloading the game in a new tab does progress to the "select a card to discard" section, but without a dialogue box prompt.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/47a666adf4c17da1d2038ae676247bcf32c33caea5203728f1c2043ed321c6a7.json

**Comment by halogenandtoast** [comment]
I think this helped uncover a major performance issue on the frontend, which was... not my fault and had to do with a faulty dependency. Upgrading it seems to have solved the issue, but I can't be 100% certain. Either way once this deploys it should work without freezing (but there is no dialog for this option regardless).
