### ISSUE TITLE
bug in prologue TCU

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#947]
Safe.fromJustNote Nothing, Could not find any matches for: HasMatchingTreachery (TreacheryWithId 2ec1431f-a9a4-4045-905d-d189b2917e5c)
CallStack (from HasCallStack):
  fromJustNote, called at library/Arkham/Classes/Query.hs:102:22 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Classes.Query
  selectJust, called at library/Arkham/Treachery/Cards/FateOfAllFools.hs:21:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Treachery.Cards.FateOfAllFools
  runMessage, called at library/Arkham/Treachery.hs:28:58 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Treachery
  runMessage, called at library/Arkham/Entities.hs:192:49 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2845:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4581:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/c65cbc5c044f9fae82d81a4d27e6515a6c2d58504575ca070585825825da3c84.json

**Comment by halogenandtoast** [comment]
The issue here is that the Fate of all Fools in front of Gavriella should have been discarded but wasn't. I have a fix coming for that, but to continue your game you can turn debug mode on and hit the discard button under that treachery to continue.
