### ISSUE TITLE
Amanda and weaknesses

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#949]
can Amanda put weaknesses beneath her? 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/87ad4969ecedfa2a1f549da63f9b7c631e362cc12f13ff2bc7ecce835439851d.json

**Comment by halogenandtoast** [comment]
> It's possible to put non-hidden weaknesses and encounter cards below her. Examples for valid weaknesses: [Doomed](https://arkhamdb.com/card/04040), [Dark Pact](https://arkhamdb.com/card/04038), [The Tower • XVI](https://arkhamdb.com/card/05042);
