### ISSUE TITLE
Ants! does not discard enough cards

### ISSUE THREAD

**Issue by morg16** [halogenandtoast/ArkhamHorror#953]
I autofailed on Ants! (horrible), and so from this gamestate I should lose all three cards from my hand, and the hiking boots that I have in play.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f764e1a3432ea934492d2cf0a8d19ce38fe022b63dc8ba270624ed2cdc4db2f2.json

**Comment by halogenandtoast** [comment]
So yeah I had 2 issues with this card:

* The test should be 4 not 3
* You should have to choose for each point
* HOWEVER, this treachery doesn't use the term must, so you can choose the first option even with an empty hand.
