### ISSUE TITLE
Devourer Below Agenda 1b

### ISSUE THREAD

**Issue by Malacante** [halogenandtoast/ArkhamHorror#96]
The Agenda 1b for Devourer Below should spawn a Monster enemy on the main path and place a doom on it. The monster is spawned but no doom appears to be placed by this effect.

**Comment by halogenandtoast** [comment]
So it turns out doom was placed, but the step that removes all doom from play was happening after this because of bad timing. I have fixed the timing of this and the doom is both placed, and not removed.
