### ISSUE TITLE
ERROR TRYING TO PLAY ENCHANTED BLADE

### ISSUE THREAD

**Issue by kortatu** [halogenandtoast/ArkhamHorror#971]
Safe.fromJustNote Nothing, missing card
CallStack (from HasCallStack):
  fromJustNote, called at library/Arkham/Investigator/Runner.hs:3397:9 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Runner
  runInvestigatorMessage, called at library/Arkham/Investigator/Runner.hs:113:16 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Runner
  runMessage, called at library/Arkham/Investigator/Cards/LolaHayes.hs:56:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator.Cards.LolaHayes
  runMessage, called at library/Arkham/Investigator.hs:25:22 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Investigator
  runMessage, called at library/Arkham/Entities.hs:200:51 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Entities
  runMessage, called at library/Arkham/Game/Runner.hs:2845:24 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4600:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3c9bd4609b95de2b27ec0836e4d75db173efd78bba4163992039dec2304de48d.json

**Comment by halogenandtoast** [comment]
Can you provide some context on what you were doing before hitting this issue. I've tried to step back to recreate the state the game is in, but can't figure out how it went wrong here. It's like the game thinks you are still searching your deck, but you are not.

**Comment by kortatu** [comment]
There was an strange thing in the setup. I could play one Tarot and Anna Kaslow from my initial hand for free, but when I needed to search for a Tarot card in my deck via Kaslow abilitie, I couldn't play Ace of Swords from my deck. I click on it but it didn't work (it wasn't highlighted in pink) . Also I had another tarot card in my hand (the Moon) but I also couldn't play it (it was not Highlighted). So my initial hand included Kaslow and two tarot cards, and I had another tarot card in my deck.
