### ISSUE TITLE
In "In the Clutches of Chaos", breaches don't get placed on locations

### ISSUE THREAD

**Issue by kyle-tieng** [halogenandtoast/ArkhamHorror#972]
The trigger for placing breaches appear, but clicking on them doesn't do anything.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/da44d0bb67a5734b40392ff67fe29f95d323a42e6aec3050c4958a4b298c3174.json

**Comment by halogenandtoast** [comment]
This scenario definitely has a few things not working, I'm fixing this and a couple of other things but please let me know if you see other issues.

**Comment by kyle-tieng** [comment]
Yeah this scenario does seem like a pain to convert digitally. I'll report any thing else I come across.
