### ISSUE TITLE
olive 2xp bug?

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#980]
No messages for chooseOne
CallStack (from HasCallStack):
  error, called at library/Arkham/Message.hs:1169:18 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Message
  chooseOne, called at library/Arkham/Message.hs:1156:27 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Message
  chooseOrRunOne, called at library/Arkham/ChaosBag.hs:311:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.ChaosBag
  resolveFirstUnresolved, called at library/Arkham/ChaosBag.hs:763:16 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.ChaosBag
  runMessage, called at library/Arkham/Scenario/Runner.hs:97:54 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Scenario.Runner
  runMessage, called at library/Arkham/Classes/RunMessage/Internal.hs:15:29 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Classes.RunMessage.Internal
  liftRunMessage, called at library/Arkham/Scenario/Scenarios/UnionAndDisillusion.hs:277:34 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Scenario.Scenarios.UnionAndDisillusion
  runMessage, called at library/Arkham/Scenario.hs:589:23 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Scenario
  runMessage, called at library/Arkham/Game/Runner.hs:2849:30 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game.Runner
  runMessage, called at library/Arkham/Game.hs:4595:19 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/2a95d00b40e3b504045f884dd8920e3db3b00da6b08426d5503844db507a76b9.json

**Comment by halogenandtoast** [comment]
Nah this bug was related to Dark Future, I had adjusted how Jacqueline gets resolved and in your situation you end up with no tokens to cancel. Fix incoming.
