### ISSUE TITLE
Elder Thing Token in Devorer Below has wrong value

### ISSUE THREAD

**Issue by Malacante** [halogenandtoast/ArkhamHorror#99]
The Elder Thing token in the Devorerer Below scenario appears to be being counted as a -10. See screenshot: https://i.imgur.com/mYSHWSn.png

**Comment by halogenandtoast** [comment]
I do not know what was happening here. If you are able to recreate this scenario, could you export the game so I can check.

**Comment by halogenandtoast** [comment]
Closing due to lack of response.
