### ISSUE TITLE
Stealthy Zoog

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#991]
Only damage dealt to swarming cards can defeat them, damage dealt to the enemy itself cannot defeat it and the damage cannot spread to its swarming cards

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/61c94af20bb6af58a6d0fd6fb30688bf059ce2b28e1465b8ddd34795fdd10827.json

**Comment by halogenandtoast** [comment]
I am not sure what the issue is. In the game you provided the enemy is a swarm enemy, not the host, so it was not defeated.

**Comment by halogenandtoast** [comment]
> Each swarm card can be attacked or dealt damage separately, but the host enemy cannot be defeated while it still has swarm cards underneath it.

**Comment by halogenandtoast** [comment]
> When a swarm card is defeated, any excess damage may be dealt to another swarm card underneath the same host enemy or to the host enemy itself.

Because the host cannot be defeated, excess damage would not carry over. You need to defeat one of the swarm cards to do this. In the app, these are designated with ![Image](https://github.com/user-attachments/assets/1b8cfe51-07aa-4099-be24-8e3f9770f4a6)
