### ISSUE TITLE
Ancient Zoog

### ISSUE THREAD

**Issue by ZhouHao268** [halogenandtoast/ArkhamHorror#993]
Ancient Zoog forced ability cannot be triggered normally

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3dd73cbaef0523a341e4220f2c5e4ada75be6ded2cb2c78271376457d2a022fc.json

**Comment by halogenandtoast** [comment]
This seems to be triggering for me. The app won't trigger the ability if it won't change the game state so the following has to be true:

* ) Ancient Zoog must be ready
* ) There must be a swarming enemy

At the point in the file you sent me, there are no swarming enemies (Ancient Zoog itself is not swarming).
